### ISSUE TITLE
project switch does not work with network folder

### ISSUE THREAD

**Issue by eXor007** [alefragnani/vscode-project-manager#10]
when i have my projects on network folder, the project switch doesn't work correctly.

Example:
Folderpath: "\\\\projects\webrepositories\projectname"

the exec looks like: "C:\\\\Program Files (x86)\\\\Microsoft VS Code\\\\bin\\\\code.cmd" "\\\\\\\\projects\\\\webrepositories\\\\projectname"

he is trying to open: "\projects\webrepositories\projectname" (it is missing a "\" at the begin)

i have tried to resolve the problem with following solution (works with network folder and also local folders):
change line 142 from:
projectPath = normalizePath(projectPath);

to:
projectPath = surroundByDoubleQuotes(projectPath);

exec looks than like: "C:\\\\Program Files (x86)\\\\Microsoft VS Code\\\\bin\\\\code.cmd" "\\\\projects\webrepositories\projectname"

os: windows 7
vscode: 0.10.8
projectmanager: 0.5.1

**Comment by alefragnani** [comment]
Hi @eXor007 ,

I could reproduce the problem. I will post a fix soon.

Thanks
