### ISSUE TITLE
projectManager.listProjects always opens project in a new window

### ISSUE THREAD

**Issue by mlewand** [alefragnani/vscode-project-manager#102]
`projectManager.listProjects` command always opens project in a new window, which makes it to act exactly like `projectManager.listProjectsNewWindow`.

## Repro Steps

1. Make sure you have the Project Manager extension installed.
1. Press `ctrl + e`
1. Execute `> project Manager: List Projects to Open` command.
1. Focus any other project and press `enter`.

### Expected

Project gets open in the current window.

### Actual

Project is open as a new window.

## Other Details

Reproduced at Windows 10, with MS VSCode, and also on a clear OSS Code compilation.

**Comment by alefragnani** [comment]
Hi @mlewand ,

This is the default behavior (the same as the new command `List Project to Open in New Window`). But for this command, you can change it to open in the _current window_. You just have to set `projectManager.openInNewWindow` setting to false.

Hope this helps

**Comment by mlewand** [comment]
@alefragnani Ohh, that's great - this is what I was looking for! 🥇 

One thing though, don't you thing it's a bit redundant and counter-intuitive? With the default configuration you have two commands with different names that do the same thing.

It might be worth to set default value of `projectManager.openInNewWindow` to `false`, and change default hotkey `alt+shift+p` to `projectManager.listProjectsNewWindow` so it keeps acting this way by default.

**Comment by alefragnani** [comment]
Yep.. I have to agree that it is a bit weird today 🙈 . 

The extension started with only one command to open projects, with _that_ setting to decide _if it should open in a new window_ (on by default). Then I felt to be needed another command to explicitly open in new window, and to avoid _break user usage_, I didn't change the default value for that setting. So, for new users, both commands works the same.

The original idea was to have only one command, but using `Ctrl + Return` for _In New Window_, just like you can do with `Open Recent` native command, and remove the setting. I registered [this issue]( https://github.com/Microsoft/vscode/issues/18064) in VSCode repo for this.

I pretend to revisit this behavior when the above issue is closed-released, or maybe based on some telemetry, I don't know yet. 

Thanks for your comments 👍
