### ISSUE TITLE
Support TreeView extension

### ISSUE THREAD

**Issue by alefragnani** [alefragnani/vscode-project-manager#103]
A new panel with projects and details.
Depends on https://github.com/Microsoft/vscode/issues/15485

**Comment by rfgamaral** [comment]
This is great news, would love to see this get implemented :)

For me, a simple list of projects that you could open (with a double-click perhaps) with the title and the system path location of the project displayed would suffice. Similar to Sublime Text's project switcher, but in the activity bar panel :)
