### ISSUE TITLE
project goto definition not work

### ISSUE THREAD

**Issue by parsibox** [alefragnani/vscode-project-manager#106]
hi
1-i create new porject with ( https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager ) 
2-open a file
3-highlight one function name 
4-click goto definition 
but not work

how can i use goto definition  in project? ( funciton defined in other project file )

**Comment by alefragnani** [comment]
Hi @parsibox ,

The `Go To Definition` command is not part of the **Project Manager** extension. It depends on the Language Extension that you use.

For instance, TypeScript and JavaScript are native in VS Code, but if you need Java or C#, you have to install their own Language Extension. Will be these extensions that will provide Code Navigation and Instellisense. 

The **Project Manager** extension purpose is to allow you to switch/open projects (folders) easily, like your _favorite projects_.

Hope this helps.

**Comment by parsibox** [comment]
i use php
and php extention is installed but not work
in netbeans when i use project it detect other function difinition

**Comment by alefragnani** [comment]
Well, I don't use PHP but I remember [this extension](https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense) being one of the most used. Maybe there are some initial setup to make it work with your PHP environment.
