### ISSUE TITLE
Project switcher on the activity bar instead of status bar

### ISSUE THREAD

**Issue by rfgamaral** [alefragnani/vscode-project-manager#108]
It would be nice to have a visual project switcher in the activity bar (the one with explorer, search, git, debug and extensions). It could replace the status bar or perhaps both could coexist with an option to pick which to use (or both).

This would depend on Microsoft/vscode#12163.

**Comment by alefragnani** [comment]
Hi @rfgamaral ,

This has already been planned in #103.. As soon as the API is made public, I will work on it :+1:

**Comment by alefragnani** [comment]
Feel free to comment on #103, sharing ideas on how it would work/what do you expect on this feature...
