### ISSUE TITLE
Occasionally fails to open projects panel

### ISSUE THREAD

**Issue by smlombardi** [alefragnani/vscode-project-manager#109]
Using Insiders (currently 1.12.0), occasionally invoking "list projects" nothing happens.  I have to quit Code, relaunch, and then it works

**Comment by alefragnani** [comment]
Hi @smlombardi ,

Is it something that _started to happen_ in recent updates (VSCode or extension), or is it something that you always had?. Also, a bit more information would be useful:

* Which OS are you using
* How is the extension configured (which parameters)
* Do you use `keybindings` or `command palette` to invoke the `List Projects` command
* Take a look at `Help / Toggle Developer Tools` and choose `Console` to check any error message.

Thanks

**Comment by alefragnani** [comment]
Do you have any news about it? Is it still happening with the latest releases?
