### ISSUE TITLE
Running the contributed command:'projectManager.listProjects' failed.

### ISSUE THREAD

**Issue by wulei** [alefragnani/vscode-project-manager#11]
i am in osx working

**Comment by alefragnani** [comment]
Hi @wulei ,

I need some more info to find out what is going on:

* Which **Code** version are you using?
* Which **extension** version are you using?
* Do you have any project saved? If yes, could you paste the `project.json´ file?
* Did  it _stopped working_ or _never worked_?

Also, could you please paste the _Console Log_? You can get it via `Help / Toggle Developer Tools / Console`?

Thanks in advance

**Comment by alefragnani** [comment]
Hi @wulei , do you still have this problem?

**Comment by alefragnani** [comment]
Hi @wulei , any news?

**Comment by alefragnani** [comment]
Since no new report has been made, I suppose it is working now.

**Comment by nonameolsson** [comment]
I have been experiencing this issue also, but on Windows 10. Will try to look for more information.
