### ISSUE TITLE
Bad "List Projects" performance after 0.15.0 update

### ISSUE THREAD

**Issue by Gama11** [alefragnani/vscode-project-manager#111]
The fix for #110 is problematic. Whenever I edit the `settings.json`, the next "List Projects To Open" is delayed by ~10 seconds, making it seem very unresponsive. Some extensions have commands that toggle a flag in `settings.json` or similar, so this ends up being the case quite often... This is with a SSD btw, but I have quite a few projects listed that Project Manager has to run through.

Project Manager should probably at least check if the relevant settings changed? ("Did projectManager folder settings change?", rather than "did _any_ settings change?").

**Comment by alefragnani** [comment]
Hi @Gama11 , I understand that, and I saw this when developing, but unfortunately there is no API available yet. It depends on https://github.com/Microsoft/vscode/issues/23325.

Changes on Settings should not happen that much, but yes, if you have some extension that uses this feature, your cache will be useless. The only thing I can do (for now) is to create a new setting to _not refresh the cache_ if your settings are changed. Doing so, you will be _disabling_ this feature.

**Comment by Gama11** [comment]
Why does this need VSCode API support? Couldn't you just store the project-manager settings somewhere, and when there's an onChange event, compare them with the new settings to see if there were any changes?

**Comment by alefragnani** [comment]
That's an alternative, but for me, the _best_ solution is that the API tells me which setting has been changed, avoiding unnecessary notifications, backup comparison or parsing.

**Comment by Gama11** [comment]
Sure, that makes sense, but it's not very hard to work around it. :)

**Comment by Gama11** [comment]
It seems even changing `tasks.json` or `launch.json` triggers a cache invalidation... I think I'll have to build project-manager from source so I can roll back to the previous version.

**Comment by Gama11** [comment]
>The only thing I can do (for now) is to create a new setting to not refresh the cache if your settings are changed. Doing so, you will be disabling this feature.

A setting like that seems like a good idea regardless - automatically updating the cache files unfortunately breaks my workflow in other ways, because I manually edited them (#99).

**Comment by alefragnani** [comment]
If #99 is released, would you still have issues with this?

**Comment by Gama11** [comment]
It wouldn't fix the performance issues / non-responsiveness, which is the main issue here.

I'm actually surprised this isn't an issue for anybody else (well, at least nobody else has commented yet). Either the auto-detection feature is little-used, or those who use it tend to run it on much less / smaller directories than I do..

**Comment by alefragnani** [comment]
There is no _known_ performance_ issue if the cache is active, because there is no need to search/detect the projects. It loads the projects from the cache file and shows the list. Also, you only complained about performance, _after_ this _auto refresh_ update. Am I right?

The question about #99 is because you said [in the comment above](https://github.com/alefragnani/vscode-project-manager/issues/111#issuecomment-296240881) that you manually edit the caches. If you don't need to edit them, your workflow wouldn't be affected.

**Comment by Gama11** [comment]
>Am I right?

Yes, but the auto-refresh tends to happen quite frequently for me...
