### ISSUE TITLE
Project List returns nothing

### ISSUE THREAD

**Issue by mrkalmdn** [alefragnani/vscode-project-manager#112]
Hi!

I have successfully saved a project but when I tried to switch between project is shows _there are no entries to pick from_.

VSCode Version: 1.11.2
Project Manager Version: 0.15.0

**Comment by alefragnani** [comment]
Hi @mrkalmdn ,

How many projects do you have saved? Are you using _VSCode_, _Git_ or _SVN_ project detection?

**Comment by mrkalmdn** [comment]
Hi @alefragnani,

It's working now. I just relaunched VSCode. 

Thanks!
