### ISSUE TITLE
Projects menu does not support MacOS native shortcuts.

### ISSUE THREAD

**Issue by robsaunders** [alefragnani/vscode-project-manager#115]
In almost all MacOS dropdown menus, using emacs shortcuts (`ctrl+n` for down and `ctrl+p` for up) works just fine, including regular visual studio code menus. I often use this in case an item I want is 1 or 2 steps down from the currently selected item.

It doesn't work in the project manager menu however which gets me every time I go to use it :P 

I feel this should be supported, those who do use them, use them constantly.

**Comment by alefragnani** [comment]
Hi @robsaunders ,

Do you mean `Ctrl + N` and `Ctrl + P` works like `Down` and `Up` navigation keys in MacOS? If yes, could you please check if this two _VSCode Core_ commands also works?

- `Go to File` (`Cmd P`) - which list files, and allows you to find some based on filter
- `Change Language Mode`: - which shows you some options to configure the language settings, and also presents the list of supported languages

I´m asking because the `List Projects to Open` command only shows a list of items, not _menu items_. At least is this _menu_ that I understand when you say _Project Manager Menu_ 😄 

Thanks

**Comment by robsaunders** [comment]
> Do you mean Ctrl + N and Ctrl + P works like Down and Up navigation keys in MacOS?

Yes :)

> If yes, could you please check if this two VSCode Core commands also works?

I've done this, I get the standard langauge mode dialog:
![image](https://cloud.githubusercontent.com/assets/129359/25800141/a39ff08a-341a-11e7-99a0-4c3c50e5d656.png)

>  At least is this menu that I understand when you say Project Manager Menu 

Okay, I'm unsure of which terminology we should be using here, but, as an example - the menu above (the language menu) allows for `ctrl + n`, `ctrl + p` navigation. Project-manager menus do not, here's the menu items I'm talking about:

![image](https://cloud.githubusercontent.com/assets/129359/25800190/d70445e8-341a-11e7-86af-15db57eea290.png)

With this menu, for example, say I want to switch down to the `ios-frames` project, I should be able to tap `ctrl + n` to select it, then hit enter. This is common throughout almost all dropdown menus (again not sure of terminology we should be using) throughout mac os, including VSCode. For example, browser location bar searches support it, spotlight supports it, even text editors like notes.app and so on support these shortcuts.

Do you need further information? I'm not sure if I'm making sense now haha :P

**Comment by alefragnani** [comment]
Yep, it makes sense 😄 

You did exactly as I intended to, and gave me all the information I needed. I just don't know _the reason_ it doesn't work.

I use the available API to display _a list of selectable items_. Maybe these keybindings are not available there, but only in _VSCode core commands_, and I should ask the VSCode team to expose this. I will check the VSCode source code to have an idea.

For instance, you can use `Ctrl + Return` to open files and folders in new tab or window, but the extensions can't use that `Ctrl` modifier. I only know if the user selected an item, but not if it was selected using `Ctrl`.

Thanks for your help.

**Comment by robsaunders** [comment]
Some additional information is that `ctrl + p` does do SOMETHING, it actually moves to the beginning of the search bar line, which is weird... as that is usually the binding for `ctrl + a`.

I'm not sure of any other plugins which expose a menu item, perhaps we could check if they support the keybindings, to determine if it's an extension-system-wide issue?

**Comment by alefragnani** [comment]
Weird :confused: 

You could try the [MDTools extension ](https://marketplace.visualstudio.com/items?itemName=seanmcbreen.MDTools) which uses the sme API to show its items.

Thanks

**Comment by alefragnani** [comment]
Hi @robsaunders , any news testing MDtools extension?

**Comment by alefragnani** [comment]
Hi @robsaunders , 

Any news about this issue? Are you still unable to use `Ctrl + N` and `Ctrl + P` to move down and up?

Last week I decided to "re-focus" on some of my extensions, and I'll start to plan milestones for each of them. But this "re-focus" will be based on community feedback/support.

Thanks

**Comment by alefragnani** [comment]
I'm closing this issue, because it has no update for more than an year.
