### ISSUE TITLE
Status bar does not appear

### ISSUE THREAD

**Issue by saquibmian** [alefragnani/vscode-project-manager#116]
The status bar does not appear for me. I'm unsure what I'm doing wrong. 

My config is as such:

```json
    "projectManager.git.baseFolders": [
        "$home/workspace/go/src",
        "$home/dev"
    ],
    "projectManager.showProjectNameInStatusBar": true,
```

This is what I see when I'm in one of my projects: 

<img width="420" alt="screen shot 2017-05-05 at 10 10 20 pm" src="https://cloud.githubusercontent.com/assets/2387703/25769113/af6150c2-31df-11e7-820b-72d2e4dd0884.png">

**Comment by alefragnani** [comment]
Hi @saquibmian ,

The status bar feature was originally created to appear only for the **Favorite Projects**, which are those that you manually `Save`, not for the _auto-detected_ VSCode, Git and SVN.

But that's a good idea to be visible for these other projects, so I will take a look how to accomplish this.

Thanks for your suggestion.

**Comment by serkanyersen** [comment]
@alefragnani I just converted all project settings to favorites just to enable this feature, but it's not working even for that.

**Comment by alefragnani** [comment]
@serkanyersen which OS are you using? Could you share a piece of your `projects.json` file?

**Comment by serkanyersen** [comment]
I'm using it on mac os x.

My projects.json looked like this.

```json
[
    {
        "rootPath": "$home/src/design-kit/",
        "name": "Design Kit",
        "group": "Company"
    },
    {
        "rootPath": "$home/src/express-app/",
        "name": "Express App",
        "group": "Company"
    }
]
```

this of course is a shortened version

**Comment by EvtK** [comment]
+1 for having displayed to projectname in the statusbar for auto detected projects. Looking for this function.

Great plugin. Thanks

**Comment by alefragnani** [comment]
🏃 

To make things easier, it will work only if `projectManager.cacheProjectsBetweenSessions` is `true`, because doing so, I don't have to _detect repos_ while opening/loading a project.

Stay tuned for an update this weekend

**Comment by EvtK** [comment]
Thanks for the update. So far  I regret reporting that it still isn't working on my side here...

```
   "projectManager.vscode.baseFolders": [
        "c:\\git\\Repos"
    ],
    "projectManager.vscode.ignoredFolders": [
        "node_modules",
        "out",
        "typings",
        "tests"
    ],
    "projectManager.vscode.maxDepthRecursion": 1,
    "projectManager.showProjectNameInStatusBar": true,
    "projectManager.cacheProjectsBetweenSessions": true,
    "projectManager.openInNewWindowWhenClickingInStatusBar": true,
```

even re-installed plugin. No luck :(

**Comment by alefragnani** [comment]
Hi @EvtK , 

That's not good 😢 . Could you check if there is some message in `Developer Tools - Console`?

**Comment by EvtK** [comment]
@alefragnani  nope, just checked. I even switched of git blame plugin because it also makes use of the bar, but no effect.

**Comment by swarnendubiswas** [comment]
@alefragnani I have the same problem where I have `cacheProjectsBetweenSessions` is `true` (it is the default now), but I do not see the Status bar entry. I have seen this for at least the last few releases of VS Code (say 1.22 and greater).
