### ISSUE TITLE
$(git-branch) on project titles

### ISSUE THREAD

**Issue by blackjid** [alefragnani/vscode-project-manager#119]
Hi, I just wanted to know if this is the expected behavior or not.

![image](https://cloud.githubusercontent.com/assets/228037/25853668/a4459c5c-349b-11e7-8c96-6a52415f5b5c.png)

**Comment by alefragnani** [comment]
Hi @blackjid ,

It's not the expected behavior :smile: . 

I already noticed that, but it's a VSCode error, already reported https://github.com/Microsoft/vscode/issues/21243. Unfortunately, no ETA yet.

Thanks

**Comment by alefragnani** [comment]
The original VSCode issue has been fixed a month ago, in February 2018 milestone. I tested Stable and Insiders releases and both are ok. 
Closing...

**Comment by blackjid** [comment]
Awesome! thanks
