### ISSUE TITLE
Save project includes whole path

### ISSUE THREAD

**Issue by csholmq** [alefragnani/vscode-project-manager#12]
The suggested project name includes the whole path. Not just the root dir.

OS X using Insiders build.

**Comment by alefragnani** [comment]
I guess the Stable build has the same problem, right?

**Comment by csholmq** [comment]
On Win10, stable build it actually works. Not sure if it's platform or build. I'll confirm tonight but should be easy enough for you to reproduce if you have access to OS X or Win
