### ISSUE TITLE
Link project with theme

### ISSUE THREAD

**Issue by msageryd** [alefragnani/vscode-project-manager#120]
Thank you for an awesome plugin.

It would be really cool if I could link each project with a theme. Or even better, just the background color in the editor. I'm mostly using Monokai, which makes two projects open at the same display kind of blending together.

Ideally I would like to pick a background color per project. It would be "black", "brown", "another brown", etc.

**Comment by alefragnani** [comment]
Hi @msageryd ,

Do you know that you already can do that, using the `Workspace Settings`? 

```
{
  "workbench.colorTheme": "Kimbie Dark"
}
```
Or do you need something to override that?

**Comment by msageryd** [comment]
@alefragnani: Wow, that's great!
I had missed that.

It completely solves what I want to do.
I'm closing this issue.
