### ISSUE TITLE
"List Projects to Open" and "List Projects to Open in New Window"

### ISSUE THREAD

**Issue by DavidSvetlik** [alefragnani/vscode-project-manager#122]
Hi, first thing - thank you for your great extension!

I have only small issue with it, you see, named options:

- "List Projects to Open"
- "List Projects to Open in New Window"

Are both behaving the same way, meaning they always open project in new window. I would like to have an option to open project within the same window (automatically closing the current one).

Thanks,
David S.

**Comment by Gektorian** [comment]
+1

**Comment by alefragnani** [comment]
Hi,
 
The _history_ behind this is described in #102 :smile: In the end, you could update `"projectManager.openInNewWindow"` to `false`. 

But in fact, I guess I'll not wait for the VSCode issue to be resolved. I'll release an update that removes this setting, and maintains both commands.

Stay tuned...
