### ISSUE TITLE
Project list very slow to show when having remote projects

### ISSUE THREAD

**Issue by egabrum** [alefragnani/vscode-project-manager#125]
One of my projects is in a remote folder that is not always available. When this is the case, the project list takes a veeery long time to show up, I suppose while trying to reach that remote folder.

It would be great if the list of already available projects showed immediately, leaving the non-reachable as "pending" until they are actually reached. 

Or, at least, mark the non-reachable projects as such so that I don't have to wait 30 seconds _every_ time that I try to open the list of projects.

thanks.

**Comment by alefragnani** [comment]
Hi @egabrum 

This must be happening because the _check for invalid path_, which display a message below the unavailable (wrong/deleted) paths. I think that, because the project list is cached, once created.

About _display those available and include the others latter_ idea, unfortunately there is no API available for that, so all items must be added at once.

I'll try to reproduce the problem, to see if this is the reason.

**Comment by alefragnani** [comment]
I tested remote locations, using **mapped drives** and **unc notation**, and didn't see any performance issues. 

I have some questions to try to help you:

- Which OS are you using?
- Which network config do you have?
- Are you using **Favorite projects** or **VSCode/Git/SVN autodetection**, and how is configured?

**Comment by egabrum** [comment]
I might not have explained myself properly. I have a few favorite projects, most of them on my local drive.
However, some are on a remote machine (path is \\machine\sharedFolder\projectFolder).

When I'm not connected to the LAN where 'machine' is and try to open a project from my list, it takes a long time to show my list of projects; I suppose because it's trying to reach 'machine' and won't show the list until it has reached or timed out trying to reach all of the project folders.

Additionally, every time I try to open the list, it tries to reach the unreachable folder again, so I'm again 'punished' with a waiting time before anything is shown.

I'd prefer if the list showed right away what is reachable. The rest might be marked as 'pending' or 'unreachable'.

- Which  OS are you using?
W7.
- Which network config do you have?
Not sure how to answer this.
- Are you using Favorite projects or VSCode/Git/SVN autodetection, and how is configured?
Favorite.

**Comment by alefragnani** [comment]
Ok, I didn't test for _unavailable_ network folders, just network folder, which _where available_ at the moment. The delay you experienced must be the _check timeout_.

As I said, the list is cached, but the _check for invalid _ is not (and I don't intend to do). A workaround would be _not check_, but it would punish you when selecting that folder/project. Based on your scenario, I agree that it would ignore the check while listing, making it available right away :+1: 

I'll update the extension to accomplish this. Probably adding a config to decide if it would maintain the check _prior_ or not, just for those that like/prefer having the _unavailable_ indicator on the list.

Stay tuned
