### ISSUE TITLE
Getting "command not found" on v0.18.0

### ISSUE THREAD

**Issue by mklinga** [alefragnani/vscode-project-manager#126]
The title probably says it all. I have bound a key to the "List Projects to open in new window" but pressing the key results in error
```
command 'projectManager.listProjectsNewWindow' not found
```

**Comment by mklinga** [comment]
Turns out that every single option for vscode-project-manager returns "command not found", not just listProjectsNewWindow.

I'm on MacOS Sierra

**Comment by alefragnani** [comment]
Hi @mklinga ,

I suggest you to reinstall the extension. If every command fails, it's probably an installation issue.

Had you updated from previous version, or is the first time you installed the extension?

Hope this helps

**Comment by mklinga** [comment]
Thanks @alefragnani , re-installing the plugin did the trick. Fwiw, I updated the plugin from the previous version and apparently something went wrong during the process.
