### ISSUE TITLE
Not shown in status bar 

### ISSUE THREAD

**Issue by qdechochen** [alefragnani/vscode-project-manager#127]
Project name is not shown in status bar. Mac 10.12.5 Sierra. But all my projects are shown when run List projects to open.

<img width="735" alt="pm" src="https://user-images.githubusercontent.com/1181011/26960741-1de337f8-4d0c-11e7-963a-150e6b10575f.png">

settings.json:
```
....
"projectManager.groupList": true,
"projectManager.showProjectNameInStatusBar": true
.....
```

projects.json
```
[
	{
		"name": "xxxx App",
		"rootPath": "/Users/xxxx/WorkFolder/xxxxx/xxxxx",
		"paths": [],
		"group": ""
	},
........

```

**Comment by alefragnani** [comment]
Hi @qdechochen ,

That's weird, it was fixed in previous releases, so maybe something is missing. I'll try to take a look, but unfortunately I don't have a Mac to test, if this is something related to the OS paths.

By the way, are you updating the `projects.json` file by hand, or using the`Sabe Project` command? I'm asking because it would store `$home` instead of `/Users/your_user` when using the `Save Command`.

**Comment by qdechochen** [comment]
Hi Alessandro,

Thank you very much for the reply.

I edited the projects.json by hand. And the content in the screenshot is exactly what it is in the json file. As what I mentioned, Ctrl+Shift+P>project manager: list projects to open works perfectly good. Does that mean the path is correct?

And the extension I got is the latest version. It isn’t asking me to update. 

Hope that you could find the reason and fix it soon. Good luck man ~





Echo

**Comment by alefragnani** [comment]
Hi @qdechochen , sorry for the delay.

Could you test something to me? Edit your `projects.json` file and replace your _home path_ (**"/Users/xxxx"**) for `$home`? This is a special variable created to allow sync between different machines, and I think this can be the reason for the issue. If it works, I have an idea how to fix.

Thanks for your help.

**Comment by qdechochen** [comment]
Hi Alefragnani,

Good news! You are right, it is the reason for the issue.

I did some tests, and found that it shows in the status bar only when the rootPath of the CURRENT ACTIVE project contains $home.

Hope to see your new version soon. 


BR,
Echo

> 在 2017年6月17日，下午10:30，Alessandro Fragnani <notifications@github.com> 写道：
> 
> $home

**Comment by alefragnani** [comment]
That's great! It should be released later today. 
Stay tuned...

**Comment by qdechochen** [comment]
It works perfectly good now!
