### ISSUE TITLE
Multiple paths for a project

### ISSUE THREAD

**Issue by sho-87** [alefragnani/vscode-project-manager#128]
I often work on a project across different machines, and due to various reasons (different OS, different partition/hard drive setup), the same project will have different paths on each computer. For example on my desktop it might be `D:\Projects\myproject` due to having multiply drives, but on my laptop it might be `~/Git/myproject`

Is it possible to set multiple paths for the same project, so that when I sync my settings between computers it will check for the appropriate path on a given machine and load that up?

I believe its a slightly different issue than #46 (but the other issue isnt really clear, so not sure)

**Comment by alefragnani** [comment]
HI @sho-87 ,

I see your point, but I guess it would be really complicated to manage different path for the same project, specially if you work in _similar_ environment, which would sometimes, have a valid path, but for an invalid/unintended project. 

Have you tried to use the [Automatic Detection of Projects](https://github.com/alefragnani/vscode-project-manager#automatic-detection-of-projects). You just have to add all different paths in your `User Settings`, and it would show the projects available in each computer, independently.

Hope this helps.

BTW, that's totally different from #46 😄

**Comment by sho-87** [comment]
that looks really useful!

one thing I noticed about that option, however, is that I don't manually define a project name so the `"projectManager.showProjectNameInStatusBar": true` option doesn't do anything. Is it possible for the directory name to be displayed in the status bar in the case of automatically detected projects like this?

**Comment by alefragnani** [comment]
It will be, when #116 is released. 

The idea is to use, at least, the folder name, just like presented in the `List Projects...` commands.
