### ISSUE TITLE
Support VSCode Multi-root Projects

### ISSUE THREAD

**Issue by alefragnani** [alefragnani/vscode-project-manager#129]
Since VSCode is recording the **Multi-root Folders** inside `projects.json`, the ideas it to _load_ these projects and show them with `Project Manager: List Projects to Open` commands, just like VSCode, Git and SVN

**Comment by alefragnani** [comment]
🏃

**Comment by alefragnani** [comment]
It was _ready_ but the new iteration in Insiders version completely changed how it works. Instead of an entry in `User Settings`, it now has a new `Workspaces` concept, with no API to access. 
I will hold any implementation until it is released in Stable, with proper API.

**Comment by alefragnani** [comment]
Depends on Stable release and proper API

**Comment by alefragnani** [comment]
Unless some API that _lists the registered workspaces_ in the future, I can't add this feature. I will close it until there.

**Comment by richarddavenport** [comment]
Wouldn't there be some way to add a `.code-workspace` file as a "project"?
If we could add just the `.code-workspace` file to the projects list, then we could open workspaces.
I would definitely help with this, if you think this is doable. Thanks!

**Comment by alefragnani** [comment]
HI @richarddavenport ,

I didn't find any API that tells me _the known workspaces_, because since each workspace is a separate file, which can be anywhere. Unless the VS Code team adds API for that, I think it would have a new entry in the extension to _list all workspaces_, and then, make them available in the Pick List.

I pretend to _wait_ for stable API/concept before adding that to the extension. At least being released  in the _Stable_ channel 😄
