### ISSUE TITLE
openInNewWindow not working on OS X

### ISSUE THREAD

**Issue by csholmq** [alefragnani/vscode-project-manager#13]
I know it says so in the README, but I feel there should be a ticket for it.

**Comment by alefragnani** [comment]
Hi @csholmq . It was reported in #7 that with **Code February Release** this setting is now working. But first, you have to install the _Shell Command_. 

Could you take a look at the comments in that issue, and check if it works for you?

Thanks

**Comment by csholmq** [comment]
@alefragnani Confirmed to work!

Ran `Shell Command: Install 'code' command in PATH` which did the trick!

`"projectManager.codePath": "code-insiders"` for Insiders. 
`"projectManager.codePath": "code"` for normal build.

`"projectManager.openInNewWindow": false` works!
`"projectManager.openInNewWindow": true` works!
