### ISSUE TITLE
How to hide folders by project?

### ISSUE THREAD

**Issue by ribeiroevandro** [alefragnani/vscode-project-manager#133]
In Sublime Text for example, I can configure to hide the view of a folder just inside the project, using `folder_exclude_patterns`, how would it be possible to have the same resource?

**Comment by alefragnani** [comment]
Hi @ribeiroevandro ,

Have you tried `"files.exclude"` setting? It's native in VSCode. If it works for you, you just have to configure it in `Workspace Setting` and it's done. When you open the project using the extension, VSCode itself will use this setting.

But, if this setting don't fit your needs (maybe it doesn't hide all the files/folders you want), you may be out of luck. You will need a new extension to _extend/replace_ the  _Explorer_ tab, and if I remember right, there are just a few available right now, or you should fill an issue in VSCode to extend the `"files.exclude"` setting to be more like `folder_exclude_patterns`.

Hope this helps.
