### ISSUE TITLE
git worktrees are not discovered as projects

### ISSUE THREAD

**Issue by joelhock** [alefragnani/vscode-project-manager#134]
a git worktree ( https://git-scm.com/docs/git-worktree ) has a .git directory entry that is not a folder with a config file, but rather just a plain file that points to the repo directory, e.g:
```
cat .git
gitdir: ../dev/.git/worktrees/worktree-dev
```
which is not detected by
```
    public isRepoDir(projectPath: string) {
        return fs.existsSync(path.join(projectPath, ".git", "config"));
    }
```
i'd say checking for the existence of a .git file or directory is enough to know you're in a directory that should be added as a project, but I might be missing something.

**Comment by alefragnani** [comment]
Hi @joelhock ,

I didn't know about _git worktree_ (still moving from other VCS) and used a snippet to check for git repos. I will update the detection to support this as well.

Thanks for reporting 👍

**Comment by hellorayza** [comment]
Is it supported display worktree now?😀
I use git worktree usually by this way : 
`git worktree add --track -b dev ../project_dev`
and folder tree like this:
```
├── project
│   ├── .git (foder)
├── project_dev
│   ├── .git (file)
```

**Comment by alefragnani** [comment]
Hi @hellorayza ,

It _should be working_. At least, since I closed the issue and released the update (more than 2 years ago), no one has complained about it 😬 .

Isn’t working for you?

**Comment by sparcbr** [comment]
It's working. You need to hit refresh button on project manager sidebar after you just created a new git worktree.
Just pointing out this as I just came here looking for a solution kk
