### ISSUE TITLE
Switching between projects now closes previous project

### ISSUE THREAD

**Issue by dsteinbach** [alefragnani/vscode-project-manager#135]
Since updating my vscode to 1.14.2 I can no longer keep more then one project open. When I switch projects it closes the previous. I run things in the terminals of these projects and don't want those processes killed. I organize my terminals by project so I need it to behave like it used to and leave the project running.

**Comment by AStupidBear** [comment]
@dsteinbach Why did you close this?

**Comment by mikeymurph77** [comment]
Is there a work around for this? I have many projects that should all run together, and switching projects kills the process. I would love if I could keep the terminal process running in the background when I switch to another project.

**Comment by alefragnani** [comment]
Hi @mikeymurph77 ,

There are two different commands available, one for each scenario.

If you want to open projects in _another window_, you have to use the `List Project to Open in New Window` command. The project will be opened in another VS Code window, keeping your current window intact. Unless you already have the project opened, so it will just _focus_ it.

Hope this helps
