### ISSUE TITLE
[question] "when" clause context for project list?

### ISSUE THREAD

**Issue by nwaywood** [alefragnani/vscode-project-manager#136]
I have the following settings in my `keybindings.json` to allow vim like navigation in the command prompt (`cmd+shift+p`) and quick open (`cmd+p`). However these settings don't seem to affect the project list dialog.

```
{
        "key": "ctrl+j",
        "command": "workbench.action.quickOpenSelectNext",
        "when": "inQuickOpen"
},
{
        "key": "ctrl+k",
        "command": "workbench.action.quickOpenSelectPrevious",
        "when": "inQuickOpen"
}
```

Is there a `when` that clause that can be used to bind keymaps to the project list?

**Comment by alefragnani** [comment]
Hi @nwaywood ,

No, it doesn't have a `when` clause, but it should be added fairly easy 👍. 

But I have a question: Would it really work for your _vim like navigation_, or would it end up with the same issue from #115?

**Comment by nwaywood** [comment]
Hi @alefragnani,

I don't think that the issue from #115 will happen here. In #115 it is trying to leverage MacOS functionality. However, if there is a `when` clause that explicitly adds a keybinding then I don't think there will be an issue :)

**Comment by alefragnani** [comment]
Hi @nwaywood ,

Check out the new release 😄
