### ISSUE TITLE
Open in new window when using keyboard shortcut or command

### ISSUE THREAD

**Issue by tgreen7** [alefragnani/vscode-project-manager#138]
I see the setting:
`projectManager.openInNewWindowWhenClickingInStatusBar`

But like the setting says this only triggers the new window to open when using the status bar button to list the projects but not when using the keyboard shortcut or the command palette. Is there a way to make the projects always open in a new window?

**Comment by alefragnani** [comment]
Hi @tgreen7 ,

That's right. This setting works only for the StatusBar. 

You may not have noticed, but the extension has two commands to open projects:
- List Projects to Open `(Shift + Alt + P)`
- List Projects to Open in New Window 

You just have to use the last one. If you prefer, reassign the Keybinding to that, or create a new one (like I did), for instance `Ctrl + Shift + Alt + P`.

Hope this helps

**Comment by tgreen7** [comment]
Perfect. Thanks
