### ISSUE TITLE
Changes to ignoredFolders not respected until VSCode is restarted

### ISSUE THREAD

**Issue by Gama11** [alefragnani/vscode-project-manager#139]
As the title says, it looks like changes to `ignoredFolders` settings are only respected after VSCode is restarted (potentially some missing config change event handling).

I added a folder to `projectManager.git.ignoredFolders` and ran the `Project Manager: Refresh Projects` command, and the newly generated project list still contained the projects from the newly ignored folder.
After restarting VSCode and running the refresh projects command again, projects in the ignored folder were no longer present.

**Comment by alefragnani** [comment]
Hi @Gama11 ,

That's true. It only detects changes in `baseFolders` settings. 

Thanks for reporting
