### ISSUE TITLE
Closed sidebar panels return with each new project

### ISSUE THREAD

**Issue by tdmalone** [alefragnani/vscode-project-manager#144]
Thank you firstly for your work with VSCode, especially with this plugin - which I find essential for daily work. :) I'm new to VSCode and am still getting my head around how it is architected (especially with regard to projects/workspaces) so my apologies if this isn't a plugin specific issue.

I'm finding that, when I switch to a new project, any sidebar panels I previously removed all return again. I can close them again and this sticks for the project, but when a new project starts they'll all be back again.

I've tried to find a file with the project-specific sidebar settings so I could at the very least bootstrap new projects with my desired config... but I can't find this either on my Windows or Mac environment.

Is there a project config file somewhere I can edit... or alternatively a way to make the sidebar settings global and not project-specific?

**Comment by alefragnani** [comment]
Hi @tdmalone , I'm glad to know it's being helpful.

I also detected this behavior, and unfortunately, it's how VSCode works. When you hide a sidebar panel, it _stores_ this information only for that workspace/folder, with no _global_ setting. 

I had created #143 to control its visibility, directly in the `Settings`

Hope this helps

**Comment by tdmalone** [comment]
Thank you @alefragnani for the quick reply! I will watch #143 to follow the progress of that.

Do you happen to know where VSCode stores the information for that workspace/folder? If I can find that, I can work out an interim workaround.

**Comment by alefragnani** [comment]
It's probably inside `%APPDATA%\Roaming\Code` (on Windows). Maybe in `LocalStorage`.
