### ISSUE TITLE
Move projects out of enclosing folder

### ISSUE THREAD

**Issue by tyrw** [alefragnani/vscode-project-manager#148]
Projects seem to be trapped in "Favorites" folder: 
![screen shot 2017-10-12 at 10 48 07 am](https://user-images.githubusercontent.com/819876/31510922-e39eb3ec-af3a-11e7-9a8e-8b16aad8ef43.png)

This is a problem because switching between projects collapses the folder.

Setting `"projectManager.groupList": false` does nothing.

Would be nice to have these outside of any "containing" folders so that it doesn't collapse every time.

**Comment by alefragnani** [comment]
Hi @tyrw ,

The `Favorites` folder contains the projects that you _saved_. Just like the `Git`, `SVN` and `VSCode` folder contains the projects from that kind of repo/folders that you added with _autodetection_. The folders exist for _organization purpose_. The `groupList` setting has no influence in the TreeView.

Instead of _move projects outside the enclosing folder_, I will take a look if there is an easy way to _save/restore_ the collapsing state of that folders.

Hope this helps

**Comment by rodrigobdz** [comment]
I agree with @tyrw's suggestion of removing the favorites folder completely.

**Comment by alefragnani** [comment]
Well, _move projects outside the enclosing folder_ has two votes now. 😄 

Feel free to send a PR for that. Just add a `User Setting` to decide if it should _organize_ the projects. Something like `projectManager.treeview.groupProjects`

**Comment by mirkea** [comment]
+1 on either having the option to remove the grouping alltogether or at least avoid having to expand them every time

**Comment by tyrw** [comment]
FYI this is now natively available through "Workspaces" https://code.visualstudio.com/docs/editor/multi-root-workspaces

**Comment by alefragnani** [comment]
What do you think about #183?

**Comment by monkeydri** [comment]
Yes #183 is great and kind of solves this issue. But it just feels awkward to have a subdirectory "Favorites" under "Projects", projects should be directly accessible under "Projects" IMHO.

The thing is I don't really get the idea, the other categories (git, svn) are a different kind than Favorites. For ex I could have a favorite project which uses git.

**Comment by alefragnani** [comment]
**Favorites** are those that you _intentionally saved_ using `Project Manager: Save Project` command. It is any folder (even non-VCS) that you would like to easily access. The other kind of projects (VSCode, Git, Mercurial and SVN) are auto discovered, based on `baseFolder` setting, and so, are considered _just another project_. 

Off course you can save any Git or SVN project as **Favorite**, and when you do so, the extension understands that _you like this project_ and it will be presented at the top of the list.

Hope this helps

**Comment by monkeydri** [comment]
My bad I did not get it while reading the README ! This is perfect, the `baseFolder` setting is exactly what I needed, thank you for the explanation !

**Comment by alefragnani** [comment]
**Version 8** was released 3 months ago. It incorporates #183, and the extension now has its own **Activity Bar**, with a separate panel for each project. 

With this approach, there will be no **Favorites** folder anymore, and all projects are presented in _root level_. So, issue was _"solved"_, and I'm closing it.
