### ISSUE TITLE
Project Name in Status Bar

### ISSUE THREAD

**Issue by advokatb** [alefragnani/vscode-project-manager#152]
Hi.
When I add `"projectManager.showProjectNameInStatusBar": true,` to my config status bar doesn't change.

![default](https://user-images.githubusercontent.com/6189889/32453024-dc5653fe-c323-11e7-97ca-eb77b3cbfa4c.png)

I know this is default option but it doens't work for me either.

**Comment by alefragnani** [comment]
Hi @advokatb ,

Yes, this is ON by default. 

Which OS are you using, and which kind of projects do you have? 

I mean, I see a  _lightning_ icon in your print, and I use the same icon to display _SVN projects_, which are automatically detected by `projectManager.svn.baseFolders` config. If this icon is related to other extension, that's ok... but if this is from *Project Manager*, then the status bar is being added, but the _project name_ is missing.

Thanks for the info

**Comment by advokatb** [comment]
I'm using Windows 10 Pro x64.

This  _lightning_ icon is for cached CSS classes (**IntelliSense for CSS class names** ext). I didn't add any groups for projects (like SVN, Git etc).

I use only project.json with such entries:
```
   {
        "name": "XVM (advokatb)",
        "rootPath": "c:/Games/World_of_Tanks/res_mods/configs/xvm/advokatb",
        "paths": [],
        "group": "Configs"
    },
```

The only change in my config related ProjectManager is `  "projectManager.showProjectNameInStatusBar": true,`

**Comment by alefragnani** [comment]
@advokatb , I found the problem. 

It's related to how you defined the path. For Windows, it uses `\\` instead of `/`, so when it looks for a path in the project list, it won't find it, because it uses a _simple string comparation_.

I'll update the routine to ignore this difference, but in the meantime, you could update your `projects.json` file, replacing `/` for `\\`.

Hope this helps

**Comment by advokatb** [comment]
Yes, that helped.
![default](https://user-images.githubusercontent.com/6189889/32558347-3035b48a-c4ad-11e7-98a3-e07888ea97af.png)
Thanks!
