### ISSUE TITLE
command 'projects.editConfig' not found

### ISSUE THREAD

**Issue by gerhardcit** [alefragnani/vscode-project-manager#153]
In Vscode Version 1.19.0-insider (1.19.0-insider)

d6fbdcf19716910b26ea81efc95724f2fabe5aa6

None of the project commands work.

```command 'projects.switchGroup' not found```
```command 'projects.openInNewWindow' not found```

I removed the plugin, reinstalled it. Same thing.

It works fine in Version 1.18.0 (1.18.0)

dcee2202709a4f223185514b9275aa4229841aa7

**Comment by alefragnani** [comment]
Hi @gerhardcit ,

I think you are using [Projects+](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-projects-plus) extension, am I right? Please, post your issue in it's repo (https://github.com/fabiospampinato/vscode-projects-plus/issues)

Hope this helps 😄
