### ISSUE TITLE
Hide Project

### ISSUE THREAD

**Issue by advokatb** [alefragnani/vscode-project-manager#154]
Is it possible temporary hide some unused projects?
I've tried to comment them in _project.json_ but comments do not work?

**Comment by alefragnani** [comment]
Hi @advokatb ,

First of all, sorry for taking so long to answer. 

Unfortunatelly no, you can't _hide_ projects. The extension does not expect/recognizes comments in the `projects.json` file, so it won't take effect.

But I think that a `Enabled` state for projects should fit your needs. You just _disable_ the project, and it wouldn't be visible.

```json
{
    "name": "Pascal MI",
    "rootPath": "c:\\PascalProjects\\pascal-menu-insight",
    "paths": [],
    "group": "",
    "enabled": false
}
```

What do you think?

**Comment by advokatb** [comment]
Thanks. Should it work now? Or you are only plan to implement it?
```
    {
        "name": "site.com",
        "rootPath": "d:\\Web\\Projects\\client -\\site.com\\theme\\themename",
        "paths": [],
        "group": "General",
        "enabled": false
    }
```
I still can see project in project list by Alt+Shift+P and by clicking on Status Bar icon.

**Comment by alefragnani** [comment]
It's not available yet, it's just an idea 😄

**Comment by advokatb** [comment]
Waiting for implementation ;)

**Comment by advokatb** [comment]
Any thoughts about when could we test it? 🥇

**Comment by advokatb** [comment]
@alefragnani can you please take a look on this enhancement? 
Thanks.

**Comment by lysbug** [comment]
Hi, it will be the super useful thing! Could develop this snippet, I guess everybody will be pleased with you, Thank you.

**Comment by advokatb** [comment]
Any thoughts about when this feature can be implemented?

**Comment by alefragnani** [comment]
I’m planning to release an update with the PR after the New Years holiday. Together with the #204.

**Comment by alefragnani** [comment]
The PR #226 was merged.
The new version will be released later today
