### ISSUE TITLE
not work in MacOs 10.13.1 ?

### ISSUE THREAD

**Issue by geraldlrh** [alefragnani/vscode-project-manager#155]
all command is not work

**Comment by alefragnani** [comment]
Hi @geraldlrh ,

Do you see any message when you try to run the commands? Also, take a look at `Toggle Developer Tools / Console` to see if any aditional message appears.

**Comment by geraldlrh** [comment]
I found it working, but it took a long time. And console has nothing

**Comment by alefragnani** [comment]
Good to know it worked 👍 . 

Just for info, if you use the _auto detection_ for `git`,  `svn` or `vscode`, it could indeed take some time. But since it _caches_ the result, the next time you call `List Projects`, it would be almost instantaneous.
