### ISSUE TITLE
Project List has an unexpected option

### ISSUE THREAD

**Issue by ifooth** [alefragnani/vscode-project-manager#156]
Issue:
- When i config automatic detection of projects, it's work prefect.
![image](https://user-images.githubusercontent.com/1853121/33365609-b5693fe2-d523-11e7-96af-fd15a4a74e05.png)
but when i input $ and try select project, it just appears
![image](https://user-images.githubusercontent.com/1853121/33365370-f5da2326-d522-11e7-979b-740752ac6143.png)

Work Environment:
- Mac High Sierra(10.13.1)
- Iterm2 /zsh with oy my zsh (lastest)
- VSCODE Version 1.18.1
- vscode-project-manager (Latest)

Can help? thanks

**Comment by alefragnani** [comment]
Hi @ifooth ,

This is the same issue as #119. Unfortunately, this is caused by a VS Code bug (reported in https://github.com/Microsoft/vscode/issues/21243). No ETA for that, sorry.
