### ISSUE TITLE
refresh projects cmd misses projects in user settings

### ISSUE THREAD

**Issue by MattDiMu** [alefragnani/vscode-project-manager#157]
When using the `refresh projects` command, all projects from my user settings file (projectManager.git.baseFolders) are lost and only the custom added projects in projects.json are shown.

After changing my user settings file all projects (from user settings and from projects.json) are shown correctly.

This issue is reproducable on

Win7, vscode 1.18.0, ProjectManager 0.23.0

**Comment by alefragnani** [comment]
Hi @MattDiMu ,

That's weird. I couldn't replicate this issue in any version (stable or insider). Do you have a step by step scenario?

Could you check if you have `projectManager.cacheProjectsBetweenSessions` set to false?

Hope this helps

**Comment by MattDiMu** [comment]
I can reproduce the issue with projectManager.cacheProjectsBetweenSessions set to false as well.

My step-to-step scenario is quite simple. I simply execute the command "ProjectManager: Refresh Projects" and all Projects added by "projectsManager.git.baseFolders" in the user settings file are gone. As soon as I update "projectsManager.git.baseFolders" (changing it to something else and reverting this change), all Projects are shown again.

**Comment by alefragnani** [comment]
🏃

**Comment by alefragnani** [comment]
Released in 0.24.1

**Comment by MattDiMu** [comment]
Thx, seems to work!
