### ISSUE TITLE
what is a "VSCode project" 

### ISSUE THREAD

**Issue by wangxiexe** [alefragnani/vscode-project-manager#158]
As in the document, it mentions "You can have automatic detection of VSCode projects"

Per my understanding, VSCode does not support creating a project, as in the official doc:
*************
Q: How do I create and run a new project?

A: VS Code doesn't include a traditional File > New Project dialog or pre-installed project templates. You'll need to add additional components and scaffolders depending on your development interests. With scaffolding tools like Yeoman and the multitude of modules available through the NPM package manager, you're sure to find appropriate templates and tools to create your projects.
*************

So, what do you mean here by saying "VSCode projects" ?  Do you mean they are just VSCode extension projects ?

**Comment by alefragnani** [comment]
Hi @wangxiexe ,

A **VSCode Project** is a folder that contains a subfolder called `.vscode`. Simple as that 😄 .

If you open any folder and use VSCode features like _tasks_, _workspace settings_, etc, it will create a subfolder called `.vscode`, to store that info. So, I decided to call it a **VSCode Project**.

It means that the autodetection will look for any folder that contains a subfolder called `.vscode`. If it finds, it will be presented in the pick list.

Hope this helps.

**Comment by wangxiexe** [comment]
Thanks for clarification, that helps.
