### ISSUE TITLE
Feature Request: Close Project

### ISSUE THREAD

**Issue by evenfrost** [alefragnani/vscode-project-manager#160]
Hey Alessandro, and thank you for awesome extension, it really fuels my workflow!

It would be great if we had `Close Project` command which would 'unload' currently opened project from VSCode, close all the editors and remove folders from Explorer panel. After closing you could add folders and for a new project for example.

I've come from Sublime Text where such command exists and I find it quite handy and useful.

**Comment by alefragnani** [comment]
Hi @evenfrost ,

Do you think this command is really necessary? I mean, you already have the `Close Folder` / `Close Workspace` commands which appears to do the exact same thing, and even shares the same keybinding (`Ctrl + K` + `F`).

Hope this helps

Hope this helps.

**Comment by evenfrost** [comment]
Yeah, you're right, just got a bit confused about similarities between workspaces and projects, This is just my subjective preference to have all in one place and call all of this just 'Projects' (like it was in Sublime), and it was like that before VSCode team implemented the concept of Workspaces.

Anyway, seems like `Close Workspace` is really right thing for that, thanks for the help!
