### ISSUE TITLE
Add project to current workspace

### ISSUE THREAD

**Issue by stu-fu** [alefragnani/vscode-project-manager#161]
I would love to have the option to have the option of adding a project from my list to the current workspace that is open, in addition to the current options of opening a project in a new or same window.

**Comment by alefragnani** [comment]
Hi @stu-fu ,

Thanks for your suggestion. Unfortunately, there is no API available yet. There are some discussions in VS Code repo about expaning the API, so we have to wait before adding something to the extension.

Take a look:

- https://github.com/Microsoft/vscode/issues/37301
- https://github.com/Microsoft/vscode/issues/35407

Hope this helps

**Comment by jordandrako** [comment]
Both those issues are closed, can we get a quick status on this? Thanks.

**Comment by alefragnani** [comment]
Hi @jordandrako ,

You are right, both has been closed, and now I can take a look on this 😄 

How do you think it should work? I mean, once you are _in some workspace_, have to option _add some of your projects to the current workspace_?
