### ISSUE TITLE
Support multiple workspace folders in a single project

### ISSUE THREAD

**Issue by vivekKodira** [alefragnani/vscode-project-manager#163]
Please add support for multi-root projects similar to https://code.visualstudio.com/docs/editor/multi-root-workspaces

**Comment by alefragnani** [comment]
Hi @vivekKodira ,

The extension already supports multi-root workspaces, since the feature has landed in VS Code stable channel. The concept that I decided to use is explained in #149 .

Hope this helps

**Comment by vivekKodira** [comment]
Thank you :)
