### ISSUE TITLE
Include Command to clear cached git/svn Projects?

### ISSUE THREAD

**Issue by halhenke** [alefragnani/vscode-project-manager#165]
I somehow added a bunch of junk to the Git Project section of my Projects - possibly because I set the `maxDepthRecursion` setting too high or because there was interaction with the [Git Project Manager](https://marketplace.visualstudio.com/items?itemName=felipecaputo.git-project-manager) plugin that I installed before I realised that Project Manger seems to have similar functionality.

At any rate I ended up with hundreds of entries in the Git section - the same repository would be repeated dozens of times. At any rate there didnt seem to be anyway to get rid of these entries - I enabled/disabled the caching setting, restarted etc. Eventually I had to set `projectManager.git.baseFolders` to an empty folder and then use the refresh command.

So not 100% sure how this happened but thought a command to enable one to forget these settings might be a worthwhile addition.

**Comment by alefragnani** [comment]
Hi @halhenke ,

Do you mean a command to clear `projectManager.XXX.baseFolders` setting? 

If you use the `Project Manager: Refresh Projects` it _shoud_ reset your Project List (clearing and recreating the cache files), and unless you had some issue with that, it should work. I remember sometime ago that _duplicate entries_ happening to me too, but I just had to `Refresh Projects`and the project list has been fixed.

Hope this helps

**Comment by halhenke** [comment]
Hey,
Yeah I am 99% certain that i did that a couple of times but when i checked for Git Projects they were still there, even though i had removed the `projectManager.XXX.baseFolders` from User settings. It was only after I added the setting back and set it to an empty directory that things refreshed.

As said though I had installed a rather similar plugin and i was actually trying to change its configuration without realising i was enabling the Git Project feature in this plugin when the whole thing started. So maybe not the easiest thing to replicate :-)

Thanks for your time 👍

**Comment by alefragnani** [comment]
I'm pretty sure you did that a couple of times, because when that happened to me, I did the same thing 😆 . Good to know it's working now 👍 

I'm trying to remember _how_ that could happen, and I was wondering if this duplicates could happen if I call `Project Manager: List Projects to Open` a couple of time, before it _shows_ the list of projects (there is nothing to avoid that). I guess this could raise this issue.

I will try to replicate this scenario. If this is the reason, I will change the way _auto-detection_ works (background).

Stay tuned

**Comment by alefragnani** [comment]
🏃

**Comment by alefragnani** [comment]
Released in 0.24.1
