### ISSUE TITLE
Save also the arrangement of terminals

### ISSUE THREAD

**Issue by frontcraft** [alefragnani/vscode-project-manager#170]
Do you think it would be possible to save in a project also the state of opened terminals?

User story:
As a user, to work on a project locally, i need to have three terminals opened. One to run the local server script from the `server` directory, second to run the client from a `client` directory and third to perform operations that i like usually to do from a command line. 

I can open three terminal sessions in VS code without a problem and create key bindings to switch between them nicely (for example to quick preview of the the output).
It would be great to restore the terminals state after opening saved project. I mean not whole session, but only amount of opened terminals and their starting locations. In iTerm these are called Arrangements. You can save there and restore terminal Arrangements. Being able to do that in VS Code automatically after opening new project would be very useful. It would make me completely resign from using the iTerm, which is currently my favorite command line manager.

**Comment by alefragnani** [comment]
Hi @frontcraft ,

I dare to say that VS Code itself already save that, with a lot of other _session-stuff_. I remember reopening sessions and the Terminal panel appear, but I don't remember if _all my Terminals_ are reopened. I guess not.

Based on this, I think the best place to ask this is on VS Code repo itself. They even have an **integrated-terminal** Label for things related to the terminal.

For instance, there is this issue https://github.com/Microsoft/vscode/issues/43557 in VS Code repo which ask for _command history_

Hope this helps

**Comment by Tyriar** [comment]
@frontcraft here's the issue you're after https://github.com/Microsoft/vscode/issues/20013

**Comment by alefragnani** [comment]
Thanks @Tyriar for pointing the right issue to track. 
@frontcraft I'm closing this in favor of the that issue.

**Comment by Tyriar** [comment]
FYI I split the layout/shell/env restore specifically out into https://github.com/Microsoft/vscode/issues/44302 and next Insiders will have a basic implementation which you can turn on using `terminal.integrated.experimentalRestore`. Any feedback on how it works would be great 😃
