### ISSUE TITLE
Refresh Projects doesn't work

### ISSUE THREAD

**Issue by aliusmiles** [alefragnani/vscode-project-manager#172]
Refresh Projects command doesn't work for git/vscode projects on: MacOS 10.13.3, VSCode 1.20.1, Project Manager 0.24.0.

How to reproduce:
- Delete/add git repo
- Run `Refresh Projects` command
- Added project is not showing in list, deleted project shows with `Path does not exists`.

I've also tried to delete `projects_cache_git.json` file and run refresh, still showing the old list. Refresh seems to work only after restarting VSCode. I've also noticed that sometimes creation date on cache file changes, but it's content and md5 hash stays the same.

**Comment by tomaxsas** [comment]
Can confirm. refresh does not work. Even restart of vs code does not help. Only thing helps is changing some setting of the plugin. After that projects are refreshed correctly. This issue is for few months for me.

**Comment by jrrdnx** [comment]
Not working for me as well.

With the "cacheProjectsBetweenSessions" setting set to false, the project list is constantly updated but takes several seconds to search through folders. Set to true, refreshing projects and restarting VS Code doesn't work, but only changing one of the other settings and saving (for me, I toggle the "maxDepthRecursion" setting back and forth between 3 and 4).

**Comment by alefragnani** [comment]
Hi,

There are other two (#157 and #165) issues related to the `Refresh` command and the _caches_. These are on my priorities, but right now I have other projects to look first. 

It will take couple of weeks before I look at this, but the intention is to fix all those issues at once.

Thanks

**Comment by alefragnani** [comment]
🏃
