### ISSUE TITLE
Silent failure with VSCode Portable

### ISSUE THREAD

**Issue by NathanMH** [alefragnani/vscode-project-manager#177]
### Expected Behaviour
Projects saved

### Actual Behaviour
When saving, project manager suggests a name, and 'saves' project. If I try to save again, it pops up 'project already exists!'. But trying to list or edit projects reveals items with
- Project Name Root Path
- Path does not exist

Using the update project button provided results in a 'No projects saved' popup. 
Choosing 'Yes, edit manually' seemingly does nothing.

### Further Information
Using VSCode Portable 1.22.1
Other extensions include Vim, Shell launcher, Org Mode.

**Comment by NathanMH** [comment]
I don't know why I didn't think to change the default project location... That completely solves the issue.
Thank you for the quick response.
Again, sorry for bothering you! And thank you for the excellent extension.

**Comment by alefragnani** [comment]
Don't need to be sorry 😄 . 

I'm glad it worked. I hope you enjoy using the extension.
