### ISSUE TITLE
Selecting a saved project does not open

### ISSUE THREAD

**Issue by stephenlautier** [alefragnani/vscode-project-manager#18]
Hi

I have been trying this plugin quite a bit however when I select a project from the list which I had saved 99% of the time nothing happens. There were times that it worked however generally it doesn't work for me.

I'm using Windows 10 (also Windows 7 at work) and both same issue.
I should have latest as of today of for this plugin and latest VS Code 0.10.11

**Comment by stephenlautier** [comment]
My bad i failed to read the doc which you provided 

> // For Windows, use:
    "projectManager.codePath": "C:\\Program Files\\Microsoft VS Code\\Bin\\Code.cmd"

Sorry

**Comment by alefragnani** [comment]
No problem :+1:
