### ISSUE TITLE
Move the TreeView to use the new "Activity Bar" API

### ISSUE THREAD

**Issue by alefragnani** [alefragnani/vscode-project-manager#183]
April 2018 (version 1.23)

**Comment by alefragnani** [comment]
🏃 

![image](https://user-images.githubusercontent.com/3781424/40458536-c9d2a0de-5ed2-11e8-904d-121730b04ba4.png)

**Comment by alefragnani** [comment]
## Activity Bar

- [ ] Open
- [ ] Open in New Window 
- [ ] Add to Current Workspace
- [ ] Delete/Rename (Favorites)

## Explorer

- [ ] Save Project
​

**Comment by imoby** [comment]
is there a way to disable this?

**Comment by alefragnani** [comment]
It was answered in #196 😄
