### ISSUE TITLE
Set custom name for auto-detected projects

### ISSUE THREAD

**Issue by cdCorey** [alefragnani/vscode-project-manager#184]
Since I work primarily on WordPress projects, the current auto-detect projects feature is useless to me. Nearly every Git repo exists in a folder called "wp-content" – which means the auto-detect projects feature returns a long list of identical "wp-content" projects, and there's no way to make it show the path or otherwise to tell them apart. I have a few thoughts on features that could help with this:

1. Show a tooltip on mouseover with the path to a project.
2. When generating projects from folder names, compare the names and if they match, include parts of the parent path as necessary to make each name unique. (E.G., if two projects are found named "wp-content," step up the tree to rename one "fubar/wp-content" and the other "snafu/wp-content."
3. Add an option to the right-click menu to rename the project. In practice, I don't want "wp-content" in there at all, I want the projects named "Fubar" and "Snafu." Obviously I can't expect the plugin to be smart enough to just figure out what I want, but I should be able to set the name myself.

In a perfect world all three of these would be implemented, but if either #2 or #3 could be implemented, that would at least provide a minimal viable solution.

**Comment by alefragnani** [comment]
Hi @cdCorey ,

I'm sorry to hear that. I have a few _same-name projects_ in my folders and it never bothered me. I remember a similar request has been made a year ago (#99) but in the end the user ended up changing its setup, and closed the issue.

For (1), I assume you are talking about the `Treeview` panel. Unfortunately, there is no API available fro add `tooltip`

For (3) you may try to use the `Save Project` command. Doing so, you will be able to define a name for the project, and with `"projectManager.groupList": true` setting defined, it will be presented at the top in the list.

For (2), your suggestion matches the same _personal preference_ from #99

If `Save Projects` command is not enough for you, I could let open the idea for (2).

What do you think about it?

**Comment by cdCorey** [comment]
Thanks for getting back to me.

How do you tell your same-name projects apart? Is there something I'm
missing? I can see how it wouldn't be a big deal if it's only a couple –
worst case scenario, you click the wrong one then just click the other one
– but in my case, I have around 50 projects, and the vast majority of them
show up with the same name. I guess that might sound like an extreme
scenario to some people, but I do WordPress client work that includes
on-going maintenance, and I think this scenario is probably not uncommon in
my line of work.

I ended up going through and adding my current most active projects into
the projects.json manually, and I guess I'll just have to add my other
projects as they come up. To be honest, I guess I would have expected
auto-detection to just add the detected projects into the projects.json so
I could customize name, etc., however I need to, but that doesn't really
seem to be how it works. I guess I'm a bit spoiled when it comes to my
project management expectations; I'm coming from Coda, which is a
relatively lightweight IDE that is very much oriented around projects, but
it's a bit buggy and its editor isn't as robust as VS Code. VS Code doesn't
really seem to have much of a concept of projects at all since its just an
editor out of the box, but it has a robust enough plugin ecosystem that I
keep hoping I can put together something close to the IDE experience I'm
used to. It's possible that may simply not be a reasonable expectation.

Anyway, I guess your explanation of how to use Save Project should
accomplish essentially the same thing I was asking for in (3), so I'll try
that. I do still think (2) would be helpful, though, since it would mean I
could tell my projects apart without having to manually go through and save
all 50 of them individually. But if I'm only the second person to bring up
this issue, I guess you'll have to decide whether you think there's enough
demand to justify the effort. I would offer to try to put together a PR,
but I haven't done any development for VS Code yet, so I don't really know
how I would even go about doing that.

Thanks for your assistance.

--
Corey Caswick
Chatman Design
chatmandesign.com <http://www.chatmandesign.com>

**Comment by alefragnani** [comment]
Hi @cdCorey 

> How do you tell your same-name projects apart? Is there something I'm missing?

When I have _same-name_ projects listed, I just read it's path at its side. Since they are, in most cases, at different base locations, I can easily detect which one I wan to use.

> To be honest, I guess I would have expected auto-detection to just add the detected projects into the projects.json so I could customize name, etc.,

These are two different concepts. Your favorite projects are those that _you intentionally saved because you think they are important_. The auto-detected, on the other hand, are those that _you just want to be available inside VS Code_.

As I said, I can let this issue open for idea (2). Being the second user to bring up this is not a problem at all, since I already added features (even more complex than this one) that only one user has requested. It depends on prioritize 😀 .

**Comment by alefragnani** [comment]
Turns out that it's possible to have `hint / tooltip` for `TreeView` in recent APIs 😄 . 

Take a look at #183 screenshot

**Comment by cdCorey** [comment]
It would probably be helpful. As you recommended previously, I just started adding projects manually. It would be nice to not have to do that, but I've gotten used to it.

**Comment by alefragnani** [comment]
I'm closing this feature request because it didn’t receive enough upvotes from the community. Still a big Thank You to you for taking the time to create this issue!

Thanks for your understanding
