### ISSUE TITLE
Open in current window if empty

### ISSUE THREAD

**Issue by albireox** [alefragnani/vscode-project-manager#188]
One thing I like about how the Atom project manager works is that it will normally open new projects into a new window. But if the current window is empty (that is, there is no directory or file open, only and untouched Untitled file), it would replace the window with the project. Would it be possible to have this as an option?

**Comment by alefragnani** [comment]
Hi @albireox ,

I think that it's a good idea. Thanks for your suggestion 👍

**Comment by TheSeally** [comment]
@alefragnani is it still relevant issue? Can I try to do this?

**Comment by alefragnani** [comment]
It appears it depends on https://github.com/microsoft/vscode/issues/15178, to know if _there is any_ file/folder/workspace opened.

From Slack https://vscode-dev-community.slack.com/archives/C74CB59NE/p1574037925370200:

> checking vscode.workspace.workspaceFolders returns undefined if I don't have a Folder or a Workspace (multi-root folder) opened, which is fine. But if I have random files opened (no folder related) it will return undefined as well :cry:. I tried to use vscode.workspace.textDocuments (which is described as All text documents currently known to the system.), but even with no opened file, it can return 1, because of the Welcome Page..
