### ISSUE TITLE
Do not search for git projects inside git projects

### ISSUE THREAD

**Issue by mikeroll** [alefragnani/vscode-project-manager#189]
When using automatic project search (via `projectManager.git.baseFolders`), in case of complex git repositories, like the ones with nested repos or/and submodules, I find it rather confusing to have both the outer ("main") repo and inner sub-repos listed as separate projects.
My suggestion is to stop looking for nested git projects once a valid top-level one has been found, or introduce a setting to let the user control this behaviour.
Perhaps this is also relevant to other VCSs.

**Comment by alefragnani** [comment]
Hi @mikeroll ,

It really can't stop search in subfolders, for reasons like #134, so a setting is good alternative for your scenario.

Thanks for your suggestion.
