### ISSUE TITLE
VS Code 0.10.12 - OSX - Project switching doesn't work

### ISSUE THREAD

**Issue by jamespacileo** [alefragnani/vscode-project-manager#19]
Sorry to raise this, but it doesn't seem to be functioning on
OSX with VS Code 0.10.12.

Procedure used:
F1 -> Project Manager : List Projects -> click on wanted project

I'd be happy to debug and help, but I'm not sure how.

Thanks

**Comment by alefragnani** [comment]
Hi @jamespacileo , you don't have to be sorry :smile: 

Did you follow the instruction in the readme? Did you installed the **VSCode Shell Commands**? After that, you only need to define the `path`, like below:

```json
    // - For Code Stable Build, use this:
    "projectManager.codePath": "code"

    // - For Code Insider Build, use this:
    "projectManager.codePath": "code-insiders"
```

Hope this helps

**Comment by jamespacileo** [comment]
Grazie Alessandro! Buona Pasqua! :+1: 

I was missing those steps, thanks! Any chance you could consider displaying a warning/error as a feature?

Thanks again1 :smile:

**Comment by alefragnani** [comment]
Prego! Buona Pasqua :smile: 

I agree, it's a good idea to display a warning message if this setting is empty. At least for Mac OS X, because it appears to be _required_ :disappointed: I will take a look how this could be accomplished.

Thanks for your suggestion :+1:
