### ISSUE TITLE
Open project in new window if shift/alt/ctrl/cmd (pick one) click on status bar

### ISSUE THREAD

**Issue by alexrussell** [alefragnani/vscode-project-manager#190]
Right now we can choose whether the status bar list will open the chosen project in the same window or a new window, but it'd be good if we could [modifier]+click on the status bar text to make it do the inverse of whatever the setting is.

i.e. if I have it set so that status bar click opens in the same window, [modifier]+click is a new window. If settings having status bar in a new window, [modifier]+click would be same window.

I'm not overly fussed about which modifier we use. Shift probably makes the most sense as it is used in other apps (notably web browsers) to open a new window from a lick (or address bar typing with shift+enter), but it doesn't matter all that much. Maybe make it configurable, or work with any combination of modifiers (at least one of shift, alt, ctrl, cmd/super pressed).

**Comment by alefragnani** [comment]
Hi @alexrussell,

Thanks for your suggestion, but I think that it will be _on hold_ for the same reason as #76, a _missing API_. 

Today, there is no way to handle _Alt keys_ when you click on Status Bar, so I'm not able to check whether you `Clicked` or `Ctrl + Clicked` the item. I can open an issue in VS Code repo, but I don't think it will be released soon.

Hope this helps.

**Comment by alexrussell** [comment]
Ahh sorry I didn't see that issue - I was searching for "status bar" rather than "new window" when I searched for a preexisting issue.

Here's hoping that VSCode can add the handling of modifier keys on the various VSCode-controlled UI bit, then!

**Comment by alexrussell** [comment]
For tracking, I have opened a vscode issue at Microsoft/vscode#51073

**Comment by alefragnani** [comment]
I'm closing this issue because the VS Code issue that it depends on has no update from VS Code team members for more than an year. It's not even planned on any Milestone so, it does not appear to be on their roadmap

I've subscribed to the issue, so if/when it is released, I'll be notified, and could reopen/reactive this one

Hope this helps
