### ISSUE TITLE
Trying to save a project when no folder is open gives confusing message

### ISSUE THREAD

**Issue by nicktimko** [alefragnani/vscode-project-manager#191]
I lazily did a `code` in a folder that I didn't have saved maybe thinking it'd be like `code .` then when trying to quickly save that project, I got the confusing error

> Running the contributed command:'projectManager.saveProject' failed.

# Steps to reproduce

1. Open a VSCode window with no folders open
2. Open control palette and try to "Save Project"
3. VSCode emits warning

# Expected behavior

Warn the user "Hey idiot, you don't have a folder open" or something more friendly. The VSCode warning started making me check if things were up to date...

# Details
* VSCode 1.23.1
* Ubuntu 16.04
* VSPM: 0.25.2

**Comment by alefragnani** [comment]
Hi @nicktimko ,

> Warn the user "Hey idiot, you don't have a folder open" or something more friendly. The VSCode warning started making me check if things were up to date...

I'm going for the _friendly_ message 😆 .

Thanks for reporting

**Comment by BlueTalon6** [comment]
It looks like this check and prompt has been removed in a later version? 
Had some code open and tried to save a project with 12.7, without having a folder open and got "Error running command projectManager.saveProject.. _something about property of undefined_". 
Updated VSC to 1.77.3 and now there's no prompt or error.

**Comment by alefragnani** [comment]
Hi @BlueTalon6 ,

I could reproduce the issue. Really weird this is not working anymore, as the source responsible for it is not changed for a while.

This should be fixed in the next release

Thanks for reporting.
