### ISSUE TITLE
Add more info when open project explorer with Cmd+Ctrl+P

### ISSUE THREAD

**Issue by muuvmuuv** [alefragnani/vscode-project-manager#194]
When I open the project explorer with the above command I just get a list with the name and path. It would be nice to see the group too and some additional settings like: 

- Description: a detailed information about the project
- Image: a tiny favicon (absolute path)
- Git Info: some info from the repo like: authors, changes counter, the current branch

**Comment by alefragnani** [comment]
Hi @muuvmuuv ,

The list API is limited to 3 different _areas_ to display info. Today it already uses all 3. Two of them are _important_ but the last one, is not, and I'm already thinking about removing it.

* Project Name: At left, with a bigger font size (and also an octicon to represent VSCode, Git, Mercurial and SVN repositories)
* Project Path: At right, with a smaller font size
* _Path not found_ hint: Second line

 How to you think all this suggested info should be presented? Do you have any mockup/print to suggest?

**Comment by muuvmuuv** [comment]
Oh it is no package, I created this in sketch yesterday to show you how I would like to have it 😄 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by muuvmuuv** [comment]
Is it possible to create a by its own popup for project manager? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alefragnani** [comment]
I was just saying that, if _this_ (my extension) was an Atom package, your design could be used. I wasn't asking if that mockup was a package 😄 ..

The reason for my comment is that Atom is _more hackable_ and you can create visual elements (like your design) by your own. In VS Code, in other hand, you just have the visual elements that its API provides. And in this case, the list is limited to the visual that I commented.

I remember that there are some reported issues in VS Code repository to _expand_ that element, but none was so different. I guess that it won't be possible to have so much information in that list/popup. For instance, I have three issues related to it, and none is even _planned_ yet:

* https://github.com/Microsoft/vscode/issues/11468
* https://github.com/Microsoft/vscode/issues/11483
* https://github.com/Microsoft/vscode/issues/16445

Hope this helps

**Comment by alefragnani** [comment]
Last week I decided to "re-focus" on some of my extensions, and I'll start to plan milestones for each of them. This "re-focus" will be based on community feedback/support.

I'm closing this issue because two of the VS Code issues that it depends on, has no update from VS Code team members for more than two years. It's neither planned on any Milestone, so, it does not appear to be released soon.

I'm subscribed to both issues, so if/when it is closed, I'll be notified.

Thank you for your understanding.

**Comment by akivagold** [comment]
Hi, sorry for reviving this. Is there an option to add a git branch to the project search? It will really help navigate between projects from different worktrees.
