### ISSUE TITLE
Somehow dependent of network connection

### ISSUE THREAD

**Issue by djiest** [alefragnani/vscode-project-manager#195]
It seems the extension is somehow depending on a network connection. I have al my projects local, but when connected with VPN to a customer location, the extension does not load my saved projects

**Comment by alefragnani** [comment]
Hi @djiest ,

The extension is not _dependend_ of network connection. unless you define some of its settings with resources that depends on network connection. For instance, if you define `projectManager.projectsLocation` or `projectManager.???.baseFolders`, it will need to use that connection. 

Please, add some more details, so I could try to understand what is going on:

* Do you see any error/warning reported in `Developer Tools / Console`? 
* How is the extension configured?

Hope this helps

**Comment by djiest** [comment]
Hi @alefragnani 

You're correct that I have a project in the list that depends on a network connection. I will disable that project and see how this affects the performance.

Thanks,
Djiest

**Comment by alefragnani** [comment]
Hi @djiest ,

Any news about your test?

**Comment by djiest** [comment]
Hi @alefragnani 

I can confirm it had to do with a project that pointed to a network device.

Thanks for thinking along.

Regards
Joost
