### ISSUE TITLE
Add new "Save current folder as Project" button in Activity Bar (Favorites Panel)

### ISSUE THREAD

**Issue by Tenrys** [alefragnani/vscode-project-manager#197]
I just found out the icon for this extension doesn't show in the Activity Bar until you have at least one project saved. I think it should display at any point in time, and let you add the current workspace as project with a button located at the same place as the `Edit Projects` button, or in the context menu if you click empty space in the projects list.

**Comment by alefragnani** [comment]
Hi @Tenrys ,

Personally, I would let this _always visible_, but by VS Code design, the Activity Bar should be hidden only if none of its views has contents. I ended up following this guidelines. Even doing that, issues like #196 were filled. By now, it will stay as is, but I'll keep looking for this 👍 

I also liked your idea about the `Add Current Folder/Workspace` button. Really handy.

Thanks for your ideas

**Comment by alefragnani** [comment]
With the release of v**10.3.0** the Side Bar icon is now visible by default (#227) , even with no project saved. In this case, a message is added to the panel and a Context Menu item to `Save your First Project` is available.

I think #227 now also closes this issue.
