### ISSUE TITLE
Add update button to the side bar view

### ISSUE THREAD

**Issue by kankaristo** [alefragnani/vscode-project-manager#200]
It would be nice to have an update button in the side bar view ("Project Manager: Git"), which would essentially run `projectManager.refreshProjects`.

Similar to the update button in "Bookmarks Explorer":
![screenshot from 2018-07-19 00-28-48](https://user-images.githubusercontent.com/3522333/42908901-dde32a6e-8aea-11e8-949f-03c60c6a580e.png)

**Comment by alefragnani** [comment]
Hi @kankaristo ,

That's a good idea. Thanks for your suggestion 👍

**Comment by alefragnani** [comment]
Closed with PR https://github.com/alefragnani/vscode-project-manager/pull/231
