### ISSUE TITLE
Stop working after update to vscode 1.25.1

### ISSUE THREAD

**Issue by UsulPro** [alefragnani/vscode-project-manager#203]
First of all thanks for this extension, it's one of my favorites for vscode :+1: 

After I update vscode to 1.25.1 it always hangs when I trying to open the projects tab:

![image](https://user-images.githubusercontent.com/14885189/43039813-85e657c8-8d3d-11e8-8cde-2af20677176e.png)

and after that nothing happens for a long time

Save me, I forgot how to open folders via the file menu :smile:

**Comment by UsulPro** [comment]
solved after reinstalling this extension

**Comment by alefragnani** [comment]
Hi @UsulPro ,

Good to know it fixed simply reinstalling the extension. That's weird, I have to admit, but it seems that the extension updating process has some issues, because from time to time, I see this kind of report, and not only on my extensions.

Let me know if you find anything else...
