### ISSUE TITLE
VS Code / Ubuntu freezes when a project doesn't exists

### ISSUE THREAD

**Issue by thiagobraga** [alefragnani/vscode-project-manager#207]
When I click on a project that does not exist, VS Code shows the corresponding warning, but gets stuck in the message, and Ubuntu becomes irresponsible. The screen gets freeze.

Sorry for the lack of information. I don't know how to get a screenshot this way. Maybe some logs, but I don't know what logs would be useful.

**Comment by alefragnani** [comment]
Hi @thiagobraga ,

What do you mean about _corresponding message_? When you select a project to open with the extension, I just use a _native_ VS Code command, so it would work/not work, just like VS Code does. 

What happens if you try to use the `Open Recent` native VS Code command, selecting a project/folder that does not exists. Does it freezes VS Code as well?. Also, what happens if you try to open a missing project from the command line?


Hope thi helps

**Comment by thiagobraga** [comment]
Hi @alefragnani,

> What do you mean about corresponding message?

Maybe I have not been very clear. But I was referring to the dialog box that appears when you click on a project that does not exist. See the screenshot:

![project manager - bug on dialog box](https://user-images.githubusercontent.com/993684/45254086-1ff57f80-b348-11e8-959f-33efe0eed713.png)

At the left side, I've run the command `tail -f /var/log/syslog`. The message is:

```
ubuntu code[31275]: GtkDialog mapped without a transient parent. This is discouraged.
```

After testing a few times, I realized that Ubuntu does not freeze. This can be noticed because the system clock does not freeze. But the mouse gets stuck, impossible to click on anything. After a while, I realized that by pressing Enter, the dialog box closed and everything returned to normal.

> What happens if you try to use the Open Recent native VS Code command, selecting a project/folder that does not exists. Does it freezes VS Code as well?

Yes. Maybe it is a VS Code bug on Ubuntu. I've created a test folder, opened this folder from command line, closed the Workspace in VS Code and moved the folder. When I `Open Recent...` this folder, the same bug occurs:

![project manager - moving folder for testing purposes](https://user-images.githubusercontent.com/993684/45254217-0e61a700-b34b-11e8-87c9-8b3904a4acd3.png)

![project manager - moving folder bug freezes screen](https://user-images.githubusercontent.com/993684/45254227-35b87400-b34b-11e8-89fa-611fde240f10.png)

> Also, what happens if you try to open a missing project from the command line?

In this case, VS Code interprets this request as a new file in a new folder. It does not freeze as in other cases.

**Comment by alefragnani** [comment]
Hi @thiagobraga ,

Well, as you could detect yourself, this seems to be a VS Code issue, not in the extension. I suggest you to report directly in VS Code repository. 

If I remember correctly, some of the VS Code team members uses Linux fulltime, which could make it easier to them to detect/replicate the issue, and priorize its fix.

Hope this helps

Depois relaciona o item cadastrado aqui 😁
