### ISSUE TITLE
Project Settings

### ISSUE THREAD

**Issue by juanrgon** [alefragnani/vscode-project-manager#208]
I think this has been brought up multiple times before and has for some reason been ignored each time, but I would really like VSCode to include project settings in addition to workspace settings.

Our team wants to share a project settings file in our git repo, that a user could override with their local settings file. The idea would be workspace settings override project settings which override user settings which override default settings. 

This is essentially what Sublime Text does: https://www.sublimetext.com/docs/3/projects.html.

**Comment by alefragnani** [comment]
Hi @juanrgon ,

I think you are referring to VS Code itself, not this extension. This extension does not store/manage settings, but only the project locations itself, giving you shortcuts to access them.

If I remember correctly, VS Code has made some updates related to user/project settings in recent released, specially after releasing multi-root workspaces. Here are two references to VS Code docs that you may find helpful. https://code.visualstudio.com/docs/getstarted/settings and https://code.visualstudio.com/docs/editor/multi-root-workspaces.

Hope this helps
