### ISSUE TITLE
Add Shortcut: Reveal Project in OS (Finder)

### ISSUE THREAD

**Issue by wottpal** [alefragnani/vscode-project-manager#214]
Hey is it currently possible to set up a shortcut which opens the currently active projects base folder in  Finder (or other OS explorer).

VSCode has inbuilt functionality for files, it is named `revealFileInOS`

Thanks!

**Comment by alefragnani** [comment]
Hi @wottpal ,

That's an interesting idea, but I think it should be presented in VSCode itself. Looking at VSCode repository, I fount [this issue - 40138](https://github.com/Microsoft/vscode/issues/40138), so I suggest you to _upvote_, making it more visible to VSCode team.

Hope this helps
