### ISSUE TITLE
VS Code open window with projects on startup

### ISSUE THREAD

**Issue by muuvmuuv** [alefragnani/vscode-project-manager#218]
Some IDE's like PhpStorm, have a popup window coming on startup that shows saved projects. It would be nice to have this in VS Code, even this would make it closer to a full IDE.

Here an example:

<img width="777" alt="project-management-pane" src="https://user-images.githubusercontent.com/11534760/45471104-53f9e780-b730-11e8-81e8-a018fa9a2fce.png">

I think that also depends on the VS Code API.. sad that it is not that hackable. They should give their users a bit more flexibility.

**Comment by alefragnani** [comment]
Hi @muuvmuuv ,

Today, the **Welcome page** already shows the recent projects/folders/workspaces, but yes, it has no connection with the projects from **Project Manager** extension, or any API to connect to it. I found [this issue](https://github.com/Microsoft/vscode/issues/38778) which ask similar thing, so I think that an upvote would be good.

Hope this helps

**Comment by alefragnani** [comment]
Depends on https://github.com/Microsoft/vscode/issues/38778

**Comment by alefragnani** [comment]
Hi @muuvmuuv ,

I'm closing this issue because the VS Code has closed (yesterday) the issue that it depends on. So, unfortunately, there is no way to accomplish what you were asking, sorry.

Thank you for your understanding.

**Comment by LeoJhonSong** [comment]
Hi, thanks for the powerful extension! It seems now there are extensions able to create a custom welcome page when opening a vscode new window ([Welcome Recent Projects](https://marketplace.visualstudio.com/items?itemName=LeandroStasi.welcome-recent-projects), [Big Welcome](https://marketplace.visualstudio.com/items?itemName=Arman.big-welcome)). Would there be a chance we can have a welcome page for project manager too?
