### ISSUE TITLE
Project mananger icon

### ISSUE THREAD

**Issue by JTRipper12** [alefragnani/vscode-project-manager#220]
I have installed / reinstalled several times but the Icon appears for a split second in the activity bar then goes away. 
![capture](https://user-images.githubusercontent.com/16598836/45509862-33f61280-b788-11e8-94f0-526e6fa24eb7.PNG)

**Comment by garzasays** [comment]
Having the same issue. I have tried to install this on Windows 10 and on Mac with no luck. As a last resort I tried downloading this from the marketplace and install as .vsix. No luck there either. Nothing errors in the console to share. Let me know any additional info you may need. Thanks

**Comment by alefragnani** [comment]
Hi @JTRipper12 @garzasays ,

The icon will appear if you have at least one project listed, either by using the `Project Manager: Save Project` command or using the auto-detected projects (Git, SVN, Mercurial, VSCode). 

Have you saved/configured any project to be visible?

Hope this helps

**Comment by garzasays** [comment]
Doh. My mistake. I was looking for the icon or something in the File menu. Didn't even bother to check the command palette.  My mistake. Thanks for the quick reply. Thanks for the extension, now that I have it working it's great.

**Comment by alefragnani** [comment]
Hi @JTRipper12 , did it work for you too?

**Comment by JTRipper12** [comment]
@alefragnani it did thanks!

**Comment by connorshea** [comment]
I just ran into this when installing VS Code Insiders and went on a wild goose chase trying to figure out what was causing the problem. I feel like this UX isn't very obvious to users.

IMO the icon should always be in the sidebar, the view that opens when there are no projects can just say something like "No projects found. Add one with the Command Palette to get started."

**Comment by alefragnani** [comment]
Hi @connorshea ,

That's a great idea. I filled #227 to track it 👍
