### ISSUE TITLE
Ubuntu freeze when switching project

### ISSUE THREAD

**Issue by BartKeulen** [alefragnani/vscode-project-manager#223]
**Problem:**
When I have an *unsaved* workspace open and want to switch to a different project using the project manager extension Ubuntu freezes. Here is a [screenshot](https://imgur.com/a/8ryiSxy) of the state it freezes.

**Setup:**
- Ubuntu 18.04.1
- VS Code 1.27.2
- Project manager 9.01

**Steps to reproduce:**
- Open a folder in VS Code
- Save as a 'project manager' project
- Add another folder to workspace
- Switch to different project using 'project manager'

**Comment by alefragnani** [comment]
Hi @BartKeulen ,

Isn't that the same issue as #207? On that issue, the user noted that Ubunto wasn't freezing, but _the mouse gets stuck_..

> After testing a few times, I realized that Ubuntu does not freeze. This can be noticed because the system clock does not freeze. But the mouse gets stuck, impossible to click on anything. After a while, I realized that by pressing Enter, the dialog box closed and everything returned to normal.

Hope this helps

**Comment by BartKeulen** [comment]
Hi @alefragnani,

It is indeed the case that *the mouse gets stuck* and not Ubuntu that freezes. The problem can be solved using the keyboard as in #207. I am not sure if this is bug in VS code or in the extension. Hopefully my issue is of any help.

Thanks!

**Comment by alefragnani** [comment]
Hi @BartKeulen ,

That's indeed a VS Code, so you should report directly in VS Code repository. The user that reported #207 didn't comment which was the issue that he created (if any), so I suggest you to look at VS Code repository for more info. 

I'm not a Linux user, but I'll try to find some additional info in Gitter and Slack channels (if I remember correctly, some of the VS Code developers does uses Linux). I'll comment here if I find something.

Hope this helps

**Comment by alefragnani** [comment]
I think https://github.com/Microsoft/vscode/issues/52778 and https://github.com/Microsoft/vscode/issues/57019 are related to this.

I suggest you to upvote/comment there too.
