### ISSUE TITLE
Wrong example path / no error message

### ISSUE THREAD

**Issue by kuechlerm** [alefragnani/vscode-project-manager#23]
Your example configuratation uses 
`C:\\Program Files\\ ...`

Maybe it is just me, but VS Code and VS Code Insiders are installed @ `C:\\Program Files (x86)\\...`
Nothing serious, but without an error message I was quite puzzled for some minutes.

p.s. love this extention! Thanks a lot.

**Comment by alefragnani** [comment]
That's because I'm using a **32 bits** Windows install :smile:

Maybe it's better to use `$PROGRAM_FILES` tag, so it will be independent. Better yet when **VS Code** becomes 64 bits.

Thanks :+1:

**Comment by johnemau** [comment]
This got me as well.
