### ISSUE TITLE
Project manager installed but not working

### ISSUE THREAD

**Issue by codeshark1** [alefragnani/vscode-project-manager#232]
How do I get it to work? It's not available neither in the activity bat, nor via command prompt
<img>https://i.imgur.com/rnPe6t0.png</img>

**Comment by kferrone** [comment]
I had to first save a project with `Project Manager: Save Project` command. Then fully turn off VSCode. Then turned it back on and it appeared and everything worked. Seems to not load right if the little projects.json file it makes isn't available yet. Saving a project creates it.

**Comment by alefragnani** [comment]
Hi @codeshark1 ,

As @kferrone , you have to save a project first, in order to view the Activity Bar icon. 

This has already been reported in #220, and will be fixed/updated in #227.

Hope this helps.

**Comment by alefragnani** [comment]
Hi @happycoder97 ,

I'm going to change how this Side Bar works in #227, making _always visible_ by default. 👍

**Comment by Arithmetics** [comment]
this worked for me. thanks. great extension
