### ISSUE TITLE
Hide Globs/Paths from Open-Dialog on per project basis

### ISSUE THREAD

**Issue by wottpal** [alefragnani/vscode-project-manager#235]
Hey there,
I recently switched from Atom and in the project manager I've used there I was able to exclude custom globs (e.g. `dataset/**/*.jpg`) from being listed in the _Go To File_ dialog. Is this possible here, too?

Thanks in advance!

**Comment by alefragnani** [comment]
Hi @wottpal ,

Unfortunately no. This extension is intented (today) only for switching between projects, not to manage how they work (it's settings). In fact, I didn't know the Atom extension do that. 

Are you talking about the  `settings` setting (https://github.com/danielbrodin/atom-project-manager#project-settings) ? 

Hope this helps

**Comment by wottpal** [comment]
Thanks for answering so quickly!

> Unfortunately no. This extension is intented (today) only for switching between projects, not to manage how they work (it's settings). In fact, I didn't know the Atom extension do that.

This is so sad and kind of a vscode dealbreaker for me 😕

> Are you talking about the settings setting (https://github.com/danielbrodin/atom-project-manager#project-settings) ?

Yes exactly, you could use it like:

```
    settings:
      "fuzzy-finder.ignoredNames": [
        "assets/**/*"
        "node_modules/**/*"
      ]
```

**Comment by alefragnani** [comment]
Well, VS Code itself already have a _Project Settings_ concept, which is stored in `.vscode\settings.json` file, inside the project folder. Wouldn't that be a reasonable alternative for you? You can add this file to your VCS repo and anywhere you go, it will always use the same setting.

Unless you want to _override_ this, with your own settings?

**Comment by wottpal** [comment]
🤯 I didn't know about `.vscode\settings.json` files yet as I'm still a VSCode newbie. They solve my exact problem, thank you very much!
