### ISSUE TITLE
Does not work if started from `code.exe`

### ISSUE THREAD

**Issue by unional** [alefragnani/vscode-project-manager#24]
If I open Code using Window Shortcut (i.e. task icon or start menu icon), it runs `code.exe` and in that case, when I try to open project, it does not work.

If I start Code from command line, then it works.

Don't know if it is related to this:
https://github.com/Microsoft/vscode/issues/5064

**Comment by alefragnani** [comment]
Hi, 

You have to  configure `projectManager.codePath` setting, as defined in **readme.md**. 
I noted this behavior right at the beginning, but hadn't find a reason for that. In fact there are other differences when you start Code from the icons, like _Environment Variables_ (only _system_ are recognized). Maybe the issue you listed is the reason.

There will be a proper API in Code for that in the future https://github.com/Microsoft/vscode/issues/58, so I will be able to replace my `exec` codes for that, and that setting will not be needed anymore :smile: 

Hope this helps

**Comment by unional** [comment]
I see. Thanks. Maybe pointing that out in the readme would be helpful. :tulip: 
I didn't realize that is the cause for this because it has been working for me (spawning `code` form cli)
