### ISSUE TITLE
[Enhancement] Autodetect type when setting "any" baseFolder

### ISSUE THREAD

**Issue by totkeks** [alefragnani/vscode-project-manager#240]
I was just setting up project manager and wanted it to use my projects folder as base folder for all different kinds, so I set this:
```
"projectManager.any.baseFolders": [
		"$home\\Projects"
	],
```

Unfortunately what this does is displaying me three folders there in the side bar, "Projects", "Subfolder 1", "Repository Folder".

When switching to this config setting, it only shows the repository:
```
"projectManager.git.baseFolders": [
		"$home\\Projects"
	],
```

Would it be possible to auto-detect the type of project, when using the "any.baseFolders" setting?

**Comment by alefragnani** [comment]
Hi @totkeks ,

Unfortunately no. The idea behind the _kinds_ of project is to have specific settings for each one of them, allowing you to individually define each one. The _any_, on the other hand, is not attached to any kind of repository. It's like a _folder explorer_.

Hope this helps.
