### ISSUE TITLE
The project list in Activity Bar is not case-insensitive

### ISSUE THREAD

**Issue by jacobweber** [alefragnani/vscode-project-manager#243]
On Mac OS X, when you click the Project Manager icon in the Activity Bar, the resulting list is sorted with uppercase letters before lowercase (e.g. Apple, Carrot, banana).

Would it be possible to add a configuration to ignore case when sorting (e.g. Apple, banana, Carrot)? For me it's easier to find things without thinking about their case.

**Comment by alefragnani** [comment]
Hi @jacobweber ,

Wow, what a catch! 👍 

The extension _is_ case insensitive by design (and simplicity), so no configuration needs t be added, but instead, the Activity Bar must be fixed. 

Thanks for reporting

**Comment by jacobweber** [comment]
Looks like there are some other settings, like "Group List" and "Sort List", that aren't applied to the list in the Activity Bar.

**Comment by alefragnani** [comment]
Yes, but those are intentional 😁
