### ISSUE TITLE
Project manager not showing up in side bar

### ISSUE THREAD

**Issue by ttfreeman** [alefragnani/vscode-project-manager#245]
The project manager is not showing up in the side bar (or activity bar) for me.

**Comment by alefragnani** [comment]
Hi @ttfreeman ,

Are you facing  #220 or  #196. If yes, then it will be changed in #227 .

Hope this helps

**Comment by pythoninja** [comment]
It doesn't show for me too. Just reinstalled extensions.

I am on VSCode 1.30.1 and Project Manager 10.1.0.

![image](https://user-images.githubusercontent.com/13417093/50376118-d2accd80-0619-11e9-9930-2b5946d170de.png)

**Comment by alefragnani** [comment]
@pythoninja unless you save a project/configure an automatic detection of repositories, it won’t show up. 

I'll change this behavior in #227 ..

Hope this helps

**Comment by pythoninja** [comment]
@alefragnani thank you for your reply! Btw, I had just opened "git" project which was successfully detected by Project Manager and...

![image](https://user-images.githubusercontent.com/13417093/50385414-4c11f200-06e6-11e9-8643-0a367c9ceb42.png)

Still do not see any button or something related to "git project". It's possible I misunderstood something...

**Comment by alefragnani** [comment]
@pythoninja I don't know if I understood correctly, but it appears you just opened a folder that is a git repository, using `File / Open`, right? If that's the case, then you didn't use Project Manager to open projects, you just opened a git folder.

To make Project Manager _to autodetect / recognize_ Git projects in your computer, you need to configure it. Open `Preferences / Settings` and define `projectManager.git.baseFolders` (more info [here](
https://github.com/alefragnani/vscode-project-manager#available-settings)) with the base folder that contains your Git repositories. When you save the settings, **Project Manager** will scan that location, looking for Git repositories, and each one detected will be presented in the Activity Bar, as shown [here](
https://github.com/alefragnani/vscode-project-manager#activity-bar).

Hope this helps.
