### ISSUE TITLE
Make silent upgrades

### ISSUE THREAD

**Issue by ucirello** [alefragnani/vscode-project-manager#246]
Currently, when this extension upgrades itself, it shows a screen with a list of issues and few extra pieces of text.

I'd like it to have an option that would allow for silent upgrades - or perhaps just a downright corner toast.

The current upgrade screen is really invasive.

**Comment by alefragnani** [comment]
Hi @ucirello ,

Thank you for your suggestions, but I'll keep the current approach for now. Don't worry, the "What's New" window will appear only on new releases. This is not a nag window.

Hope this helps

**Comment by ucirello** [comment]
Why not adding an option for silent upgrades? It is annoying as it is.
