### ISSUE TITLE
No working in vscode 1.0

### ISSUE THREAD

**Issue by gslsouza** [alefragnani/vscode-project-manager#25]
List, edit and save. But stopped loading project.
Windows 10.

**Comment by alefragnani** [comment]
Hi @gslsouza ,

Are you running Code from _Start Menu / Icons_ or from _console_? 
Did you follow the instructions from **Readme.md** to configure `projectManager.codePath`?

Hope this helps

**Comment by gslsouza** [comment]
Sorry. Forgot to edit this line. It is working fine. Thank you
