### ISSUE TITLE
怎么在两个窗口里打开同一个项目？

### ISSUE THREAD

**Issue by junjie-lean** [alefragnani/vscode-project-manager#251]
我确实是有这样的需求，谢谢。

**Comment by junjie-lean** [comment]
我找到方法了，将该项目加入到工作区就能解决这个问题，谢谢。

**Comment by Tom9402** [comment]
但是打开同一个项目的不同分支呢？

**Comment by alefragnani** [comment]
Hi @Tom9402 ,

Do you mean **Git** branches? If that’s the case, it’s not supported, nor planned, sorry.
