### ISSUE TITLE
Workspace settings support for Project Manager

### ISSUE THREAD

**Issue by redfellow** [alefragnani/vscode-project-manager#253]
Would be nice to have projects contain workspace settings. For example this style of having content in workspace settings in the projects.json:

```json
[
	{
		"name": "modules / tools",
		"rootPath": "c:\\git\\modules\\tools",
		"paths": [],
		"group": "",
		"enabled": true,
		"workspace.settings": {
			"settings": {
				"git.autofetch": false,
				"git.autorefresh": false,
				"window.title": "tools — ${dirty}${activeEditorMedium}${separator}",
				"workbench.colorCustomizations": {
					"activityBar.background": "#243427"
				}
			}
		}
	}
]
```

**Comment by alefragnani** [comment]
Hi @redfellow ,

Thank you for your suggestion, but I wouldn’t mix the management (catalog) of projects, with its settings. This would end up creating another level of complexity on how the settings are applied when you open a workspace. 

`<Project Manager Settings><Workspace Settings><Folder Settings><User Settings>`

Instead, I have #151, which still depends on API to be available in VS Code.

Hope this helps
