### ISSUE TITLE
Feature-request: Fuzzy Search 'ListProjects'

### ISSUE THREAD

**Issue by p-sebastian** [alefragnani/vscode-project-manager#254]
Great extensions, I am currently having trouble using the search function of "projectManager.listProjects", since it doesn't do **fuzzy search**. I have a huge list of projects that I want to be able to access via this list as a command, but it makes it difficult to switch if I don't remember the exact beginning etc. 

Point to note 'Im mostly a keyboard user'

Also on another note, it would be great if we could group projects by more user defined categories, that take into account the fuzzy search, such as in my case: 
> 'work, courses, projects, sandbox'.  

And this one which might be more complicated, tags for project types:
> 'web, native, react, cordova, etc.'

Thank you, and fuzzy search would be a game changer for me in this.

**Comment by alefragnani** [comment]
Hi @p-sebastian ,

I agree that the project search/filter would be enhanced, but unfortunately, this depends on VS Code itself. There is no way to _customize_ the search/filter, as already reported in #66 and #67.

I suggest you to play with `projectManager.sortList` and `projectManager.groupList` settings. Maybe it would minimize the troubles.

About grouping, this is already being tracked in #50.

Hope this helps
