### ISSUE TITLE
Feature-Request: Open project in new window

### ISSUE THREAD

**Issue by mt-webdev** [alefragnani/vscode-project-manager#256]
Hey everyone,

it just came to my mind that it would be awesome to have a feature like CMD + Click (on project) which will open another instance/window of vscode.

I am jumping between projects multilpe times per second (at least how it feels) and sometimes just wanna jump in'n'out to make a minor change or something. So its a struggle right click vs code -> select new window -> select project -> do stuff.

Thx as always!! Keep building! 💯

**Comment by alefragnani** [comment]
Hi @mt-webdev ,

I would like to have it too 😢 , and it was already reported in #76 , but as [commented here](https://github.com/alefragnani/vscode-project-manager/issues/76#issuecomment-270261352), it depends on VS Code team to publish an API for that. The request was already made in https://github.com/Microsoft/vscode/issues/18064, but unfortunately, no ETA. I'm subscribed to that issue, so if/when it is closed, I'll be notified.

In the meantime, you could bind a new Keyboard Shortcut for the `List Projects to Open in New Window` command, and you would have almost the same feeling.

Hope this helps

**Comment by dantodev** [comment]
If this feature will be possible and implemented in the future please consider to also use the middle mouse button to open a project in a new window.

**Comment by alefragnani** [comment]
Hi @dantodev ,

It does not work for me today (at least not commands like `Open Recent`), but maybe because I define middle-button as OS features . But sure, if the VS Code team releases an API, that's a great idea 👍
