### ISSUE TITLE
Any chance to provide the ability to colorize project list

### ISSUE THREAD

**Issue by mikeerickson** [alefragnani/vscode-project-manager#262]
First of all, thank for this project, I am getting used to using it (just started using a couple weeks ago).

Now, is there any way you could add support for colorizing the project list (either foreground or background colors).  I have some 30 or so projects that I bounce around on and it would be quite helpful if I could apply colors based on the type of project)

**Comment by alefragnani** [comment]
Thank you @mikeerickson ,

Unfortunately, neither the `Command Palette` nor the `Side Bar` supports this kind of customization, at least not yet.

Based on the [VS Code Restrictions](
https://code.visualstudio.com/api/extension-capabilities/overview#restrictions), I’m not sure this would happen to the `Command Palette`. Maybe, sometime in the future, it would be available to customize the items in the `Side Bar`, similar to what you see in Git panel.

Hope this helps

**Comment by mikeerickson** [comment]
Ok, sounds good. I was indeed referring to the sidebar.  Was just curious.  Maybe someday dine the raid
