### ISSUE TITLE
Support enviroment variables in rootPath

### ISSUE THREAD

**Issue by thomasfrobieter** [alefragnani/vscode-project-manager#263]
I've tried to use:

`"rootPath": "c:\\Users\\${env:USERNAME}\\Documents\\Projects\\xyz",`

But the variable isn't replaced. The variable is based on this article: https://code.visualstudio.com/docs/editor/variables-reference

**Comment by alefragnani** [comment]
Hi @thomasfrobieter ,

The extension does not support those variables. Those are available only for Debugging and Tasks (VS Code native operations).

If you want your _home folder_, you could use `$home` instead. This is a special variable that I created in the extension, exactly for this 😀 . Its use is described [here](https://github.com/alefragnani/vscode-project-manager#edit-projects).

```json
  {
        "name": "Bookmarks",
        "rootPath": "$home\\Documents\\GitHub\\vscode-bookmarks",
        "paths": [],
        "group": "",
        "enabled": true
    }
```
> Use a special variable called `$home` while defining any `path`. It will be replaced by the HOME folder.

Hope this helps
