### ISSUE TITLE
"projectManager.treeview.visible" setting no longer works

### ISSUE THREAD

**Issue by Gama11** [alefragnani/vscode-project-manager#265]
With the latest release, I have the project manager icon showing in the side bar despite having `"projectManager.treeview.visible": false` in my `settings.json`. The setting still seems to exist however, there's no "unknown setting" warning.

![](https://i.imgur.com/EReyFhu.png)

A possible workaround is to uncheck "Project Manager" in the context menu.

**Comment by alefragnani** [comment]
Sorry about that. 😞 😞 

I really forgot to test that scenario. I hope to find a way which doesn’t undo #264 .

Stay tuned

**Comment by Gama11** [comment]
Disabling it from the context menu seems to serve more or less the same purpose, so maybe it would be fine to just remove the setting? Perhaps I'm missing a use case though.

**Comment by alefragnani** [comment]
If I remember correctly, removing from the context menu doesn’t work between sessions. Every time you restart VS Code will bring back the icon. Unless, this has been fixed in recent releases.

**Comment by Gama11** [comment]
Doesn't seem to be an issue for me.

The only potential issue I can think of is if you use the VSCode settings sync extension to sync across multiple computers. Then you'd probably have to disable the view once on each, instead of that being covered by the setting.

**Comment by Gama11** [comment]
Btw, in case you do decide to remove setting, you can attach a deprecation warning to it along the lines of "disable in context menu instead".

**Comment by alefragnani** [comment]
I just confirmed that disabling/hiding the icon from the Activity Bar does work between sessions 🎉. I'm really happy to see this has been fixed.

So, I'm following your suggestion,. removing the  `projectManager.treeview.visible` setting, and adding a _deprecation warning_.

Thank you

**Comment by Gama11** [comment]
Hm.. actually, the project manager side bar item just reappeared for me out of nowhere. Not sure what triggered it, perhaps the new VSCode update? :)

**Comment by alefragnani** [comment]
I just found the issue that _fixed_ the behavior that I commented (https://github.com/Microsoft/vscode/issues/60097)

I installed both updates (stable and insiders) and the side bar icon didn't show up. Using Win10 BTW.

Maybe you are experiencing a regression in https://github.com/Microsoft/vscode/issues/60097?

**Comment by Gama11** [comment]
I don't think so, it doesn't reappear after a reload, or even a complete restart of VSCode (all instances closed). Like I said, no idea what triggered it. :(

**Comment by Gama11** [comment]
Oh, by "add a deprecation warning", I meant using the official mechanism for that. ;)

```json
"properties": {
    "projectManager.treeview.visible": {
        "type": "boolean",
        "deprecationMessage": "If you don't want to see the Project Manager icon in the Activity Bar, right-click and uncheck it from the context menu."
    }
}
```

![](https://i.imgur.com/9ibRK3W.png)

**Comment by alefragnani** [comment]
There is an _official mechanism_? 😮
