### ISSUE TITLE
run script on terminal on load

### ISSUE THREAD

**Issue by nonlinear** [alefragnani/vscode-project-manager#269]
i dunno if it's a security issue, but i'd like to run a script per project when I open it. It's usually to run either jekyll, gatsby, etc.

**Comment by alefragnani** [comment]
Hi @nonlinear ,

I don't see that as a _security issue_, and I agree it's may be useful in some scenarios. But I'm sorry, I think its _out of scope_ for this extension. 

It has been already requested (#130) sometime ago, and I suggested to take a look at [Auto Run Command extension](https://marketplace.visualstudio.com/items?itemName=gabrielgrinberg.auto-run-command). If you search for "run command" in VS Code marketplace [link](https://marketplace.visualstudio.com/search?term=run%20command&target=VSCode&category=All%20categories&sortBy=Relevance) you may find more extensions, with similar purpose.

Hope this helps

**Comment by nonlinear** [comment]
That helps a lot. Why rebuild functionality that is already out there? Scope scope scope.
