### ISSUE TITLE
feature-request: open workspace whenever possible

### ISSUE THREAD

**Issue by mugi-luffy** [alefragnani/vscode-project-manager#270]
When switching between projects, VSCode brings up a popup and asks if I want to open the workscape that was found in that folder.
It would be nice if the extension would look for the *.code-workspace file in the root of the folder and open it instead of just opening the folder. 
If no workspace file (or more than one) was found, it should default to the current behavior.

**Comment by alefragnani** [comment]
Hi @mugi-luffy ,

As noted in https://github.com/alefragnani/vscode-project-manager/issues/266, this is caused by VS Code itself, not the extension. You can see more details in that issue.

The workspace support is being tracked in #151.

Hope this helps
