### ISSUE TITLE
How to Contribution?

### ISSUE THREAD

**Issue by s97712** [alefragnani/vscode-project-manager#271]
I need to add some features, but I can't run this extension,  `vscode-project-manager-core` and `vscode-whats-new` is unaccessable, how should I do?

**Comment by alefragnani** [comment]
Hi @s97712 ,

I’m refactoring the extension’s core, and until this task is finished, you won’t be able to build it. It would take a couple of weeks, until a buildable version is available.

Stay tuned.

**Comment by isundaylee** [comment]
@alefragnani Would it be possible to post an update here when the refactoring is completed? I'm interested in helping add Remote Development support, if such support isn't planned/being worked on already by someone else. 

BTW, thanks for making such an awesome plugin! It's my must-have for VSCode.

**Comment by CurtisBelt** [comment]
@alefragnani Hello! You mentioned "a couple weeks" while closing the issue, but 10 months later they are still inaccessible? Is this being tracked elsewhere? Thanks! I was going to see if I could help improve the projects fuzzy search but this has me dead in the water.

**Comment by diminutivesloop** [comment]
Any updates on the refactoring effort for core?
