### ISSUE TITLE
Feature request: Show project name in VS Code title bar

### ISSUE THREAD

**Issue by zehfred** [alefragnani/vscode-project-manager#272]
Let's say my folder is called 'my-project' but I saved the project with the name 'My Project'. Currently VS Code shows the name of the folder in the title bar. Would be really great to have it display 'My Project - Visual Studio Code'. Do you think that would be possible? Thanks 🤞

**Comment by alefragnani** [comment]
Hi @zehfred ,

I do agree its an interesting feature, but as already reported in #98, it depends on VSCode providing an API for that. I have requested that API in https://github.com/Microsoft/vscode/issues/22037, but it was closed by the VS Code team.

Sorry about that.

**Comment by aaron13223** [comment]
I made a quick extension based on [this](https://github.com/microsoft/vscode/issues/202991#issuecomment-2310582766)

It works!
