### ISSUE TITLE
Remember open files

### ISSUE THREAD

**Issue by axelhuizinga** [alefragnani/vscode-project-manager#285]
How can I tell project manager to reopen all open files of a project?

**Comment by alefragnani** [comment]
Hi @axelhuizinga ,

The extension doesn’t do that. It’s not it’s intention to work with _user session_. 

If I remember correctly, VS Code itself does that (at least I’ve noted a certain _level_ of restore, but if you asked this, it’s probably not what you expect. I suggest you to take a look at VS Code repo for similar requests, or try a few other extensions, like https://marketplace.visualstudio.com/items?itemName=eamodio.restore-editors and https://marketplace.visualstudio.com/items?itemName=uyiosa-enabulele.reopenclosedtab, which appears to do this kind of work.

Hope this helps
