### ISSUE TITLE
No option to set a "Focus on Favorites {Git,View}" shortcut

### ISSUE THREAD

**Issue by cig0** [alefragnani/vscode-project-manager#289]
Hi @alefragnani,

Do you have plans to support opening the panel with shortcuts?

Thanks!

**Comment by alefragnani** [comment]
Hi @cig0 ,

Do you mean these commands?

![image](https://user-images.githubusercontent.com/3781424/62556798-086e9180-b84c-11e9-9c19-3bd8a5851949.png)

These are not created/published by the extension, but by VS Code itself, and I don't know how/if you can define shortcuts. At least, it does not appear in `Preferences: Open Keyboard Shortcuts` pane.

Hope this helps

**Comment by cig0** [comment]
That very same. No, there's no way to add a keybinding for them at the time :(

TYVM for your quick reply!
