### ISSUE TITLE
New Side Bar icon matching new VS Code icon style

### ISSUE THREAD

**Issue by alefragnani** [alefragnani/vscode-project-manager#290]

**Comment by derekshirk** [comment]
I came here looking to see if this was something that was already in progress and if I could help. 

Looks like it has already been assigned. Looking forward to this update. 😄

**Comment by alefragnani** [comment]
Yes, it should be updated this weekend.
Stay tuned

**Comment by derekshirk** [comment]
Awesome. Thanks!
