### ISSUE TITLE
Allow preservation of unsaved and temporary files when switching project

### ISSUE THREAD

**Issue by kevindashgit** [alefragnani/vscode-project-manager#291]
Coming from tmux/vim - I commonly switch between vim windows and sessions. When I leave a session containing files that are open (in vim) and modified unsaved - I know that when I return to this session, the state is preserved. 

In VSCode - using your extension to move around to different projects, it would be great if I could leave the current project w/o being prompted to save - instead I wanna just switch, leaving and preserving current state. If its not saved, leave it open, but not saved - so that when I come back to it - its still in that state.

**Comment by alefragnani** [comment]
Hi @kevindashgit ,

I think you are talking about **hot exit** (initially discussed in https://code.visualstudio.com/blogs/2016/11/30/hot-exit-in-insiders) right? 

In this case, this is a VS Code core feature (not from this extension). To achieve that, you have to change your `User Settings`, updating the `Hot Exit` setting to `onExitAndWindowClose` (the default value is `onExit`). 

Hope this helps

**Comment by kevindashgit** [comment]
@alefragnani right on the money! Thank you!!!
