### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by AndreiJirohHaliliDev2006** [alefragnani/vscode-project-manager#292]
- Issue Type: `Performance`
- Extension Name: `project-manager`
- Extension Version: `10.6.0`
- OS Version: `Windows_NT x64 6.2.9200`
- VSCode version: `1.37.1`

Report Info:
`{
    "nodes": [
        {
            "id": 1,
            "callFrame": {
                "functionName": "(root)",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 0,
            "children": [
                2,
                54,
                55,
                61
            ]
        },
        {
            "id": 2,
            "callFrame": {
                "functionName": "o",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 12,
                "columnNumber": 799
            },
            "hitCount": 0,
            "children": [
                3
            ]
        },
        {
            "id": 3,
            "callFrame": {
                "functionName": "next",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 0,
            "children": [
                4
            ]
        },
        {
            "id": 4,
            "callFrame": {
                "functionName": "",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 768,
                "columnNumber": 545
            },
            "hitCount": 0,
            "children": [
                5
            ]
        },
        {
            "id": 5,
            "callFrame": {
                "functionName": "_activateById",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 759,
                "columnNumber": 713
            },
            "hitCount": 0,
            "children": [
                6
            ]
        },
        {
            "id": 6,
            "callFrame": {
                "functionName": "activateById",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 493,
                "columnNumber": 739
            },
            "hitCount": 0,
            "children": [
                7
            ]
        },
        {
            "id": 7,
            "callFrame": {
                "functionName": "_activateExtensions",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 495,
                "columnNumber": 359
            },
            "hitCount": 0,
            "children": [
                8
            ]
        },
        {
            "id": 8,
            "callFrame": {
                "functionName": "map",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 0,
            "children": [
                9
            ]
        },
        {
            "id": 9,
            "callFrame": {
                "functionName": "define._activateExtensions.r.length.Promise.all.s.map.e",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 495,
                "columnNumber": 805
            },
            "hitCount": 0,
            "children": [
                10
            ]
        },
        {
            "id": 10,
            "callFrame": {
                "functionName": "_activateExtension",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 495,
                "columnNumber": 942
            },
            "hitCount": 0,
            "children": [
                11
            ]
        },
        {
            "id": 11,
            "callFrame": {
                "functionName": "actualActivateExtension",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 757,
                "columnNumber": 562
            },
            "hitCount": 0,
            "children": [
                12
            ]
        },
        {
            "id": 12,
            "callFrame": {
                "functionName": "n",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 12,
                "columnNumber": 738
            },
            "hitCount": 0,
            "children": [
                13
            ]
        },
        {
            "id": 13,
            "callFrame": {
                "functionName": "Promise",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 0,
            "children": [
                14
            ]
        },
        {
            "id": 14,
            "callFrame": {
                "functionName": "n",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 12,
                "columnNumber": 783
            },
            "hitCount": 0,
            "children": [
                15
            ]
        },
        {
            "id": 15,
            "callFrame": {
                "functionName": "next",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 0,
            "children": [
                16
            ]
        },
        {
            "id": 16,
            "callFrame": {
                "functionName": "",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 757,
                "columnNumber": 599
            },
            "hitCount": 0,
            "children": [
                17
            ]
        },
        {
            "id": 17,
            "callFrame": {
                "functionName": "_activateExtension",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 760,
                "columnNumber": 935
            },
            "hitCount": 0,
            "children": [
                18
            ]
        },
        {
            "id": 18,
            "callFrame": {
                "functionName": "_doActivateExtension",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 761,
                "columnNumber": 580
            },
            "hitCount": 0,
            "children": [
                19,
                47
            ]
        },
        {
            "id": 19,
            "callFrame": {
                "functionName": "",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 761,
                "columnNumber": 951
            },
            "hitCount": 0,
            "children": [
                20
            ]
        },
        {
            "id": 20,
            "callFrame": {
                "functionName": "i",
                "scriptId": "81",
                "url": "pii_removed\\loader.js",
                "lineNumber": 30,
                "columnNumber": 594
            },
            "hitCount": 0,
            "children": [
                21
            ]
        },
        {
            "id": 21,
            "callFrame": {
                "functionName": "require",
                "scriptId": "73",
                "url": "internal/modules/cjs/helpers.js",
                "lineNumber": 16,
                "columnNumber": 18
            },
            "hitCount": 0,
            "children": [
                22
            ]
        },
        {
            "id": 22,
            "callFrame": {
                "functionName": "Module.require",
                "scriptId": "71",
                "url": "internal/modules/cjs/loader.js",
                "lineNumber": 631,
                "columnNumber": 35
            },
            "hitCount": 0,
            "children": [
                23
            ]
        },
        {
            "id": 23,
            "callFrame": {
                "functionName": "",
                "scriptId": "169",
                "url": "pii_removed\\extension.js",
                "lineNumber": 36,
                "columnNumber": 379977
            },
            "hitCount": 0,
            "children": [
                24
            ]
        },
        {
            "id": 24,
            "callFrame": {
                "functionName": "",
                "scriptId": "169",
                "url": "pii_removed\\extension.js",
                "lineNumber": 36,
                "columnNumber": 379220
            },
            "hitCount": 0,
            "children": [
                25
            ]
        },
        {
            "id": 25,
            "callFrame": {
                "functionName": "t.getExtensionPathIndex.then.i._load",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 699,
                "columnNumber": 105
            },
            "hitCount": 0,
            "children": [
                26
            ]
        },
        {
            "id": 26,
            "callFrame": {
                "functionName": "t._load",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 775,
                "columnNumber": 960
            },
            "hitCount": 0,
            "children": [
                27
            ]
        },
        {
            "id": 27,
            "callFrame": {
                "functionName": "define._installInterceptor.i._load",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 507,
                "columnNumber": 765
            },
            "hitCount": 0,
            "children": [
                28
            ]
        },
        {
            "id": 28,
            "callFrame": {
                "functionName": "Module._load",
                "scriptId": "71",
                "url": "internal/modules/cjs/loader.js",
                "lineNumber": 504,
                "columnNumber": 23
            },
            "hitCount": 0,
            "children": [
                29
            ]
        },
        {
            "id": 29,
            "callFrame": {
                "functionName": "tryModuleLoad",
                "scriptId": "71",
                "url": "internal/modules/cjs/loader.js",
                "lineNumber": 537,
                "columnNumber": 22
            },
            "hitCount": 0,
            "children": [
                30
            ]
        },
        {
            "id": 30,
            "callFrame": {
                "functionName": "Module.load",
                "scriptId": "71",
                "url": "internal/modules/cjs/loader.js",
                "lineNumber": 592,
                "columnNumber": 32
            },
            "hitCount": 0,
            "children": [
                31
            ]
        },
        {
            "id": 31,
            "callFrame": {
                "functionName": "Module._extensions..js",
                "scriptId": "71",
                "url": "internal/modules/cjs/loader.js",
                "lineNumber": 701,
                "columnNumber": 36
            },
            "hitCount": 0,
            "children": [
                32
            ]
        },
        {
            "id": 32,
            "callFrame": {
                "functionName": "t._initNodeRequire.o._compile",
                "scriptId": "81",
                "url": "pii_removed\\loader.js",
                "lineNumber": 14,
                "columnNumber": 263
            },
            "hitCount": 0,
            "children": [
                33
            ]
        },
        {
            "id": 33,
            "callFrame": {
                "functionName": "",
                "scriptId": "220",
                "url": "pii_removed\\extension.js",
                "lineNumber": 0,
                "columnNumber": 10
            },
            "hitCount": 0,
            "children": [
                34
            ]
        },
        {
            "id": 34,
            "callFrame": {
                "functionName": "",
                "scriptId": "220",
                "url": "pii_removed\\extension.js",
                "lineNumber": 0,
                "columnNumber": 103
            },
            "hitCount": 0,
            "children": [
                35
            ]
        },
        {
            "id": 35,
            "callFrame": {
                "functionName": "",
                "scriptId": "220",
                "url": "pii_removed\\extension.js",
                "lineNumber": 0,
                "columnNumber": 178
            },
            "hitCount": 0,
            "children": [
                36
            ]
        },
        {
            "id": 36,
            "callFrame": {
                "functionName": "r",
                "scriptId": "220",
                "url": "pii_removed\\extension.js",
                "lineNumber": 0,
                "columnNumber": 201
            },
            "hitCount": 0,
            "children": [
                37
            ]
        },
        {
            "id": 37,
            "callFrame": {
                "functionName": "module.exports.Object.defineProperty.value",
                "scriptId": "220",
                "url": "pii_removed\\extension.js",
                "lineNumber": 0,
                "columnNumber": 9092
            },
            "hitCount": 0,
            "children": [
                38
            ]
        },
        {
            "id": 38,
            "callFrame": {
                "functionName": "r",
                "scriptId": "220",
                "url": "pii_removed\\extension.js",
                "lineNumber": 0,
                "columnNumber": 201
            },
            "hitCount": 0,
            "children": [
                39,
                46
            ]
        },
        {
            "id": 39,
            "callFrame": {
                "functionName": "module.exports.e.exports",
                "scriptId": "220",
                "url": "pii_removed\\extension.js",
                "lineNumber": 0,
                "columnNumber": 30115
            },
            "hitCount": 0,
            "children": [
                40
            ]
        },
        {
            "id": 40,
            "callFrame": {
                "functionName": "r",
                "scriptId": "220",
                "url": "pii_removed\\extension.js",
                "lineNumber": 0,
                "columnNumber": 201
            },
            "hitCount": 0,
            "children": [
                41,
                43
            ]
        },
        {
            "id": 41,
            "callFrame": {
                "functionName": "module.exports.Object.defineProperty.value",
                "scriptId": "220",
                "url": "pii_removed\\extension.js",
                "lineNumber": 0,
                "columnNumber": 32077
            },
            "hitCount": 2,
            "children": [
                42
            ],
            "positionTicks": [
                {
                    "line": 1,
                    "ticks": 2
                }
            ]
        },
        {
            "id": 42,
            "callFrame": {
                "functionName": "RegExp",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 1
        },
        {
            "id": 43,
            "callFrame": {
                "functionName": "module.exports.Object.defineProperty.value",
                "scriptId": "220",
                "url": "pii_removed\\extension.js",
                "lineNumber": 0,
                "columnNumber": 47287
            },
            "hitCount": 0,
            "children": [
                44
            ]
        },
        {
            "id": 44,
            "callFrame": {
                "functionName": "r",
                "scriptId": "220",
                "url": "pii_removed\\extension.js",
                "lineNumber": 0,
                "columnNumber": 201
            },
            "hitCount": 0,
            "children": [
                45
            ]
        },
        {
            "id": 45,
            "callFrame": {
                "functionName": "module.exports.o.__awaiter.r",
                "scriptId": "220",
                "url": "pii_removed\\extension.js",
                "lineNumber": 0,
                "columnNumber": 8926
            },
            "hitCount": 1,
            "positionTicks": [
                {
                    "line": 1,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 46,
            "callFrame": {
                "functionName": "",
                "scriptId": "220",
                "url": "pii_removed\\extension.js",
                "lineNumber": 0,
                "columnNumber": 51846
            },
            "hitCount": 1,
            "positionTicks": [
                {
                    "line": 1,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 47,
            "callFrame": {
                "functionName": "_loadExtensionContext",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 762,
                "columnNumber": 330
            },
            "hitCount": 1,
            "children": [
                48
            ],
            "positionTicks": [
                {
                    "line": 763,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 48,
            "callFrame": {
                "functionName": "n",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 343,
                "columnNumber": 909
            },
            "hitCount": 0,
            "children": [
                49
            ]
        },
        {
            "id": 49,
            "callFrame": {
                "functionName": "getValue",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 605,
                "columnNumber": 480
            },
            "hitCount": 0,
            "children": [
                50
            ]
        },
        {
            "id": 50,
            "callFrame": {
                "functionName": "then",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 511,
                "columnNumber": 536
            },
            "hitCount": 0,
            "children": [
                51
            ]
        },
        {
            "id": 51,
            "callFrame": {
                "functionName": "_ensureActual",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 511,
                "columnNumber": 100
            },
            "hitCount": 0,
            "children": [
                52
            ]
        },
        {
            "id": 52,
            "callFrame": {
                "functionName": "Promise",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 0,
            "children": [
                53
            ]
        },
        {
            "id": 53,
            "callFrame": {
                "functionName": "define._ensureActual._actual._actual.Promise",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 511,
                "columnNumber": 150
            },
            "hitCount": 1,
            "positionTicks": [
                {
                    "line": 512,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 54,
            "callFrame": {
                "functionName": "(program)",
                "scriptId": "0",
                "url": "",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 3
        },
        {
            "id": 55,
            "callFrame": {
                "functionName": "processTimers",
                "scriptId": "75",
                "url": "timers.js",
                "lineNumber": 208,
                "columnNumber": 22
            },
            "hitCount": 0,
            "children": [
                56
            ]
        },
        {
            "id": 56,
            "callFrame": {
                "functionName": "listOnTimeout",
                "scriptId": "75",
                "url": "timers.js",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 0,
            "children": [
                57,
                60
            ]
        },
        {
            "id": 57,
            "callFrame": {
                "functionName": "tryOnTimeout",
                "scriptId": "75",
                "url": "timers.js",
                "lineNumber": -1,
                "columnNumber": -1
            },
            "hitCount": 0,
            "children": [
                58
            ]
        },
        {
            "id": 58,
            "callFrame": {
                "functionName": "ontimeout",
                "scriptId": "75",
                "url": "timers.js",
                "lineNumber": 417,
                "columnNumber": 18
            },
            "hitCount": 0,
            "children": [
                59
            ]
        },
        {
            "id": 59,
            "callFrame": {
                "functionName": "",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 774,
                "columnNumber": 822
            },
            "hitCount": 1,
            "positionTicks": [
                {
                    "line": 775,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 60,
            "callFrame": {
                "functionName": "ok",
                "scriptId": "30",
                "url": "assert.js",
                "lineNumber": 353,
                "columnNumber": 11
            },
            "hitCount": 1,
            "positionTicks": [
                {
                    "line": 354,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 61,
            "callFrame": {
                "functionName": "onStreamRead",
                "scriptId": "61",
                "url": "internal/stream_base_commons.js",
                "lineNumber": 86,
                "columnNumber": 21
            },
            "hitCount": 0,
            "children": [
                62
            ]
        },
        {
            "id": 62,
            "callFrame": {
                "functionName": "Readable.push",
                "scriptId": "41",
                "url": "_stream_readable.js",
                "lineNumber": 201,
                "columnNumber": 34
            },
            "hitCount": 0,
            "children": [
                63
            ]
        },
        {
            "id": 63,
            "callFrame": {
                "functionName": "readableAddChunk",
                "scriptId": "41",
                "url": "_stream_readable.js",
                "lineNumber": 226,
                "columnNumber": 25
            },
            "hitCount": 0,
            "children": [
                64
            ]
        },
        {
            "id": 64,
            "callFrame": {
                "functionName": "addChunk",
                "scriptId": "41",
                "url": "_stream_readable.js",
                "lineNumber": 279,
                "columnNumber": 17
            },
            "hitCount": 0,
            "children": [
                65
            ]
        },
        {
            "id": 65,
            "callFrame": {
                "functionName": "EventEmitter.emit",
                "scriptId": "172",
                "url": "domain.js",
                "lineNumber": 430,
                "columnNumber": 38
            },
            "hitCount": 0,
            "children": [
                66
            ]
        },
        {
            "id": 66,
            "callFrame": {
                "functionName": "emit",
                "scriptId": "17",
                "url": "events.js",
                "lineNumber": 139,
                "columnNumber": 43
            },
            "hitCount": 0,
            "children": [
                67
            ]
        },
        {
            "id": 67,
            "callFrame": {
                "functionName": "t",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 189,
                "columnNumber": 325
            },
            "hitCount": 0,
            "children": [
                68
            ]
        },
        {
            "id": 68,
            "callFrame": {
                "functionName": "define.constructor._register._socket.onData.e",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 180,
                "columnNumber": 910
            },
            "hitCount": 0,
            "children": [
                69
            ]
        },
        {
            "id": 69,
            "callFrame": {
                "functionName": "acceptChunk",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 180,
                "columnNumber": 975
            },
            "hitCount": 0,
            "children": [
                70
            ]
        },
        {
            "id": 70,
            "callFrame": {
                "functionName": "fire",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 48,
                "columnNumber": 925
            },
            "hitCount": 0,
            "children": [
                71
            ]
        },
        {
            "id": 71,
            "callFrame": {
                "functionName": "define.constructor._socketDisposables.push._socketReader.onMessage.e",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 185,
                "columnNumber": 107
            },
            "hitCount": 0,
            "children": [
                72
            ]
        },
        {
            "id": 72,
            "callFrame": {
                "functionName": "_receiveMessage",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 187,
                "columnNumber": 398
            },
            "hitCount": 0,
            "children": [
                73
            ]
        },
        {
            "id": 73,
            "callFrame": {
                "functionName": "fire",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 48,
                "columnNumber": 925
            },
            "hitCount": 0,
            "children": [
                74
            ]
        },
        {
            "id": 74,
            "callFrame": {
                "functionName": "e",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 178,
                "columnNumber": 846
            },
            "hitCount": 0,
            "children": [
                75
            ]
        },
        {
            "id": 75,
            "callFrame": {
                "functionName": "a",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 178,
                "columnNumber": 776
            },
            "hitCount": 0,
            "children": [
                76
            ]
        },
        {
            "id": 76,
            "callFrame": {
                "functionName": "fire",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 48,
                "columnNumber": 925
            },
            "hitCount": 0,
            "children": [
                77
            ]
        },
        {
            "id": 77,
            "callFrame": {
                "functionName": "n.constructor.e.onMessage.e",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 774,
                "columnNumber": 33
            },
            "hitCount": 0,
            "children": [
                78
            ]
        },
        {
            "id": 78,
            "callFrame": {
                "functionName": "fire",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 48,
                "columnNumber": 925
            },
            "hitCount": 0,
            "children": [
                79
            ]
        },
        {
            "id": 79,
            "callFrame": {
                "functionName": "e",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 178,
                "columnNumber": 846
            },
            "hitCount": 0,
            "children": [
                80
            ]
        },
        {
            "id": 80,
            "callFrame": {
                "functionName": "a",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 178,
                "columnNumber": 776
            },
            "hitCount": 0,
            "children": [
                81
            ]
        },
        {
            "id": 81,
            "callFrame": {
                "functionName": "fire",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 48,
                "columnNumber": 925
            },
            "hitCount": 0,
            "children": [
                82
            ]
        },
        {
            "id": 82,
            "callFrame": {
                "functionName": "define.constructor._protocol.onMessage.e",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 663,
                "columnNumber": 391
            },
            "hitCount": 0,
            "children": [
                83
            ]
        },
        {
            "id": 83,
            "callFrame": {
                "functionName": "_receiveOneMessage",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 664,
                "columnNumber": 896
            },
            "hitCount": 1,
            "children": [
                84,
                93
            ],
            "positionTicks": [
                {
                    "line": 666,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 84,
            "callFrame": {
                "functionName": "_receiveRequest",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 666,
                "columnNumber": 78
            },
            "hitCount": 0,
            "children": [
                85
            ]
        },
        {
            "id": 85,
            "callFrame": {
                "functionName": "send",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 774,
                "columnNumber": 117
            },
            "hitCount": 0,
            "children": [
                86
            ]
        },
        {
            "id": 86,
            "callFrame": {
                "functionName": "send",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 188,
                "columnNumber": 31
            },
            "hitCount": 0,
            "children": [
                87
            ]
        },
        {
            "id": 87,
            "callFrame": {
                "functionName": "write",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 181,
                "columnNumber": 947
            },
            "hitCount": 0,
            "children": [
                88,
                90
            ]
        },
        {
            "id": 88,
            "callFrame": {
                "functionName": "writeUInt32BE",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 6,
                "columnNumber": 391
            },
            "hitCount": 0,
            "children": [
                89
            ]
        },
        {
            "id": 89,
            "callFrame": {
                "functionName": "i",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 5,
                "columnNumber": 402
            },
            "hitCount": 1,
            "positionTicks": [
                {
                    "line": 6,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 90,
            "callFrame": {
                "functionName": "alloc",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 5,
                "columnNumber": 607
            },
            "hitCount": 0,
            "children": [
                91
            ]
        },
        {
            "id": 91,
            "callFrame": {
                "functionName": "allocUnsafe",
                "scriptId": "25",
                "url": "buffer.js",
                "lineNumber": 290,
                "columnNumber": 41
            },
            "hitCount": 0,
            "children": [
                92
            ]
        },
        {
            "id": 92,
            "callFrame": {
                "functionName": "allocate",
                "scriptId": "25",
                "url": "buffer.js",
                "lineNumber": 318,
                "columnNumber": 17
            },
            "hitCount": 1,
            "positionTicks": [
                {
                    "line": 326,
                    "ticks": 1
                }
            ]
        },
        {
            "id": 93,
            "callFrame": {
                "functionName": "deserializeRequestJSONArgs",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 671,
                "columnNumber": 794
            },
            "hitCount": 5,
            "children": [
                94
            ],
            "positionTicks": [
                {
                    "line": 672,
                    "ticks": 5
                }
            ]
        },
        {
            "id": 94,
            "callFrame": {
                "functionName": "readLongString",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 669,
                "columnNumber": 868
            },
            "hitCount": 0,
            "children": [
                95
            ]
        },
        {
            "id": 95,
            "callFrame": {
                "functionName": "toString",
                "scriptId": "96",
                "url": "pii_removed\\extensionHostProcess.js",
                "lineNumber": 6,
                "columnNumber": 158
            },
            "hitCount": 0,
            "children": [
                96
            ]
        },
        {
            "id": 96,
            "callFrame": {
                "functionName": "toString",
                "scriptId": "25",
                "url": "buffer.js",
                "lineNumber": 643,
                "columnNumber": 45
            },
            "hitCount": 2,
            "positionTicks": [
                {
                    "line": 646,
                    "ticks": 2
                }
            ]
        }
    ],
    "startTime": 4757323887,
    "endTime": 4757602527,
    "samples": [
        41,
        42,
        41,
        41,
        45,
        46,
        47,
        53,
        54,
        59,
        54,
        60,
        54,
        83,
        89,
        92,
        96,
        96,
        93,
        93,
        93,
        93,
        93
    ],
    "timeDeltas": [
        256420,
        374,
        343,
        123,
        119,
        121,
        124,
        189,
        116,
        114,
        316,
        116,
        111,
        116,
        119,
        118,
        119,
        117,
        117,
        116,
        128,
        116,
        218
    ]
}`

**Comment by alefragnani** [comment]
Hi @AndreiJirohHaliliDev2006 ,

Thank you for your time generating such report, but unfortunately I’m not sure how to read it. Which tool should I use? 

Also, could you elaborate more about which scenarios/moments  do you see the extension with high load CPU? It only _do some work_ in 3 moments:

- when you open a new VS Code instance
- when you _list projects to open_
- when you _change some of its settings_

Thank you

**Comment by AndreiJirohHaliliDev2006** [comment]
> Hi @AndreiJirohHaliliDev2006 ,
> 
> Thank you for your time generating such report, but unfortunately I’m not sure how to read it. Which tool should I use?
> 
> Also, could you elaborate more about which scenarios/moments do you see the extension with high load CPU? It only _do some work_ in 3 moments:
> 
> * when you open a new VS Code instance
> * when you _list projects to open_
> * when you _change some of its settings_
> 
> Thank you

I'm not sure how that hell happens, but I had the CPU profile file for the unresponsive problem issue. ([See alefragnani.project-manager-unresponsive.cpuprofile.txt](https://github.com/alefragnani/vscode-project-manager/files/3511674/alefragnani.project-manager-unresponsive.cpuprofile.txt))

**Comment by alefragnani** [comment]
How do you know this was caused by this extension, not VS Code itself, or any other installed extension? I didn’t recognized any mention to my extension in this log.

Thanks

**Comment by alefragnani** [comment]
Hi @AndreiJirohHaliliDev2006 ,

Are you still facing this error? Did it happen again? If yes please, could you provide more details which could help me to identify and fix it. Otherwise, I think I could close the issue.

Thank you

**Comment by AndreiJirohHaliliDev2006** [comment]
Because I forgot how this hell happen, I'll close it to declutter your issue tracker.
