### ISSUE TITLE
Open a project in New Window by "Ctrl+Click"

### ISSUE THREAD

**Issue by ShoshinNikita** [alefragnani/vscode-project-manager#294]
It would be very convenient to open a project in New Window by `Ctrl+Click` (like **Go To Definition** works) from the **Side Bar**

**Now:**

- Right click
- Select `Open in New Window`

**After:**

- `Ctrl+Click`

**Comment by alefragnani** [comment]
Hi @ShoshinNikita 

This has already been requested (#190), and that issue has been closed a few months back, because the VS Code team didn’t commented/planned their issue for more than an year.

I’m sorry to say, but I don’t think this will happen anytime soon.

Hope this helps

**Comment by ShoshinNikita** [comment]
Oh, I didn't notice the issue. It's a pity that VS Code team didn't add the feature.

Anyway, thank you for the answer)
