### ISSUE TITLE
new install - where is projects.json?

### ISSUE THREAD

**Issue by xthdraft** [alefragnani/vscode-project-manager#296]
The extension is listed as active, and when I click the manage icon then "configure extension settings",  a list of 24 items appears.  Some of these direct me to "edit in settings.json".  I can see no reference to projects.json, nor can I find such a file anywhere on my hard drive.   Consequently I have no idea how to open this extension. 

Clicking on the extension name in the extension panel just opens the extension's information page in github.

 I thought an install would place the extension in vs code's  main file menu.  But it doesn't seem to in my case. Have I done something wrong?

**Comment by alefragnani** [comment]
Hi @xthdraft ,

I think you are mixing two different things here. What you described is _how to manage “any extension setting”_, which stores things in `settings.json`. The `projects.json` file is where this extension stores the projects you saved (more info down). I suggest you invest a bit of time reading VS Code documentation about [settings](https://code.visualstudio.com/docs/getstarted/settings), so you can have a better understanding on how VS Code works. You will see, for instance, that no extension adds any item to the “main menu”.

To use the extension itself I suggest you to read the [README file](https://github.com/alefragnani/vscode-project-manager#manage-your-projects), but TL;DR... 

1. Open any folder in VS Code and use the `Project Manager: Save Project` to save this folder as a **Favorite** 
1. Anytime you need to open that **Favorite** folder, use the `Project Manager: List Projects to Open` command and select the desired project from the list.
1. If you have Git, SVN, Mercurial projects, you can configure the extension to **auto-detect** them [more info](https://github.com/alefragnani/vscode-project-manager#available-settings)

Hope this helps

**Comment by xthdraft** [comment]
Sorry to be obtuse, but I opened a folder from VS Code File menu, but can't
then see any item on any menu which says "Project Manager: Save Project."
There are items on the VS Code File menu saying "Save as"  and "Save
workspace as.."   Do I click on one of those?

**Comment by alefragnani** [comment]
No need to be sorry 👍 

There is no menu item, you have to use the `Command Palette`, which you open using `F1`, `Ctrl + Shift + P`, or menu `Go / Command Palette` _(if I remember correctly)_

VS Code does not allow extensions to add Menu Items to the Application, neither Buttons (as you can see, there is no toolbar in VS Code). It’s a _typings first editor_, like Sublime, and it uses the same approach. The commands that are available, will be available _primarily_ in `Command Palette`. There are a few UI elements that the team added throughout the years, and In my case, I added a Side Bar with a few buttons and context menus (recent API available). You can use that too.

Hope this helps

**Comment by xthdraft** [comment]
Thanks so much, opening the command palette clears everything up, and I am
now good to go.

I'd like to respectfully comment on your readme file.     For someone with
no prior experience of  vs code (myself), it's not clear from your readme
that one must open the command palette to understand into your program.  A
complete newbe wouldn't know anything about a "command palette". Perhaps
you could make that step more explicit in your readme setup instructions.

Anyway, I'm really looking forward to using your extension, as vcode needs
this functionality.

best regards.
