### ISSUE TITLE
Must save the changes before switch projects

### ISSUE THREAD

**Issue by j5465** [alefragnani/vscode-project-manager#298]
Today when I made some change in a file and then switch to another project, appearing a dialog alert me to save the file otherwise my changes will be lost.
I remember I could switch freely just like reopen vscode window and my change is still there in the past.
Is this because of different versions or some settings ? 
> System: windows 10
> vscode version:1.37.1
> project manager version: 10.7.0

**Comment by alefragnani** [comment]
Hi @j5465 

You may be facing the same issue as #291. It's a VS Code core feature (not from this extension).

Hope this helps
