### ISSUE TITLE
Feature Request: open option icons on hover

### ISSUE THREAD

**Issue by supdegrave** [alefragnani/vscode-project-manager#302]
[Note: this may be related to #76 and #256] 

When the sidebar project list is shown, it would be great to have icons displayed when hovering over a project item, for the [Open] and [Open in New Window] commands. 

In the Mercurial source control extension (mrcrowl.hg), icons to discard or stage changes are displayed when you hover on a changed file. Having similar functionality for [Open] and [Open in New Window] would make it so that users don't have to right-click in order to choose [Open in New Window]. 

Behavior when clicking on the project item itself in the list, rather than one of the icons, should remain consistent.

**Comment by alefragnani** [comment]
Hi @supdegrave ,

If I understand correctly, you mean those icons that appears at the right side of each item in the tree, right? That’s a great idea 👍 .

Thank you

**Comment by supdegrave** [comment]
Yep, that's what I have in mind. Here's a screenshot of what I'm using for comparison. 

![VSCode Hg Plugin hover icons](https://user-images.githubusercontent.com/5695160/66110369-efbdf600-e5c6-11e9-8c73-a3016de665a5.png)
