### ISSUE TITLE
Can we have colours.. colors... ink.. something?

### ISSUE THREAD

**Issue by Narven** [alefragnani/vscode-project-manager#303]
Hi,

In the follow of quest to improve on my human writing and related to my previous [request odessy](https://github.com/alefragnani/vscode-project-manager/issues/301) I would like to request another thingy.. small... tiny one... small.. this size |<-------->|

Since humans have evolve so much since President Bill Clinton and Monica Lewinsky dancing, and we all live colourful happy lives, is it possible to add a property to each of the projects called `color`... `colour`... (damn human writing...)... `ink`.

That would change the `color`... `colour`... (:angry:)... `ink` of the vscode title bar based on the project?

Is kinda hard when you have 6 projects open all with the same pink color.. :cry:  .. ink.

It would be nice do differentiate each one. One light pink, another medium pink the other darkpink and humanpink... kinda `fifty shades of pink` (would need to have more projects of course)

Just an idea. :bowing_man: ... hehe aliens don't bow.

**Comment by alefragnani** [comment]
Hi @Narven,

Do you know the [Peacock](https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock) extension? I guess it should fit perfectly in your scenario.

Btw, sometime ago a similar issue (#253) was created, but asking to create another level of settings, which I think it’s too much complex to manage. I would like to keep the extension just a manager of your projects. But I understand, and sometimes I feel _it could be_ a bit more.

Hope this helps

**Comment by alefragnani** [comment]
About time, thank you for your kind words. I’m glad to know the extension is being helpful 😊 .

**Comment by Narven** [comment]
Yes. I know about Peacock, just found it yesterday :P 
I could be fun to see if peacock could interact with this extension :D

**Comment by alefragnani** [comment]
That’s great!
What kind of interaction do you think? How it would work?
The extensions can publish their own API to be used by other extensions, so it depends on the desired scenarios.,

**Comment by Narven** [comment]
I was think, that this extension could have that property of "colour", and there were 2 choices:

* colour could be set manual, like `"colour": "#ffcc99"`
* if Peacock is installed it would store that configuration also into project-manager config

Peacock would be the color manager of Project Manager :1st_place_medal:
