### ISSUE TITLE
Add parent folders within project list

### ISSUE THREAD

**Issue by mariusvw** [alefragnani/vscode-project-manager#306]
When scanning for projects it would be nice to have the ability to include the parent folder name.

For example if you have this structure:

- projects/clientA/someproject
- projects/clientB/someproject
- projects/clientC/someproject

You currently will have no idea which project is listed because they have the same name like so.

- someproject
- someproject
- someproject

It would be nice to have at least one above folder visible:

- clientA/someproject
- clientB/someproject
- clientC/someproject

**Comment by alefragnani** [comment]
Hi @mariusvw ,

A similar request has been made sometime ago (#99) but the author ended up changing the setup and canceled the issue. There is another request still open (#184) which I think is kind of equivalent to your request. 

I think this "same-name conflict" issue would be solved adding the _different path portion_ (in your example, `clientA`, `clientB` and `clientC`) to the right of the project name, with a smaller font (at least in the Side Bar). You can see this when you use `Find in Files` and it matches a same-name file in different folders. Look at the _image_ label:

![Screen Shot 2019-11-01 at 23 07 16](https://user-images.githubusercontent.com/3781424/68064599-6ea86a80-fcfc-11e9-9f0b-b8372cbfeff0.png)

What do you think?

ps. I don't know if you are aware of, but the hint in each project shows the full path.

**Comment by mariusvw** [comment]
I like to work on it and show you what I mean.

First thing I ran into is that I cant access the vscode-project-manager-core repository to pull the source.

I have some more issues (bugs) that I ran into but without being able to setup a testing environment I am stuck :)

**Comment by CurtisBelt** [comment]
@mariusvw I had the same issue, this is the best tracking I've found so far for it: #271

**Comment by gromov-io** [comment]
good solution

clientA/someproject
clientB/someproject
clientC/someproject

**Comment by Tealk** [comment]
is there actually any news on this?
