### ISSUE TITLE
Open project in new window from status bar option

### ISSUE THREAD

**Issue by thebspin** [alefragnani/vscode-project-manager#307]
I know there was #190 but i would like this to be an setting per project or a global option, both would work fine for me.

**Comment by alefragnani** [comment]
Hi @thebspin ,

You already have a setting available to that 😬 . Just set `projectManager. openInNewWindowWhenClickingInStatusBar` to `true`.

Hope this helps.

**Comment by thebspin** [comment]
Ah i am sorry.
I found that by just doing random stuff in my settings.json but it needed a reload with that setting to actually work :)
