### ISSUE TITLE
Sort list by recent does not work

### ISSUE THREAD

**Issue by Sunxiangpeng0531** [alefragnani/vscode-project-manager#308]
Hi, I'm using project manager under macOS. It seems like sorting list by recent is not working as expected. As you can see, the recent order in welcome page is not the same as project list.
![1573575355952](https://user-images.githubusercontent.com/34417280/68689382-3716a980-05ab-11ea-8c22-c6b0a869d56d.jpg)
So can you please check the issue? Thanks very much!

**Comment by alefragnani** [comment]
Hi @Sunxiangpeng0531 ,

I'm sorry to say, but there is no connection between both _Recent_ lists. 

* The recent list from the **extension**  is related to recent projects that you opened using the extension's commands (`List Projects to Open` and `List Projects to Open in New Window`), the Side Bar or the Status Bar. BTW, the _sorting_ it is available only in the `Command Palette`, not in the Side Bar

* The recent list from the **Welcome Page** is controlled by VS Code itself, and _I guess_ it respect the `Open` and `Open Recent` commands (native).

I remember sometime ago seeing an issue in the VS Code repo to allow extensions to _customize_ the Welcome Page. But nothing has been released/available yet.

Hope this helps
