### ISSUE TITLE
key binding seems not to working

### ISSUE THREAD

**Issue by gsscoder** [alefragnani/vscode-project-manager#311]
Hi,
thanks for very intelligent and useful VSCode extension.

I've added the following key binding but it seems not working:
```
{
        "key": "cmd+alt+j",
        "command": "workbench.action.quickOpenSelectNext",
        "when": "inProjectManagerList"
}
```

I run **VSCode** on macOS Catalina, **Project Manager** 10.9.1.

**Comment by alefragnani** [comment]
Hi @gsscoder ,

Could you check if you already have "another command" assigned to `cmd+alt+j`? Execute the `Preferences: Open Keyboard Shortcuts` command and type `cmd+alt+j` in the edit field. 

In my case, I already have `Bookmarks: Jump to Previous` command, from my other **Bookmarks** extension assigned 😄 .

Then, I assigned another keyboard shortcut `Ctrl+Alt+J` and it worked perfectly

Hope this helps

**Comment by gsscoder** [comment]
Thanks for replying @alefragnani! No, there's nothing assigned and I'm unable also with a different unassigned combination.

Very weird...

If you want me check other things, please ask.

**Comment by alefragnani** [comment]
Hi @gsscoder ,

Just to be clear, you are following [this instructions](https://github.com/alefragnani/vscode-project-manager#keyboard-focused-users), right? I mean, Yyou are trying to _navigate_ between the projects which were _previously displayed_ by the `List Projects to Open` and/or `List Projects to Open in New Window` command.

**Comment by gsscoder** [comment]
Hello, @alefragnani. Again, thanks for your time.

For some reason what I do (maybe because my experience with VS Code is still limited), doesn't change the key binding. I checked actual key bindings opening config json: `CMD+SHIFT+P > Open Default Keybord Shortcuts` and added the entry in `Code -> Preferences -> Keybord Shortcuts` using various combinations (none worked).

Anyway using CMD+SHIFT+P I was able to discover that `List Projects to Open` is bound to CMD+ALT+P.

So in the end I got what I need! :) Thank you

**Comment by alefragnani** [comment]
No problem 👍 

You just mixed two different key bindings. 

You were trying to define the key binding to be used _to move Up/Down when you already have the list of projects available_, not to _list projects itself_. Glad to see it’s working 🎉
