### ISSUE TITLE
Add a "switch project" keyboard shortcut

### ISSUE THREAD

**Issue by vict0rsch** [alefragnani/vscode-project-manager#312]
It would be great if we could have a functionality to easily switch projects in the spirit of what `cmd/ctrl + tab` does on the OS

**Comment by alefragnani** [comment]
Hi @vict0rsch ,

VS Code already have a _built in_ command for that. Take a look at the `Quick Switch Window..` command. You just need to define a keyboard shortcut 😄 .

You also have the `Switch Window...` command, which will show you the list of opened projects, for you to pick.

Hope this helps
