### ISSUE TITLE
Clicking project in list when it's already open does nothing

### ISSUE THREAD

**Issue by aheckler** [alefragnani/vscode-project-manager#313]
Not sure if this is a bug exactly, but it's definitely unexpected. To reproduce:

1. Quit VS Code and open it fresh.
2. Click the Project Manager icon in the Activity Bar.
3. Click a project in the list to open it in Explorer.
4. Click the Project Manager icon to go back to the list.
5. Click the same project you just opened.
6. Nothing happens.

In my mind, I would expected to be kicked back to the Explorer view, since my project is already open there.

**Comment by alefragnani** [comment]
Hi @aheckler ,

This is the _default_ VS Code behavior when you open a project, which is already open. It does not _force_ the Explorer view.

You can reproduce the same behavior using the native `File: Open Recent` command. Try to focus on different views (Debug, Extensions, Find), and you will notice it does nothing when you re-select the current project.

Maybe you could open an issue in the VS Code repo, suggesting a _confirmation message_, or something like this.

Hope this helps

**Comment by aheckler** [comment]
Done: https://github.com/microsoft/vscode/issues/87305

**Comment by leonbloy** [comment]
This behaviour would be much less confusing if the currently selected project were distinguishable from the other (in different color or something).

**Comment by alefragnani** [comment]
@leonbloy, as [commented here](https://github.com/alefragnani/vscode-project-manager/issues/346#issuecomment-600283776) you could define different values in `colorCustomizations` setting (for each project), or you could use an extension, like [Peacoc](https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock)

**Comment by leonbloy** [comment]
Thanks, Ale, but I wish the "current" project to be displayed differently.

**Comment by alefragnani** [comment]
Well, the Peacock extension has a _“Surprise me on Startup_ setting, which will apply a random color to the current project, but I don’t know other details about it.

Otherwise, if doing it _manually_ or using the Peacock extension is not an option to you, feel free to open a new issue specific to this.

Hope this helps
