### ISSUE TITLE
Running the contributed command:'projectManager.listProjects' failed.

### ISSUE THREAD

**Issue by alanlv** [alefragnani/vscode-project-manager#32]
OSX 10.11.4
VSC 1.1.1
Project Manager 0.7

run "project manager list" command, alert the failed message as "Running the contributed command:'projectManager.listProjects' failed."
note: "project manager save", "project manager edit" is normal

console logs:
Running the contributed command:'projectManager.listProjects' failed. //Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:117 

e.onUnexpectedError @ //Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:117

WARNING: Promise with no error callback:6
//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:31 
//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:31 

Object
error: "Running the contributed command:'projectManager.listProjects' failed."exception: nullhandler: undefinedid: 6parent: undefinedpromise: __dirname.undefined.t.Class.derive._oncancel_errorId: 6_isException: false_listeners: null_nextState: null_oncancel: null_state: Object_completed: i()arguments: (...)caller: (...)length: 0name: "i"prototype: Objectconstructor: i()__proto__: Object__proto__: ()<function scope>_error: i()_notify: p(e,t)_progress: i()_setCompleteValue: i()_setErrorValue: i()cancel: i()done: nullenter: (e)name: "error"then: null__proto__: Object_value: "Running the contributed command:'projectManager.listProjects' failed."done: (e,t)arguments: (...)caller: (...)length: 2name: ""prototype: Object__proto__: ()<function scope>then: (e,t)arguments: (...)caller: (...)length: 2name: ""prototype: Object__proto__: ()<function scope>__proto__: t_cancelAction: ()_cleanupAction: ()_oncancel: nullconstructor: (e,n)__proto__: Object__proto__: Object__defineGetter__: __defineGetter__()arguments: nullcaller: nulllength: 2name: "__defineGetter__"__proto__: ()<function scope>__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: get __proto__()set __proto__: set __proto__()arguments: nullcaller: nulllength: 1name: "set __proto__"__proto__: ()<function scope>

Running the contributed command:'projectManager.listProjects' failed. //Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:90 
e.doShow @ //Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:90

**Comment by Qwerios** [comment]
I think I'm getting the same issue. For me the call fails on a clean VSCode window but works if I have a folder open. Judging by the recent changes I'm guessing the check to omit the current project from the list is failing when no current project is opened.

**Comment by alefragnani** [comment]
@Qwerios Bingo :smile:  
I will update later today. Stay tuned.
