### ISSUE TITLE
Support for home folder tilde shortcut (~) in session paths.

### ISSUE THREAD

**Issue by trusktr** [alefragnani/vscode-project-manager#321]
At the moment, `projects.json` only support absolute paths, like this:

```json
    {
        "name": "infamous+infamous",
        "rootPath": "/home/trusktr/src/infamous+infamous",
        "paths": [],
        "group": "",
        "enabled": true
    },
```

however this is not compatible across platforms. On macOS, the sessions look like this:

```json
    {
        "name": "infamous+infamous",
        "rootPath": "/Users/trusktr/src/infamous+infamous",
        "paths": [],
        "group": "",
        "enabled": true
    },
```

The problem is that I am syncing my `~/.config/Code` and `~/.vscode` (and similar with VSCodium folders) using `git`. When I try to load a project with a path like `/Users/trusktr/src/infamous+infamous` in Linux, which expects it to be at `/home/trusktr/src/infamous+infamous`, then obviously it will not find it and shows this error:

![Screenshot from 2020-01-20 13-25-11](https://user-images.githubusercontent.com/297678/72758678-5839de80-3b88-11ea-8e2e-f249c5f9a890.png)

To solve this problem, it'd be great if Project Manager supported the `~` shortcut. Then, I could modify the project path (or Project Manager could detect the home folder automatically) to be like this:

```json
    {
        "name": "infamous+infamous",
        "rootPath": "~/src/infamous+infamous",
        "paths": [],
        "group": "",
        "enabled": true
    },
```

Then it would work in Linux, macOS, and Windows (assuming Project Manager maps the `/` to `\` in Windows). :)

**Comment by trusktr** [comment]
I'm not sure, but if Project Manager gets the path from VS Code, then maybe this is a VS Code issue? If it is, maybe Project Manager would need to make its own path handling.

**Comment by alefragnani** [comment]
Hi @trusktr ,

The extension already have support for `HOME` folders, but instead of using _tilde_ symbol, I created the `$home` variable. It's also multi-platform, and can be used in _auto-detected_ projects, btw 😄 .

From the [README](https://github.com/alefragnani/vscode-project-manager#edit-projects) file:
> Use a special variable called $home while defining any path. It will be replaced by the HOME folder.

Hope this helps
