### ISSUE TITLE
Windows Subsystem Linux: "Command 'Project Manager: Save Project' is not enabled in the current context."

### ISSUE THREAD

**Issue by gkrauze** [alefragnani/vscode-project-manager#324]
Hi,

I work with WSL and VS Code with Remote WSL extension. After I changed place where WSL is stored on Windows I cannot Save any project and open paths defined for linux filesystem. 
When I try to "Save Project" I get warning: 
`Command 'Project Manager: Save Project' is not enabled in the current context.`
When I try to save the project definition manually, I cannot enter the project as after clicking the project name this extension tries to open path under Windows, that doesn't refer to linux filesystem.

I tried also to install earlier versions of the extension, but it is the same. I believe it is happening after I moved WSL machine from default location of system partition to custom location at the other partition.

Thank you in advance.
Regards

**Comment by alefragnani** [comment]
Hi @gkrauze ,

This has been added in the latest release. This has been discussed in #318 and #284, but to sum um, the idea to _disable the command_ was to avoid error if the user tried to save a folder _inside a remote_, which would not be accessible from outside (the host). But it appears some users installed the extension _inside the remote_ and would like to have separate projects, for each remote.

I'm collecting feedbacks in #323 , so a new update could incorporate new/better support for these scenarios.

I don't use remotes that much (only Containers, in fact), and never played with WSL. So I have no idea if _"changing the place where WSL is stored on Windows"_. would have any impact. Sorry.

Hope this helps
