### ISSUE TITLE
Project Manager extension disabled on remote machine after upgrade to 10.10.0

### ISSUE THREAD

**Issue by yuruiz** [alefragnani/vscode-project-manager#329]
The Project Manager extension works fine on remote development mode on 10.9.1 but as soon as I upgrade to 10.10.0 it is disabled on my remote machine. And as I downgrade to 10.9.1 the extension back to work.

My local development environment is MACOS 10.15.3 and remote development environment is  
NAME="Alibaba Group Enterprise Linux Server"
VERSION="7.2 (Paladin)"
ID="alios"
ID_LIKE="fedora"
VERSION_ID="7.2"
PRETTY_NAME="Alibaba Group Enterprise Linux Server 7.2 (Paladin)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:alibaba:enterprise_linux:7.2:GA:server"
HOME_URL="https://www.aliyun.com/"
BUG_REPORT_URL="http://bbs.aliyun.com/"

ALIBABA_BUGZILLA_PRODUCT="Alibaba Group Enterprise Linux 7"
ALIBABA_BUGZILLA_PRODUCT_VERSION=7.2
ALIBABA_SUPPORT_PRODUCT="Alibaba Group Enterprise Linux"
ALIBABA_SUPPORT_PRODUCT_VERSION=7.2

**Comment by SleepyHero** [comment]
I Encounter this problem too, fix it pls

**Comment by alefragnani** [comment]
Hi @yuruiz @SleepyHero ,

This has been intentionally added in the latest release. It was discussed in #318 and #284, but to sum up, the idea to _disable the command_ was to avoid error if the user tried to save a folder _inside a remote_, which would not be accessible from outside (the host). But it appears some users installed the extension _inside the remote_ and would like to have separate projects, for each remote.

I'm collecting feedbacks in #323 , so new updates could incorporate new/better support for these scenarios.

Hope this helps
