### ISSUE TITLE
extensionKind "["ui"] is too strict, the extension can also run a a workspace extension

### ISSUE THREAD

**Issue by egamma** [alefragnani/vscode-project-manager#330]
Hi, given the PR from @Chuxel this extension can now also run as workspace extension. It does but does not have any hard requirements on local assets, devices, or capabilities. Therefore please change the extensionKind to "extensionKind": ["ui", "workspace"] which makes the extension more generally usable.

For more details pls see https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location.

**Comment by alefragnani** [comment]
Hi @egamma ,

This has been intentionally _stricted_ in the latest release. It was discussed in #318 and #284, and to sum up, I didn’t thought users would need/want to install the extension on remotes, but instead, just see the projects _from the host._ But it appears some users installed the extension inside the remote and would like to have separate projects, for each remote.

I'm collecting feedbacks in #323 , so new updates could incorporate new/better support for these scenarios. 

Thank you for your PR. It’s one of the changes that I have to make, and it’s a good start 👍 . I also need to re-enable the `Save Project` command, so the extension _should work_ as before. 

I wonder if I could have a way to open _any_ remote folder, even when I’m local. It appears [this comment](https://github.com/microsoft/vscode/issues/89952#issuecomment-581830749) Is a start, but I didn’t dig on the extension itself to see if I can know if I’m currently running remotely, so I would know if I save local or remote folders. I’ll think about that after re-enabling `workspace` use and the `Save Project` command.

Thank you

**Comment by egamma** [comment]
@alefragnani 

>This has been intentionally stricted in the latest release. 

Stricting the extension to `["ui"]` was the right thing to do. Since the extension can also run in the remote extension host, the extension kind should also express this, that is, `["ui", "workspace"]`.

>But it appears some users installed the extension inside the remote and would like to have separate projects, for each remote.

Another use case is when VS Code is run in the browser in [VS Online](https://visualstudio.microsoft.com/de/services/visual-studio-online/). In this setup there is no UI extension host and your extension cannot be installed at all when it is `["ui"]` only. With `["ui", "workspace"]`the extension can be installed and it can be used to manage the projects inside one environment using your extension. 

You could think of a project manager that would work across VSO Environements and VS Code. To do so you would have to store the project.json in the cloud or in some gist so that it can be accessed from anywhere.

>I wonder if I could have a way to open any remote folder, even when I’m local.

This is possible when you know the full URI of the remote folder. It can either be done using a command (see this comment https://github.com/microsoft/vscode/issues/89952#issuecomment-581830749) or it can be done using the VS Code CLI using the `--folder-uri` command line argument.
