### ISSUE TITLE
Current project doesn't show up in status bar if $path variable is used

### ISSUE THREAD

**Issue by thomasfrobieter** [alefragnani/vscode-project-manager#332]
Since i use the $path variable for project paths the current project is no more visible in the status bar. 

So this doesn't work:
"rootPath": "$home\\Documents\\Projects\\projectx",

while this works:
"rootPath": "C:\\Users\\Thomas Frobieter\\Documents\\Projects\\projectx",

OS is Windows 10

**Comment by alefragnani** [comment]
Hi @thomasfrobieter ,

Thank you for reporting. I didn’t notice it was not working in recent releases, and I’m not sure why it stopped working as well 😕 .

**Comment by alefragnani** [comment]
Just noticed this has already been fixed with #414
