### ISSUE TITLE
Saving open tabs in a project?

### ISSUE THREAD

**Issue by gandalfsaxe** [alefragnani/vscode-project-manager#335]
I'm only starting to use projects and workspaces etc. more. As far as I can see, there is only a way to save a folder or set of folders to a project, but not a persistent way to save a set of open tabs. I.e. save them not as a state on a single machine, but in a file that can be synced to any machine?

E.g. I can open project X on my Macbook Pro and open tab A, B, C. Then I want to save it such that when I open project X on my iMac, tabs A, B, C are also opened.

If this is not a solved problem (with built-in functionality + Project Manager extension), perhaps this structure:
```
[
	{
		"name": "",
		"rootPath": "",
		"paths": [],
		"group": "",
		"enabled": true
	}
]
```
could be complemented with a:
```
openTabs: []
```
?

**Comment by alefragnani** [comment]
Hi @gandalfsaxe ,

The idea for the extension is to give you easy access to your projects, but no necessarily their _sessions_. In fact, you may have already noticed that VS Code itself already manage your session, restoring the open tabs when you re-open a project, folder or workspace. In this case, if you decide to replace this native restore to use your tabs, you may end up “fighting”.

Right now, the VS Code team is developing **Settings Sync** native in VS Code, and I guess they will add not only _settings_ but also _session information_. So, will be able to open files in you MacBook and restore the same tabs on your iMac.

Today, I would suggest you to try out other two extensions, which could help you on this matter, until the native **Settings Sync** land in VS Code:

* **Settings Sync**: https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync
* **Restore Editors**: https://marketplace.visualstudio.com/items?itemName=eamodio.restore-editors

Hope this helps

**Comment by gandalfsaxe** [comment]
Ah didn't they know were working on native settings sync. Do you have any link to this?

If they do this, they better solve this one too (which doesn't seem to have priority): https://github.com/microsoft/vscode/issues/81340 - I foresee a problem when you're working on different machines with access to different folders. The portable version failed quite ungracefully and would throw up a ton a errors on not being able to open some files when I opened it on my home computer after doing some work on my work computer. That's part of why I'm not using the portable version anymore btw. So yeah, I'm already using **Settings Sync** :)

Restore Editors looks interesting (though a bit limited by the lack of APIs). I'll see if I feel the need, perhaps install later. Thanks.

**Comment by alefragnani** [comment]
I would start here https://github.com/microsoft/vscode/issues/78966 and https://github.com/microsoft/vscode/issues/90129. Maybe digging deeper through the related issues would help you to find out if it would work on your scenarios.

I only share my settings, Keybindings and snippets between my personal computers, not _sessions_, and decided to use a GitHub repo to store this data. But I understand sometimes you want to continue working right where you left. It’s a very popular request in VS Code (right from the beginning).

**Comment by gandalfsaxe** [comment]
Ah great! Will be interesting to compare to Settings Sync. Thanks for the tip.

For me it's less about continue right from where I left off, and more about a set of text files that I frequently open to change/add some things. I can usually use ⌃R (File -> Open Recent -> More...) to achieve this, but more ideally I'd like a solution that didn't require me on having the file open recently (could be flaky + not work on a fresh VSCode installation).

**Comment by alefragnani** [comment]
You could look at [this extension](https://marketplace.visualstudio.com/items?itemName=yukidoi.blade-runner). Maybe it would help you, with little effort to accomplish your scenario.

Otherwise, it looks an opportunity for a _new extension_ to me 😬. I feel it would be fairly easy to do, with small complexity, at least for basic usage/scenarios. Do you have any other requirements/scenarios to share? Maybe I’m missing something.

Hope this helps

**Comment by gandalfsaxe** [comment]
Are you sure this is not within the scope of this extension though? You initially closed the issue saying:

> The idea for the extension is to give you easy access to your projects, but no necessarily their _sessions_.

However I'm not looking to restore _sessions_ but rather a fixed set of files I frequently need open, once I open a certain project :)

**Comment by alefragnani** [comment]
Haha, good one 😁.
Let’s see...
