### ISSUE TITLE
Correction in the project tagline

### ISSUE THREAD

**Issue by oldmankit** [alefragnani/vscode-project-manager#337]
Thanks for the very nice plugin.

In the description, the tagline is _Don't miss that important projects anymore._

It's almost perfect. Just changing it to _Don't miss that important project anymore._ would be correct (no 's' on 'project'). Or you could change 'that' to 'those' if you want to keep it plural.

**Comment by alefragnani** [comment]
Hi @oldmankit ,

Good catch! The idea was to keep it plural

Thank you 👍
