### ISSUE TITLE
Review Whats New page content structure and elements emphasis 

### ISSUE THREAD

**Issue by pkkid** [alefragnani/vscode-project-manager#338]
This is totally a minor complaint..
* The "Whats New" page that opens once every update never contains anything new. I've stopped trying to read it several months ago and at this point, most people probably consider it spam.
* The use of bold fonts and highlighted text all over the page doesn't actually emphasize important parts of the document, but seemingly random words. This makes the page harder to read and look a bit unprofessional.

**Comment by alefragnani** [comment]
Hi @pkkid ,

> The "Whats New" page that opens once every update never contains anything new. I've stopped trying to read it several months ago and at this point, most people probably consider it spam.

I understand your complaint, but that's not entirely true. The `What's New` page is not a replacement for the changelog, but used to display the most important features that you receive with the latest releases.

But, If you take the latest release as an example, it has received 3 changes in its content, which are very similar to the [changelog](https://marketplace.visualstudio.com/items/alefragnani.project-manager/changelog) (the same happens for previous releases):

![Screen Shot 2020-03-08 at 11 31 18](https://user-images.githubusercontent.com/3781424/76164921-7310e400-6131-11ea-9783-be249aa69179.png)

![Screen Shot 2020-03-08 at 11 39 43](https://user-images.githubusercontent.com/3781424/76164931-88860e00-6131-11ea-8135-2934e16f2e2b.png)

I think that adding a `See changelog` link at the end of the `What' new` section would help

> The use of bold fonts and highlighted text all over the page doesn't actually emphasize important parts of the document, but seemingly random words. This makes the page harder to read and look a bit unprofessional.

The idea is to make the page simple, and easy to read. If some elements don't help _that much_, it's time to review them. The inspiration came from similar pages, so I'll take a look for updates and other ideas.

Thank you for your feedback 👍
