### ISSUE TITLE
Forcing lower case letters on new projects

### ISSUE THREAD

**Issue by rick9004** [alefragnani/vscode-project-manager#339]
Installed Project Manager 10.11     Also have installed the Flutter tools  plugins Flutter and Dart.

When I tried to add a new project after opening the folder the name field would not allow capitalized letters as before.  Flutter does not allow capitalization in project names.  This should not apply to the non flutter projects.    This is new since I installed the flutter and dart.  

Not sure if the new release of project manager or the flutter plugins causing this conflict.

**Comment by alefragnani** [comment]
Hi @rick9004 ,

Sorry, but I’m not sure I understand your scenario. What do you mean about “tried to add a new project”? Are you _saving a project_ or _adding a folder to some workspace_? Which command are you running? Please, could you add more details/prints, so I could see what’s going on?

The extension dos not force any _case_ while suggesting the Project Name. It uses the exact name from the Folder or Workspace. 

Hope this helps

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been made since my last question. 
Feel free to reopen/comment if the error still occurs.
