### ISSUE TITLE
Command to open/hide on the sidebar

### ISSUE THREAD

**Issue by smikheiev** [alefragnani/vscode-project-manager#340]
Hi! I'd like to add a shortcut for opening/hiding the Project Manager panel in the sidebar. To make this I'm adding the next to my "keybindings.json":
```
{
  "key": "cmd+6",
  "command": "workbench.view.XXX"
},
{
  "key": "cmd+6",
  "command": "workbench.action.toggleSidebarVisibility",
  "when": "sideBarFocus && activeViewlet == 'workbench.view.XXX'"
},
```
So to make this work I need to know the value XXX. For example, for Explorer panel it's `workbench.view.explorer`, for SCM - `workbench.view.scm`.

Is it possible to make something like that? If yes, then what is the XXX value?
Thanks in advance

**Comment by alefragnani** [comment]
Hi @smikheiev ,

The value for `XXX` should be `extension.project-manager`. 

It appears that non-native panels must be prefixed with `extension`. At least I have to use that on those that I have installed 😄 

Hope this helps
