### ISSUE TITLE
Feature request: sidebar groupings

### ISSUE THREAD

**Issue by supdegrave** [alefragnani/vscode-project-manager#341]
Currently I have Project Manager configured with more than ten projects. 

In several cases, the root project name is the same for two different projects. To differentiate, I've resorted to naming projects so that my sidebar looks something like this: 

```
personal-project-1
personal-project-2
parent-folder-1/project-1
parent-folder-1/project-2
parent-folder-2/project-1
parent-folder-2/project-2
```

Where `project-1` and `project-2` under the different parent folders have the same name.

It would be useful to have the sidebar support project groups, like this: 

```
personal-projects
    project-1
    project-2
parent-folder-1
    project-1
    project-2
parent-folder-2
    project-1
    project-2
```

Note that I believe this to be different from #247, as I want to see this in sidebar rather than the pick list.

**Comment by supdegrave** [comment]
@alefragnani It seems that this could be supported by extending projects.json in a similar fashion to what you suggested in #50. An optional projectName property could be added, and if missing or empty string the project would be displayed as it is currently. If a valid string value is present, the project would be displayed under the group. 

I imagine this could be supported by adding a context-menu item "Add to project group".

**Comment by alefragnani** [comment]
Hi @supdegrave ,

Yep, these are similar requests, and I guess a single solution would fit.  I have an idea, but I need to test the concept. If everything goes as expected, I would add more comments.

I’ll close this issue as a _duplicate_ of #50, but I’ll take your request in consideration while developing #50.

Hope this helps

**Comment by supdegrave** [comment]
Sounds good, thank you for investigating it.
