### ISSUE TITLE
FR: Add confirmation message when switching projects (same window only)

### ISSUE THREAD

**Issue by leonbloy** [alefragnani/vscode-project-manager#346]
I think that the current behaviour (switch projects at a single click, no confirmation or feedback) is a bit ... rude? 

I work with projects in different languages which involve starting servers from the terminal, and I often find myself switching project unintendedly - which is frustrating. A confirmation window, or at least some preference setting (ask for confirmation, or require double-click) would be welcomed.

**Comment by leonbloy** [comment]
This slight frustation goes hand in hand with issue #313 (Clicking project in list when it's already open does nothing)

As I comment there, things would be more user friendly if the currently selected project were distinguishable from the other ones (in different color or something).

**Comment by alefragnani** [comment]
Hi @leonbloy ,

Don't you miss a confirmation message while reopening folders/workspaces in VS Code itself? 

I mean, if you use the `Open Recent` command (native in VSCode), it doesn't show you any confirmation message, _unless_ you have unsaved files.

A confirmation message could be added, but depending of a setting (opt-in).

About _distinguishable projects_ you could define different values in `colorCustomizations` setting (for each project), or you could use an extension, like [Peacoc](https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock)

Hope this helps

**Comment by gdh1995** [comment]
> if you use the `Open Recent` command (native in VSCode), it doesn't show you any confirmation message, _unless_ you have unsaved files.

Yes it does replace a current project without warnings. As a result, I have to use Ctrl+Click on recent project items, which I think very inconvenient and causes myself turn to this extension for help.

I wonder an opt-in setting item to always open in a new window, when I click a project line in the list on its side bar.

**Comment by alefragnani** [comment]
Hi @gdh1995 ,

VS Code already supports that, and it will work not only in Side Bar, but also Command Palette. 

You just have to update your settings:

```json
    "window.openFoldersInNewWindow": "on"
```

Hope this helps

**Comment by gdh1995** [comment]
Yes it works. Thank you!
