### ISSUE TITLE
Cannot use intellisense in projects opened

### ISSUE THREAD

**Issue by YashSaxena9** [alefragnani/vscode-project-manager#347]
When I open the project using the Project manager then it doesn't underline/highlight the syntax errors in code.
Everything works fine if I open a folder in code using the terminal.

**Comment by alefragnani** [comment]
Hi @YashSaxena9 ,

I’ve never experienced this issue, and I’m not sure why this could be happening.

Do you experience the same issue if you open the project using the native `File / Open` command? That’s basically the same API that the extension uses. 

Hope this helps

**Comment by YashSaxena9** [comment]
No, there's no issue if I open the project using the native File / Open command.
I just installed this extension as it seemed very promising and convenient but then I noticed this issue.

**Comment by YashSaxena9** [comment]
What should I share for more information. 
I'd really like this extension to work :)

**Comment by alefragnani** [comment]
How are you using the extension? Did you _saved_ projects, or did you use the _auto-detection_ feature for Git/SVN projects?

**Comment by alefragnani** [comment]
BTW, if you open a folder using the native commands and the IntelliSense works, saving the project in Project Manager, using the `Project Manager: Save Project` command and reopening the project using the `Project Manager: List Projects to Open` command, should work as well.

Could you confirm that?

**Comment by YashSaxena9** [comment]
I actually added folders by editing `.json` file. Let me check the `save Project` command

**Comment by YashSaxena9** [comment]
I checked, the result is the same, it doesn't underline/highlight the syntax errors in code.

**Comment by YashSaxena9** [comment]
It seems like I found the issue, when I open a folder using the project manager then I need to manually enable `Report compilation errors for any non-project file in the current session`.
![Screenshot (12)](https://user-images.githubusercontent.com/50399404/77549315-b1e6be00-6ed5-11ea-8d48-3b096f95e27c.png)

I think maybe because I am not defining `package `for my `java `files

**Comment by alefragnani** [comment]
Great news! 🎉 

I’m not sure what this command/operation does. Is it some other extension you have installed?

**Comment by YashSaxena9** [comment]
Okay, I think I finally found the cause, its this error.

![Screenshot (16)_LI](https://user-images.githubusercontent.com/50399404/77582481-782dab80-6f05-11ea-8d7e-3a92bcf7137d.jpg)
my folder's name is pepCoding_master and its a GitHub repo too but the name appears as a project is different

Well, I'm a student and been learning java, so I use the java extension pack by Microsoft.
Please can you help me get rid of it :)

**Comment by YashSaxena9** [comment]
Sir, I dug in further and found the cause of the problem. Its a problem related to Redhat's ` java language support extension`, I just installed an older version of that extension and it started to underline/highlight the syntax errors in code.
The solution was to use an older version of this extension, seems like its new update caused an issue 
![javapic](https://user-images.githubusercontent.com/50399404/77584686-41f22b00-6f09-11ea-8c93-70e1a9056812.PNG)
Thank you, Sir, for giving your time for my problem 😊
I appreciate your help :)

**Comment by alefragnani** [comment]
That’s great to see it’s working now!

I hope you enjoy using the Project Manager extension.
