### ISSUE TITLE
Project Manager is not working

### ISSUE THREAD

**Issue by kumarharsh** [alefragnani/vscode-project-manager#35]
I've installed project manager on a pristine vscode-insider copy, and while running `Project Manager: Edit Projects` or `Project Manager: List Projects`, I only get the **No projects saved yet!** error. I manually created a file `projects.json` in the default directory, but no luck.

It used to work without any hitch earlier. I reinstalled vscode-insider into this new computer and am not able to get this plugin running at all.

**Comment by QuietusPlus** [comment]
Same issue here, I have tried this extension numerous times in the past two, maybe three weeks and it has yet to work.

I remember the extension asking me to re-launch as Administrator at some point, not sure if this may somehow be related. Let me know if there's something I can do to help (e.g. logs)...

**Comment by alefragnani** [comment]
Hi @kumarharsh 

I think the problem is related to this issue #22, which is still open because of [this issue](https://github.com/Microsoft/vscode/issues/2741). If so, try to create the folder related to stable version.

@QuietusPlus The _re-launch as Administrator_ question is strange. I don't do anything that could be related to admin privileges. Maybe a VSCode issue?

Hope this helps.

**Comment by QuietusPlus** [comment]
@alefragnani I figured as much on the Administrator issue, I personally wouldn't read too much into it (part of using the Insiders build really).

On-topic: I've resolved the issue by doing the following:

- Open up `%USERPROFILE%\.vscode-insiders\extensions\alefragnani.project-manager-0.7.1\out\extension.js`
- Change line 16 to: `projectFile = path.join(appdata, "Code - Insiders/User/projects.json");`
- Change line 20 to: `projectFile = path.join(os.homedir(), '.config/Code - Insiders/User/projects.json');`
- Restart Visual Studio Code - Insiders.

So it does seem related to the linked issues...

**Comment by alefragnani** [comment]
Depends on https://github.com/alefragnani/vscode-project-manager/issues/22
