### ISSUE TITLE
Feature request: folders for projects

### ISSUE THREAD

**Issue by gsscoder** [alefragnani/vscode-project-manager#352]
It would be great allow organising **projects** into **folders**. So I can define `GitHub`, `Jobs`, `Hacking` etc... One level will suffices.

Thank you again, for great extension!

**Comment by alefragnani** [comment]
Hi @gsscoder ,

I think this is a duplicate of #50, which asks some way to _group/organize_ projects, instead of the actual flat list.

I'm playing with a few ideas, and I hope something could go public in the coming weeks.

Stay tuned

**Comment by gsscoder** [comment]
@alefragnani, sorry I didn't noticed someone already proposed it.

I'm sure you'll make the correct design choice to implement it :)

Thank you and have a nice day!
