### ISSUE TITLE
Open a new window by default

### ISSUE THREAD

**Issue by NotLogic** [alefragnani/vscode-project-manager#356]
I need to start multiple projects at the same time. I want to click the project name and open a new window by default. Thank you.

**Comment by alefragnani** [comment]
Hi @NotLogic ,

If you use the Side Bar, just click in the icon at the right of the project, and it will be opened in a new window. If you use the `Command Palette`, simply use the `List Projects to Open in New Window` command instead.

Hope this helps.

**Comment by NotLogic** [comment]
Think you very much!


| |
刘彬彬
|
|
邮箱：logic1900@163.com
|

签名由 网易邮箱大师 定制

On 04/16/2020 10:40, Alessandro Fragnani wrote:

Closed #356.
