### ISSUE TITLE
Conflict with SyncSettings and json config location

### ISSUE THREAD

**Issue by rogerlais** [alefragnani/vscode-project-manager#364]
Congrats to your job. Its a great help

First:
Where is the correct config file ?
<AppData>\Roaming\Code\User\globalStorage\alefragnani.project-manager\projects.json or
<AppData>\Roaming\Code\User\projects.json

Second:
There is another extension(SyncSettings) that ignores all mask files projects.json, so yours settings are loosed. Are there a motivation or possibility from a alternative solution?

**Comment by alefragnani** [comment]
Hi @rogerlais ,

First of all, thank you for your kind works. I’m glad to know the extension helps you! 

About the “correct config file”, I would say both are Ok, but it will depend on which VS Code version you first installed the extension. At the beginning, it was `Roaming\Code\User\projects.json`, but about a year ago, VS Code changed the location to store some global data, and started using the new `...globalStorage..` folder (more details #250). The extension _understand/supports_ both.

About the sync, are your talking about [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync)? I’m not sure why this extension _ignores_ this. I guess you should as to the extension developer why. I understand why ignore the _cache_ files, but not `projects.json`. 

Hope this helps

PS: Obrigado 😬

**Comment by rogerlais** [comment]
Thanks !
100% clear and correct.

A Latin replica too
"De nada" 😬
