### ISSUE TITLE
Side Bar should follow `sortList` setting

### ISSUE THREAD

**Issue by pookdeveloper** [alefragnani/vscode-project-manager#366]
Add option to specify the order of the list, if I rewrite the json dosen't work. 
Thanks :)

**Comment by alefragnani** [comment]
Hi @pookdeveloper ,

You can't _specify_ the order the projects appears, but you can choose how the projects are **sorted** and if you would like to **group** them (by its kind). Just use the available settings as described [in README](https://github.com/alefragnani/vscode-project-manager#available-settings).

These settings, on the other hand, are applied only to the `Command Palette`, not the `Side Bar`. 

Hope this helps

**Comment by pookdeveloper** [comment]
Ok thanks, I referer to the sidebar panel.

**Comment by alefragnani** [comment]
I’ll update it to follow the same `sortList` setting.

**Comment by pookdeveloper** [comment]
Perfect @alefragnani thanks for advance! :)

**Comment by tillig** [comment]
This would be super helpful. I have several projects across different orgs and when sorted by name the side bar is really confusing. Hard to tell if it's my fork of a repo or a clone of the org-level repo. A tool tip with the full path of the project might also help in a situation like this; I'll file a separate enhancement.

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/93016677-a14a1180-f5f5-11ea-98f4-55d7dd99f6fb.png)
I would like to take full control of the sort of the projects in sidebar. The same sort as json wound be nice.

I hope a new option can be provided @alefragnani

**Comment by alefragnani** [comment]
@Mister-Hope that's the idea behind _"Saved"_ 😁

**Comment by alefragnani** [comment]
🏃 Sneak peek

![Screen Shot 2021-07-30 at 21 30 14](https://user-images.githubusercontent.com/3781424/127723007-14569b2f-62cb-4168-9eda-79f2289acac3.png)
