### ISSUE TITLE
"projectManager.sortList": "Saved" not implemented

### ISSUE THREAD

**Issue by texastoland** [alefragnani/vscode-project-manager#37]

**Comment by alefragnani** [comment]
Wow, how could I forget that? 😄

**Comment by texastoland** [comment]
How difficult would it be to implement most recently used?

**Comment by alefragnani** [comment]
Not that difficult really :smile: 

But I would store the MRU outside the `projects.json` file. I mean, if you decide to _share_ the projects between Stable and Insider versions, each one would have its own MRU.

What do you think?

**Comment by texastoland** [comment]
That sounds reasonable to me! Thanks it's the only feature I've wished it had 🙌

**Comment by alefragnani** [comment]
Glad to help :+1:

**Comment by alefragnani** [comment]
#38
