### ISSUE TITLE
Opening WSL/WSL2 from local installation (Host) is not working

### ISSUE THREAD

**Issue by alefragnani** [alefragnani/vscode-project-manager#373]
With the release of #345, you are now able to save/open remote projects (Docker and SSH) right from your local installation. 

But it appears, based on reports, that WSL/WSL2 is not working.

This issue is to track specifically the support for WSL/WSL remote projects.

**Comment by Christilut** [comment]
Let me know if you need something tested on Windows 10 with WSL1.

**Comment by Maraat** [comment]
Also if you need something tested on WSL 2 I can try it.

**Comment by alefragnani** [comment]
Just released 11.0.1 yesterday, and based on [this comment](https://github.com/alefragnani/vscode-project-manager/issues/345#issuecomment-631284302) it appears WSL is working.

Could you try it? You just have to **re-save** the projects, to properly update its path.

Thank you

**Comment by Christilut** [comment]
Seems to work! Awesome! 🎉

Thanks for all the effort :)

**Comment by Christilut** [comment]
Few small things I noticed:

It says `Path does not exist` when I select `List projects to open` but doesn't seem to matter.

And when I'm in a WSL project, it shows all projects (including the current) when I select `List projects to open` but when I'm in a normal project, it shows all minus the current.

**Comment by alefragnani** [comment]
@Christilut , That’s great to hear it’s working!

When you say `Path does not exist`, are you talking about the _detail_ below the project name, in `Command Palette`? I now noticed that, at least 😬 .

I could reproduce the _show/not show_ behavior you reported. I’ll open a new issue for that too.

So now, I just need confirmation WSL2 is working too. Let’s hope for the best 😄 

Thank you

**Comment by Christilut** [comment]
Yep in the Command Palette

![image](https://user-images.githubusercontent.com/3471363/82490378-75a19980-9ae3-11ea-94bd-1656d39e8f8f.png)

**Comment by Kirkdeam** [comment]
WSL2 seems to work too, but with the same behavior as Christilut mentioned.

**Comment by alefragnani** [comment]
That’s great to hear!

I’ll open two separate issues, relatives to the scenarios described by @Christilut .

Thank you for reporting
