### ISSUE TITLE
FR: Add commands to project

### ISSUE THREAD

**Issue by gorankav** [alefragnani/vscode-project-manager#374]
Sometimes one needs specific commands for a specific projects like compile, deploy, upload, etc.

Consider having those in the project folder (e.g. code-settings.json)

**Comment by alefragnani** [comment]
Hi @gorankav ,

Thank you for your suggestion, but the idea for the extension is to give you easy/fast access to your projects, not how they work or what they contain. I guess adding template files, or things like this, end up becoming _out of scope_.

I guess, in your case, you should try using _Snippets_ or some other Templating extension would be a better idea.

Hope this helps
