### ISSUE TITLE
VSCode Remote SSH: Path does not exist

### ISSUE THREAD

**Issue by sharksforarms** [alefragnani/vscode-project-manager#375]
My setup:
- VSCode on Windows host setup with VSCode remote
- Ubuntu guest (127.0.0.1) in VirtualBox, with port 2222 open for ssh

Project Manager: 11.0.0
```
[
	{
		"name": "test",
		"rootPath": "vscode-remote://ssh-remote+127.0.0.1/home/sharks/source/test",
		"paths": [],
		"group": "",
		"enabled": true
	}
]
```

VSCode
```
Version: 1.45.1 (user setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

ssh config
```
Host 127.0.0.1
  HostName 127.0.0.1
  User sharks
  Port 2222
```

When clicking on the saved project I get the following message:
![image](https://user-images.githubusercontent.com/10912917/82331254-ddf05e00-99b1-11ea-8da6-41785347f55e.png)

**Comment by alefragnani** [comment]
Hi @sharksforarms ,

I'm guessing this happens for the same reason #377, because other users has reported that SSH was working with the latest release, so I guess they were using MacOS/Linux.

If that's the case, it should be fixed in the next version.

Hope this helps

**Comment by alefragnani** [comment]
Just remember to **re-save** the projects

**Comment by sharksforarms** [comment]
Confirmed working after update to 11.0.1, thanks!

**Comment by alefragnani** [comment]
That’s great! Thanks for reporting...
