### ISSUE TITLE
Support $home variable in `projectsLocation` setting

### ISSUE THREAD

**Issue by pauby** [alefragnani/vscode-project-manager#384]
If you add `$home` to `projectsLocation` Project Manager doesn't pick up the `projects.json` file. If you specify the full path, it does.

This doesn't work:

```
"projectManager.projectsLocation": "$home\\Sync\\Apps\\VSCode",
```

This does:

```
"projectManager.projectsLocation": "C:\\users\\Pauby\\Sync\\Apps\\VSCode",
```

I noticed in the examples that projectLocation has a full path whereas other paths have `$home` so it's not clear if this should work:

![image](https://user-images.githubusercontent.com/12760779/82593135-e86d4c00-9b99-11ea-8fa9-292a667f5db9.png)

**Comment by alefragnani** [comment]
Hi @pauby ,

That’s right. The `projectsLocation` does not support the `$home` variable. The variable was created latter, for _projects auto-detection_ .

But I think that it could be used in `projectsLocation` as well. It’s just a matter of add support :smile:

Thanks for reporting

**Comment by GlenPerkins** [comment]
This is a great extension, but unfortunately it prevents me from using the same VS Code preferences file for every student, one that has a projectLocation in each student's own "~/projects" folder, because "$home" works everywhere EXCEPT projectsLocation. Teaching git in order to use autodetect as a workaround is not really practical for "Day 1" of programming class, so instead each student has to take the generic preferences file and make one edit, inserting his or her acct name into "/Users/<myhome>/projects". It would be great if "$home" (or "~") worked the same way here as it does in the rest of this very nice extension.

**Comment by alefragnani** [comment]
Hi @GlenPerkins , 

Just out of curiosity, why do you need change the `projectLocation` for each student, just to replace to its `$home` folder?

I mean, the initial idea for this setting was mostly for you to _share_ your settings between machines and/or VS Code Stable and Insiders releases. And, unless you _can't use_ the default location (inside VSCode AppData), it's not a setting you need to touch.

Hope this helps

**Comment by GlenPerkins** [comment]
Sorry, yes, I should have included that part. I'm trying to make the projects folder portable and keep it separate from the installed tools. (This is similar to other VS Code issues such as portable installs with global prefs, global installation/sharing of extensions, sharing remotely sync'd settings, etc., where some things are portable, some locked down, some shared, some copied, some separated, etc.)

We have one overall `$home/projects/` folder in each account that holds all of that user's projects, each project in its own sub-folder (subdir). Not all of the projects are VS Code projects. The `$home/projects/projects.json` file stays with the projects folder and tells any VS Code installation which of the included projects to treat as VS Code projects. To move to a different computer (take all of your work home, for example), you can just copy one folder (onto a thumb drive, for example). And you can manage the projects externally--add, delete, rename project subdirs and update `projects.json` immediately with vim or Notepad or whatever.

When VS Code settings are shared or copied or sync'd, having a working `$home` variable is helpful.

**Comment by alefragnani** [comment]
That’s exactly the scenario I was thinking 😁

Please, upvote the issue, so it is easier for me to track the most wanted features.

It appears to be a small change, so it could be released soon.
