### ISSUE TITLE
Include .vsix in Github Release

### ISSUE THREAD

**Issue by cmoog** [alefragnani/vscode-project-manager#385]
Please consider publishing the `.vsix` bundle as a release artifact in this repository rather than exclusively in the Visual Studio Marketplace. This will allow [code-server users](https://github.com/cdr/code-server/issues/1714) to use `vscode-project-manager`.

**Comment by flavio20002** [comment]
Hi, i upvote that. Thanks

**Comment by alefragnani** [comment]
I've just published the latest version (**v11.3.0**) on GitHub releases https://github.com/alefragnani/vscode-project-manager/releases. Starting from now, every new release should be published as well.

Just to be clear, I didn't test the extension on code-server or any other VSCode alternative (VSCodium, Eclipse Theia, etc), so I don't know if/how it will work. I'm not sure how you (code-server) handles extension's compatibility on code-server, but feel free to open new issues, and we could talk about it.

Enjoy
