### ISSUE TITLE
Linux support broken - 0.8.2 can not save projects as well as list saved projects

### ISSUE THREAD

**Issue by gnhuy91** [alefragnani/vscode-project-manager#39]
vscode version: 1.3.1
OS: Ubuntu 14.04

I just updated to 0.8.2 today, all functionalities seem to be broken, keep saying "No project saved yet" even though I had a bunch previously.

**Comment by alefragnani** [comment]
Hi @gnhuy91 ,

Which OS are you using? You could search for `projects.json` file inside your $APPDATA folder, and see where it is stored?

**Comment by gnhuy91** [comment]
Hi, I am on Ubuntu 14.04 LTS.
There is no $APPDATA env on my PC, where should i look for it on a Ubuntu?

**Comment by alefragnani** [comment]
Hi,

In Linux, it should be inside `usr/local` or `usr/local/.config`.

Could you take a look?

**Comment by gnhuy91** [comment]
Found it
```
~/.config/Code/User
[09:12:56] $ ll
.
[drwxrwxr-x huygn    huygn    4.0K May 24 14:53]  snippets/
[drwxr-xr-x huygn    huygn    4.0K Aug  1 15:30]  workspaceStorage/
[-rw-rw-r-- huygn    huygn       8 May 26 11:55]  keybindings.json
[-rw-rw-r-- huygn    huygn       8 May 26 11:55]  launch.json
[-rw-rw-r-- huygn    huygn       8 May 26 11:55]  locale.json
[-rw-rw-r-- huygn    huygn    1.8K Jul 25 10:34]  projects.json  <--
[-rw-rw-r-- huygn    huygn     670 Aug  1 10:06]  settings.json
[-rw-rw-r-- huygn    huygn     126 Aug  1  9:58]  syncSettings.json
```

**Comment by gnhuy91** [comment]
Also I have other PC at home using Windows 10 and the same vscode + vscode-project-manager version, the plugin worked normally.

**Comment by alefragnani** [comment]
Well, I guess I messed up Linux support :cry: 

It will work if you have write access to `/var/local`, otherwise _should_ look for `/home/myuser/.config` (your cenario). 

I should fix it ASAP, so stay tunned.

Thanks for reporting, and sorry about the mess

**Comment by gnhuy91** [comment]
NP, thanks for the quick reply!

**Comment by ClementVidal** [comment]
Same issue with:
- Vscode 1.3.1
- Project manager 0.8.2
- Ubuntu 15.10
