### ISSUE TITLE
Add grouping option to the favorites

### ISSUE THREAD

**Issue by leomeneguzzi** [alefragnani/vscode-project-manager#391]
I will use the `explorer` tab to exemplify my suggestion.

Today favorites look like this:
![image](https://user-images.githubusercontent.com/7086176/85415219-6d55d780-b543-11ea-8af6-39e3e723af98.png)

What I'm purposing is something like:
![image](https://user-images.githubusercontent.com/7086176/85415007-32ec3a80-b543-11ea-9453-f0282c2d370d.png)

My suggestion is not to support folder and subfolders, but a configurable group of favorites. Using my example, these folders can be on any path of my computer, they don't need to be in the same folder. I hope my suggestion makes sense hahaha
If something is not clear enough I will be happy to explain better.

And if this suggestion be accepted, I can solve/implement this issue.

**Comment by alefragnani** [comment]
Hi @leomeneguzzi ,

This is already being tracked in #50.

Thank you.
