### ISSUE TITLE
Weird icon behaviour when no ThemeIcon is selected

### ISSUE THREAD

**Issue by reinhardjung** [alefragnani/vscode-project-manager#392]
Hi

I wounder why my Icons are not the same anymore?

Any Idea why and how I can change them?

![Bildschirmfoto 2020-06-24 um 16 51 16](https://user-images.githubusercontent.com/298616/85579453-306d0c00-b63b-11ea-9b1c-85b0585dba1d.png)

**Comment by alefragnani** [comment]
Hi @reinhardjung ,

That was the _expected behavior_ on the latest release a few days ago. The idea was to use the same folder/workspace icons from Icon Theme you had active. There is no setting to choose the behavior. Is it that bad? :smile:

But, I just noticed a side effect, while revisiting the feature to answer you. If you choose `Icon Theme: None`, the icons disappears, and it wasn’t my intention :sad:. 

I think I’ll rollback this icon feature (at least for the _default folder_ icon), and see a better way while choosing `Icon Theme: None`.

Thanks for reporting.

**Comment by reinhardjung** [comment]
> The idea was to use the same folder/workspace icons from Icon Theme you had active.
Oh, that's what I was wondering. Because my other Icons look-a-like. So, great Idea!

>.Is it that bad? 😄
Well. The "bad" thing about it only that some Icons looking old and some new.
If all Icons would look the Same, then, I don't care.
Not it is looking, that one Project seems to be something special :-(

> I think I’ll rollback this icon feature (at least for the default folder icon), and see a better way while choosing Icon Theme: None.
Hm.
I would be happy if all default folder icons would look the same.
Then it would be very cool, if they look like the Folder Icons in the Theme...but this is a super nice feature (which I love to see ;-))

**Comment by alefragnani** [comment]
HI @reinhardjung ,

> Oh, that's what I was wondering. Because my other Icons look-a-like. So, great Idea!

I’m glad you like the idea. Unfortunately, it didn’t work as expected 😞 .

> Well. The "bad" thing about it only that some Icons looking old and some new.

It will depend (mostly) on your selected Icon theme. The `folder` and `workspace` icons are published, and the extension can override. The `remote` on the other hand, isn’t yet.

 > I would be happy if all default folder icons would look the same.... but this is a super nice feature (which I love to see ;-))

At first, I’ll fix this _no icon_ issue, falling back to default icons if the user selected `None`. And think about a config (maybe opt-out) to return to the previous behavior.

Hope it works as expected 😄
