### ISSUE TITLE
FR: A command to create a new project in a predefined path

### ISSUE THREAD

**Issue by AmrBinBashir** [alefragnani/vscode-project-manager#393]
It would be great to have a command that creates a new folder in a path predefined in the settings, then add this folder to the favorites.

**Comment by alefragnani** [comment]
Hi @AmrBinBashir ,

I’m not sure I understand your idea. Could you describe a bit more?

Thank you

**Comment by AmrBinBashir** [comment]
@alefragnani I have a folder where I keep all of my projects. Some times I need to create a new project, which means I will have to `cd` to that folder, create new folder, open VSCode inside that folder then add that folder to the list of projects in this extension. 
It would be nice to have a command that do all of that:
1. Creates a new folder inside a predefined path. 
2. Opens VSCode inside that path ( a new window or same window).
3. Adds this folder to this extension favorites list.

**Comment by alefragnani** [comment]
You could use _auto-detected_ projects, adding your main folder as `baseFolder` and simply call `Refresh` command to the new folder/project to be available.

It can detect Git, SVN, Hg repos, VSCode and Any (regular) folders. Use `projectManager.xxx.baseFolders` settings.

Hope this helps

**Comment by AmrBinBashir** [comment]
I guess that is good enough.

**Comment by AmrBinBashir** [comment]
I guess that is good enough.
