### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by cadayton** [alefragnani/vscode-project-manager#394]
Might there be a tutorial that shows how to use Project Manager.   This is about the 5th time I've tried using the extension and each time I go down the never ending rabbit hole on making Project Manager become useful tool.  Anyway, life is too short to devote a lot of time to figure this extension out.

**Comment by alefragnani** [comment]
Hi @cadayton ,


What do you miss, in the Readme file, which makes you think the extension needs a tutorial?

I mean, what aren’t you being able/have difficulties to do? Is the extension difficult to use or understand its concepts? Aren’t you being able to save or locate/switch projects?

I’ll be happy to improve the extension for new users. That’s one of the reasons I added a Welcome Message on the Side Bar in recent releases. But to improve the documentation, I need to know what is missing.

Hope this helps

**Comment by cadayton** [comment]
I'm just looking for basic kick start documentation that helps me understand the value of using Project Manager. What I'm wanting to avoid is burning up a weekend of time trying to understand how to use the tool. I guessing there is some real value to using Project Manager.

Like I said in the prior email, I'm hitting a roadblock on understanding the benefits of using Project Manager mainly because I can't seem to get it off the ground running.

I'm not trying to be harsh. Just needing basic guidance about using the extension if it exists.

Craig Dayton
cadayton@protonmail.com
360-466-8778
https://keybase.io/cadayton/chat

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by alefragnani** [comment]
The extension’s idea is to give you quick access for your favorite projects. Projects are the folders, workspaces and remotes that you open in VS Code. 

Whenever you open a folder/workspace that you would like to quickly access again, you just run `Project Manager: Save Project` and give it a custom name (it suggests the folder’s name). Then, when you are using VS Code and would like to return to that _important_ folder, just run `Project Manager: List Projects to Open` and select the previously saved project.

It also support _auto-detected_ projects. Just configure `baseFolders` for Git, SVN, Hg, etc, and it will _discover_ the projects for you. These projects will also be available in the `Project Manager: List Projects to Open` command.

And to make user’s live easier, It has a Side Bar, which shows all your projects.

I guess this sums up the extension’s idea, and how it works 😬 

Hope this helps

**Comment by alefragnani** [comment]
Reviewing this request, I understand that the Walkthrough support that was introduced in v12.8 is enough.

To access it, if it is not displayed in the Welcome Page of the VS Code, simply run `Welcome: Open Walkthrough` and select `Get Started with Project Manager`.

Hope this helps
