### ISSUE TITLE
Sidebar icon not visible

### ISSUE THREAD

**Issue by shashankv02** [alefragnani/vscode-project-manager#395]
This is a great extension which I believe should have been available in vscode by default. Been using it for more than a year and all of a sudden the sidebar icon disappeared recently. Tried re-installing the extension but the sidebar icon is gone. 

VSCode Version:

```
Version: 1.47.0
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:01:54.115Z (1 day ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

**Comment by shashankv02** [comment]
It somehow moved within "Source Control" tab. I right clicked on it and selected "Reset location" and then the dedicated project manager icon appeared.

**Comment by alefragnani** [comment]
Hi @shashankv02 ,

First of all, thank you for you kind words 😁. 

It was probably a unintended _drag and drop_ of the Side Bar, and you did right using the `Reset` command. I had the same issue when playing with the new _drag and drop_ feature, while still in beta.

Good to know it worked.
