### ISSUE TITLE
Git projects are not auto-detected

### ISSUE THREAD

**Issue by theAkito** [alefragnani/vscode-project-manager#397]
I have adjusted the `settings.json`, I have tried different base folders, I increased the max depth for Git project searches -- still, to no avail. No Git projects at all are found.

Am I missing something?

P.S.: Extension runs within WSL2.

**Comment by alefragnani** [comment]
Hi @theAkito ,

If you are running within WSL2 and your Git repos are inside that remote, you should activate/install the extension to work on remotes: 

First, you need to tell VS Code that the extension will work on remotes:

```
"remote.extensionKind": {
        "alefragnani.project-manager": [
            "workspace"
        ],
```

I don't remember how that works on WSL, but if you were using Docker, you should update `.devcontainer.json` adding to install the extension on that container.

Hope this helps

**Comment by theAkito** [comment]
@alefragnani 

Thanks for the quick help. Indeed, your suggestion seems to make it work. Is there any documentation on this? Did not find info on this when skimming the How To for this extension. Additionally, I find the words "workspace" and "ui" a little confusing in this context.
Nevertheless, your solution works. Thank you.

**Comment by alefragnani** [comment]
That's great to see it worked 👏

No, there is no extra documentation on how the extension works for remotes, but maybe I could add that in the future. I don't use remotes that much (only a bit of Docker), so it's a new scenario for me. 

To bring remote support for the extension, I had to chat with users, and learned a lot. You can see it in #284, #318, #323 and #373.

Indeed, `workspace` and `ui` may be a bit confusing, but it's a VS Code concept/setting, not from the extension.

Enjoy the extension. Feel free to open issues if you miss something.
