### ISSUE TITLE
I can't figure out how to run it

### ISSUE THREAD

**Issue by hubad** [alefragnani/vscode-project-manager#398]
Hello!
I can't figure out how to run it
project manager vscode,
I read several instructions, reinstalled, but did not understand where my problem is
(well, except for the head :) )
—
here is removed minute screen video, that there is no so do?
For quality, you need to download.
https://cloud.mail.ru/public/2ihB/4y6Vgf6N2

**Comment by alefragnani** [comment]
Hi @hubad ,

Maybe you are having the same difficulty as #394 , so I suggest you take a look at the [comment](https://github.com/alefragnani/vscode-project-manager/issues/394#issuecomment-650466314) I that I added. It gives you a quick view of extension’s idea.

Hope this helps

**Comment by hubad** [comment]
all Read.
"Project Manager: List Projects to Open"
it does not open the project, but when you click on the pencil (previously this was not the case), it began to open this window https://cloud.mail.ru/public/2UDp/3BVGs56An

**Comment by alefragnani** [comment]
I'm not sure why I can't see the image you linked. Could you please upload it on GitHub?

If what you see is an empty `projects.json` file, then you must save the project, using `Save Project` command, and name the project, prior to call `Load Projects to Open`.
