### ISSUE TITLE
Display git projects as org/name or user/name

### ISSUE THREAD

**Issue by 111pontes** [alefragnani/vscode-project-manager#402]
Didn't see an option to display the user/org qualification of a repo.  It'd make it very easy to identify forks and upstream repos.

**Comment by alefragnani** [comment]
Hi @111pontes ,

No, there is no option/setting to display such information. In fact, there is no _git check/validation_ while detecting Git repos. It just checks for _file structure_ that a Git repo has.

How do you expect/imagine this info could be displayed, and where (Side Bar and/or Command Palette)?

Could you provide more info/mockups/prints?

Thank you

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been made since my last question. 
Feel free to reopen/comment if the error still occurs.
