### ISSUE TITLE
Display Project Title in Title Bar of VSCode?

### ISSUE THREAD

**Issue by eddieparker** [alefragnani/vscode-project-manager#405]
Apologies if this is already a feature or a feature request but I didn't see anything like it.

I'd love to be able to have the project name in the title bar of VSCode.  Right now the VSCode title bar just says "Untitled (Workspace) - Visual Studio Code" but I'd rather have it have my project manage name up there so I can at a glance see which window I'm in.

**Comment by alefragnani** [comment]
Hi @eddieparker ,

No need to be sorry 👍 

This has already been requested a few times, as you can see in #98, #272 and #342, and I've requested VS Code team to support that, as you can see in https://github.com/microsoft/vscode/issues/22037, but unfortunately the issue didn't receive enought upvotes (from other extension developers and users) to be part of their backlog. So, it ended up being closed.

Hope this helps
