### ISSUE TITLE
Git - No projects detected

### ISSUE THREAD

**Issue by danlance** [alefragnani/vscode-project-manager#408]
I may be missing something basic here... but can't for the life of me see what...

When I go to the GIT section within Project Manager, I see the message:

> No projects detected
> 
> In order to detect GIT projects, you have to configure the 'baseFolders' where the Git projects are.

Followed by buttons for Open Settings / I don't need Git projects.

I have the following `projectManager` settings within my settings.json:

```
    "projectManager.git.baseFolders": [
        "~/sites"
    ],
    "projectManager.git.maxDepthRecursion": 5,
```

... but never see any Git projects auto detected, despite having dozens of Git repos within subfolders of ~/sites

I'm running on Mac OS Catalina.

Any ideas?

**Comment by alefragnani** [comment]
Hi @danlance ,

The extension supports for HOME folder, but instead of using _tilde_ symbol, I created the `$home` variable.

From the README file:

> Use a special variable called `$home` while defining any path. It will be replaced by the HOME folder.

Just update your path and your repos should appear.

Hope this helps

**Comment by danlance** [comment]
Thanks - that works 👍
