### ISSUE TITLE
Ability to specify remote project directory path in host settings

### ISSUE THREAD

**Issue by tvvignesh** [alefragnani/vscode-project-manager#409]
Hi. I have been using Project Manager extension for a long time now and its amazing. And recently, I started trying it out for Remote SSH as well, but had a suggestion.

Project Manager currently maintains a separate settings context in the remote VM which is great but I would like to specify `projectManager.git.baseFolders` for the remote in my host machine itself so that I don't have to specify it again even if I destroy the VM and re-create it (in such cases, the base folder setting will be lost since its in the VM). 

Since I run my VM with Vagrant and I destroy VMs sometimes, I would have to configure project manager every time I do this. Also wondering if something similar is possible for other extensions as well.

Hope this makes sense. Thanks.

**Comment by alefragnani** [comment]
Hi @tvvignesh ,

First of all, thank you for your kind words. I'm glad to know you like the extension.

About your scenario, I'm sorry to say, but it is not possible today. To be able to have access to Git repos inside the remote, the extension needs to be installed there, and the settings aren't shared between the host and the remote. This is a VS Code limitation.

I don't use **SSH** so I don't know if you have the chance to provide additional setting to VS Code. Using **Docker** I can define settings in `devcontainer.json` file, so I _could_ define the `git.baseFolders` there.

Hope this helps

**Comment by tvvignesh** [comment]
@alefragnani Thanks for your quick reply. I am running on containers but within the VM created by vagrant. So, if I destroy the VM, even if I have a devcontainer file with settings, that will also probably be gone since its in the VM.

Anyways, I hope someday this would be possible or atleast we will get the ability to mount the settings from the host to the machine rather than doing it ourselves. You can close this issue if you want. Thanks again.

**Comment by alefragnani** [comment]
@tvvignesh looking at VS Code documentation about Remotes/SSH (https://code.visualstudio.com/docs/remote/ssh) I just find out that _it should share the settings_ (https://code.visualstudio.com/docs/remote/ssh#_ssh-hostspecific-settings). Also, it appears you can say which extensions should be _always installed_ (https://code.visualstudio.com/docs/remote/ssh#_always-installed-extensions). It appears it already support what you need 🤔.  

I think you could take a closer look at this docs for info. If it doesn't work as it says, open an issue in VS Code repo. The VS Code team is eager in make Remote works the best way possible.

Hope this helps

**Comment by tvvignesh** [comment]
@alefragnani Hi. Just thought of updating this issue. I did try opting for the `devcontainer.json` approach like you suggested, but was not able to move forward due to this: https://github.com/microsoft/vscode-remote-release/issues/2994

You can close this issue. I don't think, there is much we can do now.

**Comment by alefragnani** [comment]
Hi @tvvignesh ,

I'm sorry to know it didn't worked out for you. But I think this _will_ be achieved somehow by VS Code team in the future. I don't use remotes that much, but if I wonder an alternative in the future, I'll post some update here.

That's great to hear you did like the **Favorites** projects. This was the extension's original idea (the auto-detection came latter), and it's still my main usage, specially for Workspaces and Remotes.

Feel free to open/reopen the issue if you have any update from the VS Code team.

Thank you
