### ISSUE TITLE
New command "Load"?!

### ISSUE THREAD

**Issue by Egahras** [alefragnani/vscode-project-manager#41]
Hey there, nice extension, i realy like it and use it much.
But thats my problem, i got so many projects thats it not easy to find the specific one on the first sight.

How about a new command like "Load" where you can type the first few letters, and the list is just showing Projects where the name starts with or contain  "xyz"?

No need for seperate command list with the optional parameter "ProjectName contains $string" would be okay, too =)

what do you think about this?

**Comment by alefragnani** [comment]
Thanks, glad to help 😄 

Unfortunatelly there is no API to _customize_ how the list is filtered. It's built in VSCode and works the same way for every list presented. Sorry.

Maybe with this [enhancement](https://github.com/alefragnani/vscode-project-manager/issues/38) it should be faster for you to navigate between you projects. At least if your intention is return to previous ones.

What do you think?
