### ISSUE TITLE
grouping repos by path

### ISSUE THREAD

**Issue by cmeissner** [alefragnani/vscode-project-manager#417]
I have several github repos on my machine. I'm working with my personal account and organization accounts as well. In both are repositories with the same name. If i configure `Git: base folder` as followed:

```
$home/Development/cmeissner
$home/Development/codeaffen
```

I get the following list

![image](https://user-images.githubusercontent.com/14936920/91737162-fece6f00-ebae-11ea-9d80-bc4b79ed0f13.png)

The repository `phpipam-ansible-modules` exists in both directories. Here I can only distinguish repos by waiting for hover text, which is a bit inconvenient. Here would be a option useful to group repositories.

**Comment by alefragnani** [comment]
Hi @cmeissner ,

I think there are two issues which are similar to your request, with two different approaches:

* #50 - similar to a _group concept_, where you could assign groups to projects, and see them organised in the Side Bar/Command Palette.
* #306 - solves the _same-name conflict issue_, which I will add the base folder as a detail on each project (take a look at the print I added).

Please, feel free to upvote the one which better fit your needs. My idea is to bring at least one of them soon.

Stay tuned
