### ISSUE TITLE
Saving new project does not save label

### ISSUE THREAD

**Issue by ferrantejake** [alefragnani/vscode-project-manager#42]
Saving a new project in v0.8.3, the label field is not populated in the newly created entry.

**Comment by alefragnani** [comment]
Hi @ferrantejake ,

Which OS are you using? And wich VSCode release (stable or insider)?

Also, is this your first project to be saved, or do you have others? And does it shows the _Project saved!_ message when you have a new project?

**Comment by ferrantejake** [comment]
I am using Windows 10 Anniversary with the Insider edition of VS Code.

This happens when I create any new project. I noticed when my projects listing was empty and I started re-creating all of my projects again and the manager wasn't able to create new ones with a different label, only replace the one with an empty string as a label.

Yes, I get a _Project Saved!_ notification when I go to save a new project.

**Comment by alefragnani** [comment]
Do you have _Stable_ and _Insider_ versions installed?

 In 0.8.2 release I made the _Insider_ version has its own `projects.json` file and so, in order to keep sharing the projects between _Stable_ and _Insider_ you should redirect the _Insider_, configuring `projectManager.projectsLocation` to the _Stable_ location. 

This is also true if you only have the _Insider_ version installed.

Take a look at the updated Readme file for more info

Hope this helps

**Comment by roblourens** [comment]
Same here, only in Insider build. I was looking at it and filed this bug on vscode - Microsoft/vscode/issues/11503

**Comment by ferrantejake** [comment]
I have both _Stable_ (VSCode) and _Insider_ (VSCode Insider Edition) installed on my machine.
The concern isn't with the sharing of projects between editors - but with the label of the project not being populated when creating a new project

**Comment by alefragnani** [comment]
I could reproduce the problem in _Insider_ release, just like @roblourens commented.

@ferrantejake do you confirm the issue only occurs in _Insider_ release? If yes, I will release a patch to fix this.

**Comment by ferrantejake** [comment]
Yes, I can confirm this issue only appears in the _Insider_ edition. Thanks for looking into this 👍

**Comment by alefragnani** [comment]
Great! Stay tuned for a patch later today :+1:

**Comment by alefragnani** [comment]
I just released a fix for the issue. Let me know if its working for you guys.
