### ISSUE TITLE
[BUG] - Latest VSCode Insiders seems to break Project Manager extension

### ISSUE THREAD

**Issue by vladmandic** [alefragnani/vscode-project-manager#423]
VSCode Insiders just got auto-updated to latest version and Project Manager is still present, but cannot load list of projects anymore - it's blank, just like on first startup.  
Clicking edit icon actually opens list of projects, so they are not gone, just couldn't be parsed anymore.

Error message visible in VSCode is:  

```text
[alefragnani.project-manager]: Proposed API is only available when running out of dev or with the following command line switch: --enable-proposed-api alefragnani.project-manager
```

VSCode Version: `1.50.0-insider (user setup)` commit: `bc38b0accb3c62180317c63dbe7323200977db0f` Date: `2020-09-11T12:48:20.764Z`

**Comment by alefragnani** [comment]
Hi @vladmandic ,

That's really weird, because the extension doesn't use any _Proposed API_ 

But based on this report https://github.com/microsoft/vscode/issues/106499 in VS Code repo, It appears a VS Code issue.

Let's hope VS Code team releases an update ASAP.

Thanks for reporting

**Comment by vladmandic** [comment]
Just noticed that one as well.
Suggestion to keep this issue open just for tracking and close it with note on VSCode version that fixes it.

**Comment by alefragnani** [comment]
Exactly 👍

**Comment by vladmandic** [comment]
That didn't take long - latest VSCode works fine!

```text
Version: 1.50.0-insider (user setup)
Commit: cca20eba8974b1d6b6a9b71bf4e60a29c8f26648
Date: 2020-09-12T01:04:21.398Z
```
