### ISSUE TITLE
[FEATURE] - Allow specifying environment variables for project entries

### ISSUE THREAD

**Issue by koliyo** [alefragnani/vscode-project-manager#426]
It would be useful to have environment variables defined for the local machine available in the VS Code project. Eg when building C# projects I might have a declaration such as

```
    <ProjectReference Include="$(BAMSE_DIR)/cs/Bamse.csproj"/>
```
And when I build from command line I set the environment variable and it builds correctly. But Omnisharp does not load properly because it does not have this environment variable.

So it would be very convenient if project manager could inject environment variables when opening a project. And these could then be specified in the project configuration file.

**Comment by alefragnani** [comment]
Hi @koliyo ,

At first look, it appears a bit _ouf of scope_ for the extension, which the idea is to give you quick access to your projects, not necessarily _handle/configure/inject_ resources in it. 

The extension doesn't know anything about the kind of project you have, or its contents. It also doesn't know if the project (folder/workspace) was opened by the extension, or if you used `File / Open` commands, in VS Code. It only know its _location_.

How do you think this _variables_ could be stored in the extension, for each project. In `projects.json` file? What about _auto-detected projects_ like Git, SVN, Hg, etc?

Thank you

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been made since my last question. 
Feel free to reopen/comment if the error still occurs.
