### ISSUE TITLE
[QUESTION] - Why does a whitespace break the search query? 

### ISSUE THREAD

**Issue by xh3b4sd** [alefragnani/vscode-project-manager#428]
Fuzzy search in vsCode is usually tolerant about whitespaces. I can get the project manager settings with or without whitespace in the search query. This is expected and I like it. It is useful. 

<img width="623" alt="Screenshot 2020-09-28 at 11 09 40" src="https://user-images.githubusercontent.com/552769/94413403-5397e200-017b-11eb-80a4-aca5058e6bfa.png">

<img width="623" alt="Screenshot 2020-09-28 at 11 09 47" src="https://user-images.githubusercontent.com/552769/94413405-5561a580-017b-11eb-9f73-c337a6f08ae9.png">

Searching for projects implements a different behaviour. As soon as the search query has a whitespace in it I do not find my projects anymore. This behaviour is consistent and is not bound to special characters like `-` within the project name. This behaviour is unfortunate and I think it makes sense to align with the general fuzzy search behaviour of vsCode. 

<img width="623" alt="Screenshot 2020-09-28 at 11 09 58" src="https://user-images.githubusercontent.com/552769/94413409-5692d280-017b-11eb-9f8b-92df4e4468ce.png">

<img width="623" alt="Screenshot 2020-09-28 at 11 10 03" src="https://user-images.githubusercontent.com/552769/94413411-572b6900-017b-11eb-8a16-8d49a011e113.png">

We could argue this is a bug report or feature request. I do not know. I wanted to ask about the intention of the implementation so far and if I maybe do something wrong. How is this meant to be? What do people think how this should work? Love project manager. ❤️

**Comment by alefragnani** [comment]
HI @xh3b4sd ,

Thank you for your kind words. I'm glad to know you like it 👍 

About searching, unfortunately I have no control. It's entirely handled by VS Code itself within its APIs. Not only filtering but also sorting.

Right now there are at least two open issues in VS Code to handle searching/filtering (https://github.com/microsoft/vscode/issues/14727 and https://github.com/microsoft/vscode/issues/34088). I suggest you to upvote there, to give more visibility to the VS Code team. 

Hope this helps
