### ISSUE TITLE
[FEATURE] - When searching for a project, still use the `projectManager.sortList` setting for sorting

### ISSUE THREAD

**Issue by dannyharding10** [alefragnani/vscode-project-manager#436]
The `sortList` setting is awesome! I personally love sorting by `Recent`. However, when I begin typing into the search field, the list reverts to being sorted by `Name`. I would love it if the list maintained its sort order when filtered as well.

I can see that this might be a preference that some may not want, so putting it behind another setting would work as well. Something like `projectManager.useSortListSettingDuringSearch`. This setting could even be its own option, allowing for any of `Saved`, `Name`, `Path`, `Recent`, or `SortListSetting`, the latter meaning it would use the value of the `sortList` setting.

**Unfiltered, sorted by Recent**
![image](https://user-images.githubusercontent.com/11875246/98864782-0b353a80-2430-11eb-8ca6-45ebefd90281.png)

**Filtered, now sorted by Name :(**
![image](https://user-images.githubusercontent.com/11875246/98864879-29029f80-2430-11eb-927a-a8025be55464.png)

**Comment by alefragnani** [comment]
Hi @dannyharding10 ,

Similar requests has already been made over the years (#92 , #254 , #66), but unfortunately I don’t have control over filtering and subsequent sorting. VS Code doesn’t provide any API that would allow me to change how it filters, and the filtered result ignores the original custom sorting.

I didn’t noticed any recent update on the VS Code issues, so I guess this won’t change in the near future. I’m subscribed to those issues, so if/when it arrives, I’ll be notified.

Hope this helps
