### ISSUE TITLE
[BUG] - Misspelling word Curren in Project Manager UI settings

### ISSUE THREAD

**Issue by solairen** [alefragnani/vscode-project-manager#442]
Hi, 
I found a very small issue in configuration section ;)

**Environment/version**
- Extension version: 12.0.0
- VSCode version:  1.51.1
- OS version: Windows 10 Pro 19042.630

**Steps to reproduce**
1. Open VSCode
2. Press F1 and type  and select **"settings (Open Settings (UI))"**
3. In **settings search** type: **"projectManager"**
4. Search **Project Manager: Open in Curren Window if Empty**

**Actual behaviour**
Misspelling **Curren**

![image](https://user-images.githubusercontent.com/45487024/100089997-d58e4980-2e52-11eb-9690-184bd6f64793.png)

**Expected behaviour**
Should be **Current**

**Comment by alefragnani** [comment]
Hi @solairen ,

Thanks for reporting! Unfortunately, for me, this is not _small_ at all 😢 . 

This entry is not _just a resource_ (like the message below) but the _setting_. VS Code generates this "user friendly" text  based on the setting name `projectManager.openInCurrenWindowIfEmpty`. So, if I fix the misspelled word, I must migrate the setting.

Well, I guess I already saw some extensions doing the same. Just have to make some research 😁 

Thank you
