### ISSUE TITLE
[BUG] - projectManager.groupList not working

### ISSUE THREAD

**Issue by Tzaphkiel** [alefragnani/vscode-project-manager#444]
**Windows 10**

- Extension version: 0.160
- VSCode version:1.51.0
- OS version: win10

**Steps to reproduce**
Configure projects with Group set and activate the option:
`"projectManager.groupList": true`
```json
[
	{
		"name": "hbase-scripts",
		"rootPath": "d:\\dev\\hbase-scripts",
		"paths": [],
		"group": "DDP",
		"enabled": true
	},
	{
		"name": "ddp-ops",
		"rootPath": "d:\\dev\\ddp-ops",
		"paths": [],
		"group": "PERSO",
		"enabled": true
	},
	{
		"name": "kafka-scripts",
		"rootPath": "d:\\dev\\kafka-scripts",
		"paths": [],
		"group": "DDP",
		"enabled": true
	}
]
``` 

![Screenshot 2020-12-15 112641](https://user-images.githubusercontent.com/644489/102203103-7313f080-3ec8-11eb-8947-5e05070173e5.png)

**Comment by alefragnani** [comment]
Hi @Tzaphkiel ,

The `groupList` setting is not meant to be used by the Side Bar, because in fact, each _kind_ of project is presented in its own Panel/Treeview. This setting is exclusive to the `Command Palette`.

On the other hand, if you wanna talk about the `sortList` setting, there is already an open issue to track this (#366).

Hope this helps

**Comment by muoto** [comment]
Would be nice if items would be organized by groups.  I intuitively thought that is how the group list featured worked.  Also be very nice if you can control the ORDER of the project by editing the settings.json

**Comment by alefragnani** [comment]
Hi @muoto ,

Maybe the _group_ you are referring to is what #50 asks. The ability to define groups/tags/labels for projects and see them organized by the groups/tags/labels.

About the _sort_, if you choose `Saved` for `sortList`, it will respect the order you saved the projects, which are stored in `projects.json`. You can edit the order using `Project Manager: Edit Projects` command. But, as I commented above, _the Side Bar does not follow the setting, yet_. It's being tracked in #366.

Hope this helps
