### ISSUE TITLE
[BUG] - The Open Folder command does not work.

### ISSUE THREAD

**Issue by PANERO72** [alefragnani/vscode-project-manager#455]
**Environment/version**

- Extension version: 12.0.1
- VSCode version: 1.52.1
- OS version: 

**Steps to reproduce**

1. 
2.

**Comment by alefragnani** [comment]
Hi @PANERO72 ,

Which `Open Folder` command are you referring to, and what do you mean by "does not work"?

Could you provider more details?

Thank you

**Comment by PANERO72** [comment]
Helo @ alefragnani. Here I show a snapshot, it is the button "Open a Folder" in the extension.  I don't have any projects or folders open in VSCode and when I click the button nothing happens. Thank you.<br />
![iusse](https://user-images.githubusercontent.com/21048181/103913672-1abbc180-5109-11eb-9a9a-aff40b9eeb40.png)

**Comment by alefragnani** [comment]
Hi @PANERO72 ,

Which OS are you using? I have access to MacOS and Windows, and both seems to work.

BTW, is the `Open a Workspace` button working?

Thank you

**Comment by PANERO72** [comment]
Hi. I am using Windows 8.1.

The Open a Workspace button does work.

Thank you

**Comment by alefragnani** [comment]
That’s weird 😕 

In Windows, this button is just a shortcut for the native `openFolder` command, the same you see in `File / Open Folder` menu. 

Could you try to use the `File / Open Folder..` menu in VS Code. Does it work?

BTW, you don’t need that button to use the extension. As I said, it’s just a shortcut. You can open any folder/workspace (using regular options) and call `Project Manager: Save Project`, to save. 

Thank you

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if the error still occurs.

Thanks for your understanding
