### ISSUE TITLE
Open VSX Registry: Awareness and Important Steps

### ISSUE THREAD

**Issue by brianking** [alefragnani/vscode-project-manager#458]
@PhilippeVay has published this extension in the [Open VSX Registry](https://open-vsx.org/extension/alefragnani/project-manager).

The service was recently transferred to the Eclipse Foundation and we want to ensure a seamless transition for our users. To ensure uninterrupted service and more exposure for your extension, I recommend the following.

**To the maintainers**: If you would like to take over publishing to open-vsx.org, here’s how: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**To the current publisher**: Please sign the [Eclipse Publisher Agreement](https://www.eclipse.org/legal/documents/eclipse-openvsx-publisher-agreement.pdf). The signing process is [explained in the Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) (steps 1 and 2).

**Claiming ownership of the namespace for your extension(s)**. To find out how to do this, see:
https://github.com/eclipse/openvsx/wiki/Namespace-Access
As owner you can add more namespace members (including service accounts) yourself in https://open-vsx.org/user-settings/namespaces. Note that publishing can be done by any contributor to the extension, namely those you add as namespace members once they have signed the Publisher Agreement as well.

Please also note that a license is now mandatory for publishing your extension to Open VSX. If your project doesn't have any license, please add one, preferably an [open source license](https://opensource.org/licenses) such as MIT. The publishing tool [ovsx](https://www.npmjs.com/package/ovsx) offers to automatically add the MIT license when you try to publish without a license.

Useful links:
[Eclipse Publisher Agreement](https://www.eclipse.org/legal/documents/eclipse-openvsx-publisher-agreement.pdf)
[Eclipse Foundation Open VSX Registry Frequently Asked Questions (FAQ)](https://www.eclipse.org/legal/open-vsx-registry-faq/) 

More details are in these recent blog posts:
https://blogs.eclipse.org/post/brian-king/open-vsx-registry-under-new-management
https://blogs.eclipse.org/post/brian-king/new-era-open-vsx-registry

Today, there’s growing momentum around open source tools and technologies that support Visual Studio (VS) Code extensions. Leading global organizations are adopting these tools and technologies. This momentum has spurred demand for a marketplace without restrictions and limitations. We hope you join us on this journey as we continue to build the Open VSX community. 
We look forward to continued innovation from you in 2021!

**Comment by coxackie** [comment]
@brianking I cannot actually find this in the Open VSX Registry. Was it taken down?

**Comment by brianking** [comment]
@coxackie Yes, the cut-off was January 29th. However, it can reactivated if someone with namespace access, who also signs the publisher agreement, publishes a new version of the extension.

**Comment by mclang** [comment]
Is this still maintained @alefragnani - or why the signing hasn't been done?

**Comment by bburch1985** [comment]
Please activate for Open VSX, now under Eclipse, I would love to have this extension for VS Codium!

Thanks!

**Comment by fkumro** [comment]
Any progress on making this available on VSX?

**Comment by alefragnani** [comment]
It's planned for my vacations in January 😬

**Comment by benz0li** [comment]
@alefragnani Any update on this topic?

I hope you had relaxing holidays. 🌴

**Comment by alefragnani** [comment]
Hi @benz0li ,

Yes, it was relaxing, thanks 😄 

I could finally play with Gitpod, and had a really good experience. I'm pretty sure I'll use/enable it for upcoming projects. 

I still have some priority projects to take care of, but yes, the extension will be available in open-vsx soon.

Stay tuned

**Comment by filiptronicek** [comment]
I just removed the two extensions from https://github.com/open-vsx/publish-extensions (https://github.com/open-vsx/publish-extensions/commit/d16ee8c2afbf9881549f5f9aa071f52850dd39a0). This is both because it seems that @alefragnani is going to publish the extensions soon himself and because we couldn't get the source code anyway from the private repos.
Are you planning to publish the Bookmarks extension as well, @alefragnani?

P.S. Please do feel free to ask any questions about the publishing to OpenVSX / OpenVSX itself. I would love to get the extensions published, they're one of the biggest ones we still don't have 😄.

**Comment by benz0li** [comment]
> I could finally play with Gitpod, and had a really good experience.

@alefragnani You may also try https://vscode-r.jupyter.b-data.ch: A JupyterHub spawning JupyterLab images including [code-server](https://github.com/coder/code-server).  
ℹ️ Based on [debian:bullseye](https://hub.docker.com/_/debian) with many packages (esp. `git`, `git-lfs`, `gnupg`, `jq`, `node`, `yarn`, etc.) and some extensions already pre-installed.

**Comment by benz0li** [comment]
@alefragnani Any news about publishing this extensions on OpenVSX?

**Comment by benz0li** [comment]
@alefragnani Any news about publishing this extensions on OpenVSX?

**Comment by benz0li** [comment]
@filiptronicek Could you tackle this issue together with @alefragnani? Thank you.

It would be great to have this extension published by the owner in the [Open VSX Registry](https://open-vsx.org/extension/alefragnani/project-manager).

**Comment by alefragnani** [comment]
Hi @benz0li ,

First of all, thank you for your support!

After a few delays, I'm finally able to return to this. The plans are to release it in the next milestones, and yes, the idea is publish all of my extensions at open-vsx.

I hope to be a smooth experience, so everyone could enjoy it.

Thank you

**Comment by benz0li** [comment]
@alefragnani Any news about publishing this extensions on OpenVSX?

**Comment by alefragnani** [comment]
Hi @benz0li ,

I'm planning this for the next release, which should be out in the next couple of weeks. 

So, stay tuned 😬

**Comment by benz0li** [comment]
> I'm planning this for the next release, which should be out in the next couple of weeks.

@alefragnani What is the timeframe for the [February 2023 Milestone](https://github.com/alefragnani/vscode-project-manager/milestone/56)?

**Comment by waylonwang** [comment]
The version of open-vsx is 12.0.1, while that of vscode is 12.7.0. Only the latest version supports tags. Can you update open-vsx to the latest version?

**Comment by benz0li** [comment]
@alefragnani Please make the next release also available in the [Open VSX Registry](https://open-vsx.org/extension/alefragnani/project-manager).

Thank you.

**Comment by benz0li** [comment]
Happy new year!

@alefragnani Any news about publishing this extensions on OpenVSX?

**Comment by alefragnani** [comment]
@benz0li  Happy new year!

Yes, I’m planning the next release to the second half of February 🤞 . 

I noticed a few recent changes in the open-vsx governance, but the publishing and claiming ownership process seems to be the same. I hope to be a straightforward process.

BTW, out of curiosity,, which VS Code _alternative_ are you most interested to use with open-vsx? Desktop apps like VSCodium or online/remote solutions like Gitpod? I’m asking because specifically Project Manager, Bookmarks and Numbered Bookmarks extensions weren’t ported to vscode.dev (the web based) yet, even published in open-vsx, it shouldn’t work on this platform.

PS. I’m sorry for taking so long, and thank you all for your patience.

Thank you!

**Comment by benz0li** [comment]
@alefragnani Any news about publishing this extensions on OpenVSX?

**Comment by alefragnani** [comment]
Hi @benz0li ,

It's almost there. I just claimed the namespace https://github.com/EclipseFdn/open-vsx.org/issues/2445, and once accepted, I should publish all my extensions in the next day.

BTW, I'm not just planning to publish the extension on open-vsx, but publish its [new milestone](https://github.com/alefragnani/vscode-project-manager/milestone/56?closed=1).

Stay tuned

**Comment by alefragnani** [comment]
Hi,

I just published the new [release 12.8.0.](https://github.com/alefragnani/vscode-project-manager/milestone/56?closed=1) to Open VSX.  Let me know how if you have any issues.

Thank you for your patience.
