### ISSUE TITLE
Do not show welcome message if installed by Settings Sync feature of VS Code

### ISSUE THREAD

**Issue by sandy081** [alefragnani/vscode-project-manager#459]
Hi, I am developer of VS Code and I am currently going through those extensions which has custom welcome experience (notifications / pages) on install. VS Code provides Settings Sync feature OOB and users can have their machines in sync using this feature. So, when user sync such extensions with custom welcome experience, they should not be seeing welcome experience again in their other machines. To enable this we recently added an [API](https://code.visualstudio.com/updates/v1_51#_sync-global-state) - https://github.com/microsoft/vscode/issues/95209#issuecomment-717377926 for extensions to sync their global state when Settings Sync is enabled. It seems this extension is having custom welcome experience and not yet syncing their global state so that users won't see welcome notifications/pages when syncing extensions. 

Hence filing this issue for this extension to adopt above API and make sure welcome experience is not repeated to users on syncing. 

Here are the steps you can follow to make sure your extension is not showing welcome experience on sync:

- Machine 1 - Turn on Settings Sync feature in VS Code
- Machine 1 - Install alefragnani.project-manager - Shows welcome (**What's New in Project Manager**) page ✅ 

<img width="1353" alt="image" src="https://user-images.githubusercontent.com/10746682/105386463-b45c9600-5c14-11eb-9ce2-8276f1063893.png">

- Machine 2 - Turn on Settings Sync - this installs alefragnani.project-manager extension
🐛 Shows welcome page again

**Comment by sandy081** [comment]
Created PR - https://github.com/alefragnani/vscode-whats-new/pull/24 to fix this.

**Comment by sandy081** [comment]
@alefragnani I just tested and it seems the above fix is not working with Project manager extension but works with Bookmarks extension. May I know if the latest version of the extension includes the fix?

**Comment by alefragnani** [comment]
Hi @sandy081 ,

Yes, it was already merged, but I didn’t published yet. I’m preparing the latest feature and my intention it to have it published next week

BTW, I’m planning apply the same feature all over my extensions 😬 

Thank you

**Comment by sandy081** [comment]
Thanks @alefragnani 

Let me know if you have any questions while adopting.
