### ISSUE TITLE
Support multiple folders in the same project

### ISSUE THREAD

**Issue by alefragnani** [alefragnani/vscode-project-manager#46]
Depends on:
- [ ] https://github.com/Microsoft/vscode/issues/396
- [x]  :running_man: #47

**Comment by alefragnani** [comment]
Depends on:

- [ ] https://github.com/Microsoft/vscode/issues/396
- [ ]  :running_man: #47

**Comment by bryaan** [comment]
Can we have it mock with symlinks for now?  Could do it by hand but I think it makes sense for this project.

**Comment by Anthropic** [comment]
@alefragnani is there any way you could open new windows for each folder defined in paths?

**Comment by alefragnani** [comment]
Sure it could :smile:. But that is not the intention for this issue. I filled just to remember myself to update (if necessary) when VSCode itself support multi folder projects.

But I get your idea . It's interesting :+1:

**Comment by alefragnani** [comment]
The multi-folder is coming to VSCode (is already in the current Insiders), and it uses a _peculiar_ approach, putting the multi-folder info inside `settings.json`.  Doing so, there is nothing to be done _(adapted)_ in the extension, which is good 😄 .

**Comment by gjuchault** [comment]
@alefragnani Can you explain how we can add multiple directories ?

Current use case (not working):
1. Open a folder
2. Right click on sidebar, « Add Folder to Workspace... »
3. Save the project

What you get:
![image](https://user-images.githubusercontent.com/678848/41541737-733062c0-7313-11e8-9245-e27a681ac679.png)

What my `.code-workspace` looks like:
```{
	"folders": [
		{
			"path": "arena.utt.fr-api"
		},
		{
			"path": "arena.utt.fr-2018"
		}
	],
	"settings": {}
}```


Also tried (by going into projects.json):
```[
	{
		"name": "arena",
		"rootPath": "$home/Workspace",
		"paths": [
			"arena.utt.fr-api",
			"arena.utt.fr-2018"
		],
		"group": ""
	}
]
```

And it doesn't works, it just opens my whole Workspace directory.

Any clue ?

**Comment by alefragnani** [comment]
Hi @gjuchault ,

This option was put _on hold_ after Workspaces has landed in VS Code. That's why it has no effect today, and will probably be removed in the future. The original intention was to _prepare_ for Workspaces (even before being developed by VS Code itself) but with the current Workspaces implementation (which hides access the `.code-workspace`) access, I didn't see a good reason to keep it.

Looking at it now, after your comment, I was thinking that maybe it could be used to _mimic_ a workspace. I mean, I could create _my own workspace API_, as originally intended. I will think about it 😀 . 

Hope this helps

**Comment by dufferzafar** [comment]
@alefragnani So Is there no way to have multiple folders in a single project?

I'm very new to VSCode and coming from Sublime, this is one of the features I'm missing.

In Sublime, this option is called "Add folder to project" which adds any folder to the current project.

**Comment by dufferzafar** [comment]
I finally read up on what workspaces are, and I think they're just like sublime's projects.

I bound `Alt+Ctrl+P` to `workbench.action.openRecent` which is what Sublime has.

I've disabled this plugin for now, if I miss a feature from Sublime, I'll come back.

**Comment by alefragnani** [comment]
Hi @dufferzafar ,

Yes, Workspaces in VS Code are _the answer_ to Multifolder Projects in Sublime. You can create a workspace containing a set of folders, and when you open that workspace, it will present you all that folders opened at once, in the same window.

My extension was created at the very beginning of VS Code. The idea was to have a **Manager for your Favorite Projects**, with an easy way to manage and open them. Today, it allows you to have not only your **Favorite Projects** but also an _auto-detection_ of **Git**, **SVN** and **Mercurial** repositories. So, you just have to define a `baseFolder` where these repositories are, and you a ready to use them. _There is no relation to Sublime's projects or VS Code workspaces._

> I've disabled this plugin for now, if I miss a feature from Sublime, I'll come back.

No problem 👍

**Comment by IRIS-Core** [comment]
Some of my Favorite Projects have multiple folders, please add support for this >_<

**Comment by zhyiyu** [comment]
We can add multiple folders to a workspace now, but it seems like there is no way of opening a new workspace without closing out the old one. Also, there is no way of saving the old workspace, or even change its name!

And that is why I ask for help from project manager, is there a way of doing that?

Please forgive me for asking this dumb question here, but I have been trying to find instructions for a few days with no one seems to be interesting doing this.

Please let me know if my description was not clear. Thanks!
