### ISSUE TITLE
[FEATURE] - [Sidebar] - Prompt for confirmation on switching projects if having processes running in terminal.

### ISSUE THREAD

**Issue by liyachun01** [alefragnani/vscode-project-manager#464]
## Describe the feature you'd like.
**Action**
Directly click on a project name in the sidebar.
**Current behavior**
Switch to the clicked project
**Requested behavior**
While it may exist running (integrated terminal) processes in current project (workbench), for a mistake click on another project name in the pm sidebar (which happens to me from time to time), a friendly prompt for confirmation can be appreciated.

**Comment by alefragnani** [comment]
Hi @liyachun01 ,

VS Code itself already has this kind of warning. You just have to turn it on. 

Take a look at this comment https://github.com/microsoft/vscode/issues/74642#issuecomment-520052767

Hope this helps
