### ISSUE TITLE
add same/upper folder to project like "add folder to workspace"

### ISSUE THREAD

**Issue by imyaFamiliev** [alefragnani/vscode-project-manager#465]
Hello!
Is there a way to add upper level folders to project, so they appear in the explorer window like when adding folders using File->Add Folder to Workspace... ?
When i do this  folder information saved in workspace.code-workspace file and folders popup in explorer window.
But when i switch to another project , and switch back to current,  recently added folders lost from the explorer window.
So, project manager did not use information about added folders from workspace.code-workspace file when reopen project.

**Comment by alefragnani** [comment]
Hi @imyaFamiliev ,

I'm not sure I understand your scenario. Are you saying that after you added a folder to some workspace (via the Project Manager extension command), and switched between projects, when you returned to the original project, the _added_ folder was incorrect?

The `Add to Workspace` command from the **Project Manager** extension replicates the native VS Code command, storing the same information/path. I couldn't replicate an issue, comparing both commands.

Just out of curiosity, the `Reopen` command is not handled by the extension, and the extension does not _save_ any information about the project you opened, at least not _in VS Code_.

Could you please describe the steps you did? Maybe a gif showing your issue?

Thank you.

**Comment by imyaFamiliev** [comment]
made some changes. i figured out that workspace.code-workspace file must be saved in the right path, so project will be a unique workspace.

1 set new project A in project.json file
2 switch to new project A 
3 explorer window show content of path "B"  ( from  rootPath from project.json file )
4 go to File menu ->Add Folder to Workspace... and add path "C"
5 path "C" appears in exlorer window
6 try to switch to another  project D , vscode ask to save  workspace.code-workspace file, i save it to path "B"
7 switch to another project
8 switch back to project A 
9 a window pops up asking to open workspace file because this file (workspace.code-workspace) is located in the path "B"
10 now the explorer contains all the contents of the "B" folder and the added "C".

so my question is

**Comment by alefragnani** [comment]
Hi @imyaFamiliev ,

Oh, I see. It seems the confirmation message you see is the one VS Code displays when you open a folder and it contains a `.code-workspace` file in it.

This message is not controlled/displayed by the extension, but by VS Code itself. I don't use Workspaces (multi-root folder) that much, so I'm not sure there is a setting to decide if it should display a confirmation message or not. A quick look at the settings, didn't show me anything.

I suggest you to take a look at VS Code issues, maybe someone already had this issue and found a solution/workaround.

BTW, you can save not only **Folders** on Project Manager, but also **Workspaces**. But if you open a _folder that contains a .code-workspace file_, the popup would still be displayed.

Hope this helps
