### ISSUE TITLE
[BUG] - Command 'Project Manager: List Projects to Open' resulted in an error (command 'projectManager.listProjects' not found)

### ISSUE THREAD

**Issue by dmitry-mightydevops** [alefragnani/vscode-project-manager#469]
**Environment/version**

- Extension version: 12.0.1
- VSCode version: 1.53.2
- OS version: Fedora 32, 5.10.16-100.fc32.x86_64

**Steps to reproduce**

Frequently I'm getting this notification error and then none of the Project Manager commands (Ctrl-Shift-P) are working giving me similar errors

```
Command 'Project Manager: Edit Projects' resulted in an error (command 'projectManager.editProjects' not found)
```

```
Command 'Project Manager: Add Project to Workspace' resulted in an error (command 'projectManager.addToWorkspace' not found)
```

**Comment by alefragnani** [comment]
Hi @dmitry-mightydevops ,

It appears, for some reason, the extension is not initializing. 

Could you run the `Toggle Developer Tools` Command and select `Console` tab, and then reload VS Code window? Post the messages, so I could try to find out what is happening.

Thank you

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been made since my last question. 
Feel free to reopen/comment if the error still occurs.

**Comment by kenzouno1** [comment]
Same issue when update to version 12.7.0. I'm restored to 12.6.1 and use normally
![image](https://user-images.githubusercontent.com/1946802/189273070-f754fc6b-3b00-4bb1-9e2d-149878e0d7ba.png)
