### ISSUE TITLE
[FEATURE] - Ability to show parent directory name for autodetected projects

### ISSUE THREAD

**Issue by afischer-opentext-com** [alefragnani/vscode-project-manager#470]
I have a base folder which includes various git repositories, which follow the following pattern:
```
<base>/github.com/<account>/<project>
<base>/gitlab.com/<account>/<project>
```
or using an example
```
~/github.com/saltstack/salt
~/github.com/some_clone/salt
~/gitlab.com/yet_another_clone/salt
```

The issue is now that all three projects simply get the name `salt` when being auto-detected. Due to that it would be awesome to have in such a case the parental directory(ies) being part of the project name (until they become unique).

**Comment by alefragnani** [comment]
Hi @afischer-opentext-com ,

This has already been requested in #306. Please, upvote there, so I can keep track.

Thank you
