### ISSUE TITLE
[FEATURE] - Ability to define an Icon per project

### ISSUE THREAD

**Issue by afischer-opentext-com** [alefragnani/vscode-project-manager#471]
My workflows require it to have multiple instances of vscode open, each defined by a project managers project. Switching between those projects is cumbersome as they can't be easily identified e.g. by an Icon. In all cases its just the vscode icon, which regularly leads to the situation that I need to search the "right" project. 

Due to that my request is to have the ability to define a specific icon per project which is then used by the vscode instance and its task bar icon. I would be also fine with some other indicator, if an icon is not possible per the vscode/electron API.

A screenshot of the current situation is this:

![2021-03-03_18h09_50](https://user-images.githubusercontent.com/37439392/109844779-c2a6c480-7c4c-11eb-98a7-5f923ea84ca8.png)

My proposal would be to have something like this:

![2021-03-03_18h09_50](https://user-images.githubusercontent.com/37439392/109844741-b6226c00-7c4c-11eb-98ad-ceb70c14bcc0.png)

**Comment by alefragnani** [comment]
Hi @afischer-opentext-com ,

I don’t think this is possible, neither with the recent Product Icon Themes (https://code.visualstudio.com/api/extension-guides/product-icon-theme) which seems replace the built-in icons only (not the Application itself). 

It’s not the same thing, but I would suggest you to update the `window.title` setting, so it would display a customized name when you hover the icon, or using the Peacock extension, which allows you to define different colors for each window.

Hope this helps

**Comment by afischer-opentext-com** [comment]
The approach using the `window.title` project setting is not ideal but already an improvement. Thank you!
