### ISSUE TITLE
Additional side bar groups / headers?

### ISSUE THREAD

**Issue by bloomingbridges** [alefragnani/vscode-project-manager#473]
In the same vein as there is a **Favorites** header, would it be feasible to have custom headers as defined in the JSON?

The reason being is that it would feel gross to me mix personal projects with work projects and my current strategy involves using separate IDEs to circumvent that from happening.. 

I'm aware this is a very niche problem, so feel free to ignore my ramblings ˆˆ

**Comment by alefragnani** [comment]
Hi @bloomingbridges ,

I think #50 would work just fine for you, right?

Hope this helps

**Comment by bloomingbridges** [comment]
Ah, yes!
When looking for duplicates I didn't scroll down to read you replies, sorry about that.
