### ISSUE TITLE
[FEATURE] - Make "What's new" panel conditional

### ISSUE THREAD

**Issue by ratermir** [alefragnani/vscode-project-manager#475]
I use this plugin in Eclipse Theia IDE. It works well, but there is one annoying feature of this plugin: it shows "What's new" panel (or maybe screen ? - I don't know a terminology of IDE development) every time IDE starts. In case Theia remote development it means every time IDE connects to the server. It may led to tens of "What's new" panels opened after some time I am off the computer when the line is not perfect (celular with low signal, DSL in long distance from DSLAM ... etc). 

I am not sure whether "What's new" screens are useful at all (I never read it and I don't know anyone who do it), so removing it could be a reasonable option :) but Adding an IDE confguration item (for example "projectManager.showWhatsNew=false/true") where I decide I want to show it (or not) would be also good option.

**Comment by alefragnani** [comment]
Hi @ratermir ,  

I’m not sure how Theia works, but I suppose it is similar to Codespaces, and it probably installs the extension every time the session starts. The “What’s New” page is displayed whenever you install and/or a _update_ is installed, and I have no intention to have a setting to turn it off/optional.

Just recently the VS Code team sent a PR to my vscode-whats-new submodule (which is responsible for that) to avoid this behavior, but using Settings Sync API, which I suppose isn’t available in Theia.

I have created this issue (https://github.com/alefragnani/vscode-whats-new/issues/23 ), to avoid the that page on Codespaces/ Remotes, and IF Theia inherits the same approach/API, it would work too.

Hope this helps.
