### ISSUE TITLE
[FEATURE] - Configuring Base Folders for remote projects

### ISSUE THREAD

**Issue by fregatte** [alefragnani/vscode-project-manager#476]
Hi there!
I'm using Project Manager for the local development and this is a cool and handy plugin, thank you!
However, now I've switched to remote setup and use vscode with remote ssh connection.
I've tried to find all my remote projects by setting the "ProjectManager:Git:BaseFolders" option, but unfortunately it didn't find anything.
Is it possible to configure PM to search Git projects on the remote host, instead of locally? Or is there any other way to auto-update the project's list from a remote filesystem (without configuring and saving one-by-one)?

**Comment by fregatte** [comment]
Sorry, have already found the answer [here ](https://github.com/alefragnani/vscode-project-manager/issues/397#issuecomment-657697715)
But it will be great to add this info to the documentation, or welcome screen of the plugin. Thanks!

**Comment by alefragnani** [comment]
Hi @fregatte ,

That’s great you found the answer!

Yes, I think a topic on README would help. Thanks for your suggestion.
