### ISSUE TITLE
[FEATURE] - Add documentation about how to use the extension on Remote Development

### ISSUE THREAD

**Issue by alefragnani** [alefragnani/vscode-project-manager#477]
Add a topic about how the extension works on Remote Development scenarios, the default/defined approach and alternative ways, like installing on remotes and shared configs

**Comment by TomYeoman** [comment]
Works flawlessly for me, after adding the suggested config, and a base folder (make sure you've got a project open in WSL, when you refresh your git projects) -  thanks!

```
  "remote.extensionKind": {
      "alefragnani.project-manager": [
          "workspace"
      ]
  },
  "projectManager.git.baseFolders": [
    "$home/git"
  ],
```
