### ISSUE TITLE
Switching between open windows

### ISSUE THREAD

**Issue by roblourens** [alefragnani/vscode-project-manager#48]
Have you considered extending it to show all open VS Code sessions, and let me switch between those? I don't know off the top of my head whether an extension can know when the window is being closed. If not, the list could be "recently opened folders" or something.

I'd find both modes really useful - like cmd+alt+p to show my saved projects, ctrl+cmd+p to show all open windows.

**Comment by roblourens** [comment]
I didn't notice that there's a keyboard shortcut for 'open recent', but that kind of covers this use case.

**Comment by alefragnani** [comment]
I didn't find any API for that, but as you added, the **Open Recent** command seems do the trick :smile: 

I remember to see an issue in VS Code repo about adding a **Windows** menu, so you could switch between the open sessions. Unfortunatey I didn't bookmarked that to reference it here.

By the way, if you try to open a project that is already opened (in another VS Code session), it will switch to that session automatically, even you set `projectManager.openInNewWindow` to `false`.

Maybe the new **Recent** config for `projectManager.sortList`, added in 0.9.0 release would help you too?

Hope this helps

**Comment by alefragnani** [comment]
@roblourens It seems this will be handled _nativelly_ in September, with https://github.com/Microsoft/vscode/issues/12522.

**Comment by alefragnani** [comment]
@roblourens Confirmed that in the latest insider, there is a new command called **Switch Window** that does exactly this.
