### ISSUE TITLE
[FEATURE] - Use specific icons for each kind of remote project

### ISSUE THREAD

**Issue by alefragnani** [alefragnani/vscode-project-manager#483]
Today, every saved remote project has the same icon, which means that you don't distinguish between Docker, SSH, WLS and Codespaces.

The idea is to use a specific icon for each kind of remote.

> Originally suggested in https://github.com/alefragnani/vscode-project-manager/issues/479#issuecomment-811484223

**Comment by alefragnani** [comment]
All 3 remotes already have their codicons:

* Containers: `symbol-method`
* SSH: `terminal`
* WSL: `terminal-linux`

originally commented in: 
* https://github.com/alefragnani/vscode-project-manager/issues/479#issuecomment-811540426
* https://github.com/alefragnani/vscode-project-manager/issues/479#issuecomment-814422453

**Comment by alefragnani** [comment]
To identify the _kind of remote_, it uses the prefix of the `Uri` path 

| Remote | Uri |
|--------|-----|
| **Codespaces** | vscode-remote://codespaces |
| **Containers** | vscode-remote://dev-container|
| **WSL** | vscode-remote://wsl |
| **SSH** |  ??? |

I didn't have **WLS** nor **SSH** remote environments, but found in https://github.com/microsoft/vscode/issues/120018 how **WSL** works. 

@TylerLeonhardt do you know that, or have access to some `SSH` remote to validate the info?

Thank you

**Comment by TylerLeonhardt** [comment]
```
{
		"name": "xterm.js",
		"rootPath": "vscode-remote://ssh-remote+localhost/Users/tyleonha/Code/xtermjs/xterm.js",
		"paths": [],
		"group": "",
		"enabled": true
	}
```

this is from adding `ssh username@localhost -A` to remote SSH (a great way to test it yourself! - keep in mind you need get sshd running on your machine for this to work)

**Comment by alefragnani** [comment]
Thanks! 🎉 

It’s been a long time I don’t need to use SSH, so I totally forgot I could test _locally_. But I hope this will change soon...

**Comment by alefragnani** [comment]
Depends on VS Code 1.56 (April release) and https://github.com/alefragnani/vscode-ext-codicons 1.4.0 (released right after VS Code)

Tracked in https://github.com/alefragnani/vscode-ext-codicons/issues/6

**Comment by alefragnani** [comment]
The dependencies has been resolved

* VS Code 1.56 has been released and the codicons were also published.
* My NPM package has been updated as well (v 1.4.0)

Update the dependency and use the new codicons

**Comment by Herjar** [comment]
Do I need to do something to enable icons? All projects get the same icon for me:
![image](https://user-images.githubusercontent.com/3456683/144818814-8748e62b-9ac0-4187-adca-5bf44d9a07dd.png)

**Comment by alefragnani** [comment]
Hi @Herjar ,

This icon refers to Workspaces (a `.code-workspace` file), so I guess you saved a Workspace project, inside SSH and WSL. You can move the mouse over each one and wait for the Tooltip, which displays the path and kind of project.

In this case, this is the expected behavior

Hope this helps

**Comment by Herjar** [comment]
When I hold over each project the correct type and icon shows. 

Example of how I try to add a project: I open a new editor, connect to remote host and open a folder. I try to save a project, but I get this message:
![image](https://user-images.githubusercontent.com/3456683/144991162-76bf5c66-22ec-4792-87e8-0bf696c383b5.png)
So yes, then I save to a `.code-workspace` file, and then I can save the project.

Sounds like I am using it the wrong way, but it tells me I have to save the workspace first?

**Comment by alefragnani** [comment]
If you have a _multi-root workspace_ open, no matter if it is locally or remotely (docker, ssh, wsl), it will be recognized as a _multi-root workspace_. And to be able to use the `Project Manager: Save Project` command, you will need to save the `.code-workspace` file first, because the project will be linked to this `.code-workspace` file.

But, if you open any _remote project_ and use the `Project Manager: Save Project`, it will save the project (linked to the relative folder) directly.

It works this way for Docker (which is the only one I have available right now), and it should work this way for WSL and SSH as well. Unless VSCode let you open a remote connection _without any folder_ and when you open a folder, it _thinks_ to be adding a new root-folder.

Hope this helps
