### ISSUE TITLE
Color support in sidebar

### ISSUE THREAD

**Issue by mikeerickson** [alefragnani/vscode-project-manager#488]
I am curious, is it possible to add color support when displaying items in the sidebar?

It would sure be cool to be able to apply colors so that I could more easily find projects.  I currently use various "prefix" items so that I can group projects, but having color support would really help

Client Projects:
-clients/...

Codedungeon OSS Projects:
@codedungeon/...

**Comment by alefragnani** [comment]
Hi @mikeerickson ,

Unfortunately, there is no API available to add/use colors in the Side Bar.

But I guess #50 may work for you. Take a look at https://github.com/alefragnani/vscode-project-manager/issues/50#issuecomment-811534516

Hope this helps

**Comment by mikeerickson** [comment]
@alefragnani well that will be terrific, can’t wait!
