### ISSUE TITLE
Add opened projects/folders history

### ISSUE THREAD

**Issue by whitecolor** [alefragnani/vscode-project-manager#49]
I think it would be useful to have opend project history. And sometimes you open some temporary folder/project that you actually don't won't to save but it maybe needed to open it again, history would help much in this case.

what do you think?

**Comment by alefragnani** [comment]
Do you know about **File / Open Recent** command? It's built in VS Code and store up to 10 recent folders/projects (also files) that you have previously opened. 

Maybe this could help you. At least it helps me a lot :smile:

**Comment by whitecolor** [comment]
Probably this helps thanks))

**Comment by innerlee** [comment]
Hi @alefragnani , it would be cool if we can access the list of recent opened projects on the activity bar. It would reduce the clicks and keyboard strokes accessing that `open recent` command.

**Comment by alefragnani** [comment]
Hi @innerlee ,

The Side Bar wasn’t available in 2016, so, this idea didn’t existed 😬 .

Please, fill a new issue about it, better yet, including a mock-up on how you think it would become.

Thank you
