### ISSUE TITLE
Contextual Structure for Projects

### ISSUE THREAD

**Issue by robsonrosa** [alefragnani/vscode-project-manager#50]
The are some issues related with this one, but not seems the same goal. 
- #43 
- #46 
- #47

I work in several projects that are related in some way. There are two frameworks with many sub projects, for example. I could say that I work in different contexts and the projects are differents in theses contexts, so it will be nice if I could change my current context and the projects availables in this context.

In other words, I am suggesting an `project.json` with this format:

```
[
  {
     "label": "awesome-framework",
     "projects": [
       {
          "label": "core",
          "description": "C:\\awesome-framework\core"
       }, 
       {
          "label": "ui",
          "description": "C:\\awesome-framework\ui"
       }
    ]
  },
  {
     "label": "wonderful-framework",
     "projects": [
       {
          "label": "core",
          "description": "C:\\wonderful-framework\core"
       }, 
       {
          "label": "ui",
          "description": "C:\\wonderful-framework\ui"
       }
    ]
  },
  {
     "label": "personal",
     "projects": [
       {
          "label": "resume",
          "description": "C:\\personal\resume"
       }, 
       {
          "label": "game",
          "description": "C:\\personal\game"
       }
    ]
  }

]
```

And, to usage, there will be another keyboard shortcut to change contexts. So I start my day, choose my context with `alt+shift+c` and along the day I can change my projects with `alt+shift+p`. Maybe I little bit crazy, but I think it will be useful for whom works in more than one company.

**Comment by alefragnani** [comment]
Thanks @robsonrosa ,

Sometime ago I was thinking in a similar idea, but with a different approach. The idea was to add, what you call _context_ as a _group_ for each project. In fact, the same project could be part of different _groups_. The structure should be something like this:

```json
[
	{
		"label": "vscode-language-pascal",
		"description": "c:\\Users\\alefr\\Documents\\GitHub\\vscode-language-pascal",
		"groups": ["vscode" , "delphi"]
	},
	{
		"label": "vscode-bookmarks",
		"description": "c:\\Users\\alefr\\Documents\\GitHub\\vscode-bookmarks",
		"groups": ["vscode"]
	}
]
```

But to do that, first I would like to have [this issue](https://github.com/Microsoft/vscode/issues/11468) resolved in VS Code. So, the listing and selection would be much easier.

Even so, I never thought about a specific command to _change context/group_, and _filter_ the projects from that context while using `List Projects`. I liked your idea 😄 .

Thanks for your suggestion 👍

**Comment by alefragnani** [comment]
Depends on: 

- [ ] https://github.com/Microsoft/vscode/issues/11468
- [ ] #47

**Comment by bobrocke** [comment]
This would be a fine addition and allow projects with many internal folders that don't need to be edited to be excluded for the larger project view. PhpStorm does this and it's very helpful.

**Comment by fabiospampinato** [comment]
@robsonrosa @bobrocke: I've just released a new extension that supports your use case, check it out, I think you'll like it: [Projects+](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-projects-plus).

@alefragnani I don't think it makes much sense to wait for issue [#11468](https://github.com/Microsoft/vscode/issues/11468) to be closed, even if they do implement your request the extension wouldn't be able to support deep nesting.

**Comment by bobrocke** [comment]
Cool!

**Comment by alefragnani** [comment]
@fabiospampinato congrats for your extension 👍  
I decided to wait for that issue to be released because I want to avoid _workarounds_ in my extensions. I have some bad experiences in the past, and now I prefer to use available APIs only. Your _workaround_ was clever, BTW.

About the _nesting_ limitation, I'm not worried, because it wasn't supposed to support anyway. It would be limited to one level only.

**Comment by ferreteleco** [comment]
Is there any update on this?

**Comment by adeptdeveloper** [comment]
I think I would like something like this.  I generally create a "Project" for each client I have, but several clients have multiple projects such as different applications.

- Client XYZ (Project)
-- Web App
-- iOS App
-- Android App
-- API
- Client ABC
-- Public Website
-- Web App

For my usecase, I don't mind seeing all the sub-projects in one Explorer panel, but it would be nice when you do a global search that the search results could be minimized (tree control) by subproject.

I'm not sure if that's entirely clear or not.

Great extension though!

-Steve

**Comment by alefragnani** [comment]
Hi @adeptdeveloper ,

I’m not sure, but based on your scenario, I think you already have this, natively, in VS Code 😬 . Have you tried [Multi-root Workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces)?

Each one of your “client workspace” could be a Multi-root Workspace, composed by each “App”. After created, just save each Multi-root workspace as a new Project on the extension.

Maybe, in the end, you don’t need this Projects grouping feature at all.

Hope this helps

**Comment by adeptdeveloper** [comment]
Hi @alefragnani ,

Yes, thanks, this is exactly what I needed.  I do like how your plugin handles project listing on the Activity Bar, but I found another plugin called Workspace Explorer that works as well.  I wish it was in the Activity Bar but this will do.

https://marketplace.visualstudio.com/items?itemName=tomsaunders.vscode-workspace-explorer

Thanks!
-Steve

**Comment by alefragnani** [comment]
That’s great!

I know about that extension, it appears to work great too, specially if you are a Workspace centric user. In my case, I almost don’t use 😄 .

The grouping idea is what this issue is all about. I already played a bit on how it would work, but just for fun/testing the APIs. I think it should be the next big feature for the extension, but no ETA.

If you change your mind, feel free to evaluate when it’s ready.

Stay tuned

**Comment by alefragnani** [comment]
Based on the suggestion from #416, the idea is to add _icon_ for each groups, so this icon could be used in the Side Bar/Command Palette, instead of a default/basic folder.

https://github.com/alefragnani/vscode-project-manager/issues/416#issuecomment-686170986

**Comment by alefragnani** [comment]
A few month ago, my original issue was closed, in favor of https://github.com/microsoft/vscode/issues/74967, but it didn’t make any difference, because it is not assigned to any Milestone too.

That being said, I’m removing the `depends on` label and changing the original idea on how the UI would work. 

It will be probably a multi milestone feature, and I already started playing with a few ideas, so you could see the first steps on the upcoming releases.

**Comment by alefragnani** [comment]
I know it did take too long, but it's finally going to happen 😬 .

## Motivation

Organize the projects in a way you could _group_ and _filter_ the projects, depending on some _context_. 

## Concept

- What was initially called _group_ will be renamed to **Tag**. 
- Each **Project** can have _more than one Tag_ assigned

### Saving Projects

When you save a new project, you just have to type its **Name**. I would like to keep this _simple_, and avoid adding another step to apply **Tags** to the project. 

### Applying Tags

A new `Edit Project` command will be added to context menu in the **Side Bar**. Once called, a _multi-step_ command will run, where you will be able to:

- Rename the Project
- Update the Project's Path
- Apply/Update Tags
- Enable/Disable the Project

### Side Bar

A new _Tag/Flat view_ option will be added to the **Favorites** panel, so you will be able to choose the best way to display your projects.

When you choose _Tag view_, the projects will be grouped by it's **Tags**. If a projects has more than one **Tag**, it will be displayed on each's **Tag** _node_

This is a sample of a `projects.json` file

```json
   {
     "name": "My Project One",
     "tags: ["Personal"],
     ...
   },
   ...
   {
     "name": "Markdown Snippets",
     "tags: ["Personal", "Company B"],
     ...
   },
   ...
   {
     "name": "Documentation",
     "tags: ["Company B"],
     ...
   },
```

And a mockup displaying the Side Bar

```
  - Personal
    > My Project One
    > My Project Two
    > Markdown Snippets
  - Company A
    > Backend A
    > Frontend A
  - Company B
    > Documentation
    > Markdown Snippets
```

> This _duplicity_ will be better understood with the **Switching Contexts** option

### Switching Contexts

One of the ideas behind **Tags** is to define _contexts_ for each project, like `Personal`, `Company A`, `Company B`, and so on.

Switching contexts will give you the chance to focus on this kind of projects, depending on its **Tags**. Once you switch to some context, the projects will be _filtered_ by that **Tag**.

Only the projects _of that context_ will be available in the **Side Bar** and **Command Palette**.

## Roadmap

At first, it will be available only for **Favorite** projects. 

Once _stable_, it could be expanded to auto-detected projects (**Git**, **SVN** and so on) too.

## Limitations

- It must be simple to use (when needed) 
- Avoid structural changes on `projects.json` file
- No multi-level visualization on **Side Bar**

## Feedback

Are welcome, of course 😁

**Comment by alefragnani** [comment]
🏃  Sneak peek...

![Kapture-QuickPick-with-button-and-canSelectMany](https://user-images.githubusercontent.com/3781424/113223964-ba986f80-9260-11eb-8eb8-642b00da3a85.gif)

I moved to the next milestone, because of an issue I found on a VS Code API (https://github.com/microsoft/vscode/issues/119834). If no solution/fix is found, I'll change a bit on how `Tags` are created. Instead of a dynamic way, like the video, it would use a `User Setting`

Feedbacks are welcome 😉

**Comment by KaniRobinson** [comment]
> 🏃 Sneak peek...
> 
> ![Kapture-QuickPick-with-button-and-canSelectMany](https://user-images.githubusercontent.com/3781424/113223964-ba986f80-9260-11eb-8eb8-642b00da3a85.gif)
> 
> I moved to the next milestone, because of an issue I found on a VS Code API ([microsoft/vscode#119834](https://github.com/microsoft/vscode/issues/119834)). If no solution/fix is found, I'll change a bit on how `Tags` are created. Instead of a dynamic way, like the video, it would use a `User Setting`
> 
> Feedbacks are welcome 😉

A colleague and I was literally just talking about the grouping in this tool, and you sir have come through with a result, this looks amazing!

**Comment by Timbuktu1982** [comment]
Hey. 

This is a great functionality. How can i use this? I mean the usage of tags to get my own structure of all my projects...

Thank you

**Comment by alefragnani** [comment]
Hi @Timbuktu1982 , 

It's not available, yet. I just had to postpone a bit, so stay tuned.
