### ISSUE TITLE
[BUG] - Extension Disabled Because It Does Not Support Virtual Workspaces

### ISSUE THREAD

**Issue by thekendog** [alefragnani/vscode-project-manager#502]
Just updated VSCode and now this extension (12.1.0) isn't working.  Displays the message 'This extension has been disabled because it does not support virtual workspaces.'

**Comment by alefragnani** [comment]
Hi @thekendog ,

This item is already being tracked in #501. It's planned for the next release.

Hope this helps

**Comment by thekendog** [comment]
Is there anyway to get around it for now?  I rely heavily on this extension.
