### ISSUE TITLE
Relativ VS Absolute path - Sidebar menu VS Taskbar (Statusbar)

### ISSUE THREAD

**Issue by homezonebenny** [alefragnani/vscode-project-manager#516]
If you set this into the settings.json file:

```json
  "projectManager.git.baseFolders": [
    "\\VSCode_Workspace",
  ],
```

And you open it via the left side bar "Project Manager" and down in the section "Git" it works fine though.
But if you want to open it via the Taskbar (bottom status bar) you need to set it like this:

```json
  "projectManager.git.baseFolders": [
    "D:\\VSCode_Workspace",
  ],
```

Without the drive letter the Taskbar (Statusbar) option will not work.
This feels kinda inconsistent.

\
This means relativ paths only work with the side bar but **not** with the Taskbar (bottom status bar).

**Comment by alefragnani** [comment]
Hi @homezonebenny ,

The `baseFolders` setting does not support _relative_ path, just _full_. I'm not sure why/how `\\VSCode_Workspace` did worke for Git repos detection, but it's unexpected.

You can however, use `~` or `home` _special variables_, which will be replaced for you `HOME` folder.

Hope this helps
