### ISSUE TITLE
[BUG] - FUNDING.yml: Invalid GitHub Sponsors user

### ISSUE THREAD

**Issue by The-Compiler** [alefragnani/vscode-project-manager#523]
When clicking the "Sponsor" button in this repo, I see:

![image](https://user-images.githubusercontent.com/625793/122940848-20cef300-d375-11eb-931e-2c960ad9e897.png)

This seems to be because @alefragnani is [listed in there](https://github.com/alefragnani/vscode-project-manager/blob/c19c27e197dfdd4783b5dd3c680c2f0041fe18f1/.github/FUNDING.yml#L1) under `github:`, but doesn't actually seem to have a GitHub Sponsors profile.

**Comment by alefragnani** [comment]
Hi @The-Compiler ,

First of all, thank you for your interest in sponsoring me, and for your donation! It's great to know the extension is being useful! 🤝

About this error, yes, I'm still on the waiting list.. I decided to add the profile details there to be prepared to the day my Sponsors profile is active. But unfortunately, Brazil is still on the waiting list for GitHub/Stripe, and no ETA.

I'm not sure the `Sponsors` button will still appears if I remove that line from `FUNDING.yml` (I remember some issues about that button at the beginning), but if it remains there, I'll remove the line to avoid that warning, until my Sponsors profile is available.

Thank you

ps: I can let you know when my Sponsors profile is available, if you wish 😬
