### ISSUE TITLE
[BUG] - Open in new window blank screen

### ISSUE THREAD

**Issue by Wesleyzxc** [alefragnani/vscode-project-manager#529]
When I'm switching between projects, opening in a new window doesn't load the new project up, instead it returns a blank screen. I've downgraded to v12.2.0 and it works as intended.

*On further testing, it does work on the latest extension version, but on very small test repos. Also, it still causes issues sometimes, so it could possibly be a VS Code bug. 

**Environment/version**
- Extension version: v12.3.0
- VSCode version: 1.58.1
- OS version:  Windows 10 Pro

**Steps to reproduce**
1. Open project A
2. Open project B in new window

**Comment by MarcoNovaro** [comment]
I have a similar problem, even with projects open in the same window.
Yet, I'm also not sure if this is a problem of VSCode, since both (VsCode and the extension) got an update recently.

**Comment by alefragnani** [comment]
Hi,

I'm not being able to reproduce this error, neither in Windows, nor in MacOS, both on Stable and Insiders releases.

I've used 3 different ways to open projects:
* Using the basic `Command Palette` command
* Via the Context Menu in the `Side Bar`
* Clicking the inline command, in the `Side Bar`

Everything seems to be working just fine

Could you provide a more detailed step by step and/or a video showing the issue. Also, maybe you could open the `Developer Tools` to see if some error is shown in `Console`

Hope this helps

**Comment by MarcoNovaro** [comment]
At least from my side, this problem seems due to the "VSCode blank screen" bug, as described in here:

https://stackoverflow.com/questions/40323190/vs-code-main-window-is-blank

I included --disable-gpu, and now I can't see the problem anymore.
Thanks for the quick feedback.

**Comment by Wesleyzxc** [comment]
Thanks @MarcoNovaro, I can only replicate this problem on my work laptop, will try it out and check back.

**Comment by Wesleyzxc** [comment]
I've cloned one of my own repos and tried switching and it happened again. After adding `--disable-gpu` on the target: `"C:\Program Files\Microsoft VS Code\Code.exe" --disable-gpu` it seems to be working fine now.

**Comment by alefragnani** [comment]
Wow, I never saw that GPU issue, but I'm glad to see you found a fix.

Thanks for sharing

Enjoy the extension

**Comment by Wesleyzxc** [comment]
Yup, also tried the same trick on my work laptop but it still acts up. The second suggestion on the stackoverflow is to set compatibility to Windows 7. I've tried that and it seems to be working for now, will continue for a day or two and see if it happens again.

**Comment by alefragnani** [comment]
@Wesleyzxc , thanks for sharing!
