### ISSUE TITLE
[BUG] - "Releases" is out of sync with VSCcode version

### ISSUE THREAD

**Issue by tyler36** [alefragnani/vscode-project-manager#533]
I was looking at the [main github page](https://github.com/alefragnani/vscode-project-manager) and noticed it displays `12.0.1 (latest)`. 

I can see there are files such as `changelog.md` updated for `12.3.0` ... see screenshot
![project-manager-outdated release](https://user-images.githubusercontent.com/7234392/127288351-dfec15ca-f508-45d3-bfea-7e82d46a72cd.jpg)

Indeed, Vscode shows my current version as `12.3.0`. 

I'm not sure how you manage Github / Vscode extension releases but you might have forgotten to update something somewhere.

**Comment by alefragnani** [comment]
Hi @tyler36 ,

Yes, the releases are not synced, and it will probably not be synced in the near future. The original reason behind those releases is no more necessary so, there is no need to keep it updated.

Hope this helps

**Comment by tyler36** [comment]
Thanks for the update.
