### ISSUE TITLE
[FEATURE] - Nested projects

### ISSUE THREAD

**Issue by cotneit** [alefragnani/vscode-project-manager#539]
In monorepos you have multiple closely related projects. Sometimes you want a shortcut to open a certain project in a new window without all the surroundings (which among other things improves VSCode integration in certain cases, like avoiding custom icon conflicts).

VSCode workspaces partly solve this issue, but I feel like project-manager is in the perfect position to extend them.

I propose a nested project structure that will allow us to quickly open folders belonging to a workspace in a separate window. I suppose it could rely on either existing workspace configuration or project-manager's config to define and extract child-projects (basically every "folders" entry in workspace config should be a child-project).

The alternative is manually creating a new project for each folder in a workspace, where you also have to provide context to define the parent-project.

I hope I conveyed the idea, would love to see this!

**Comment by alefragnani** [comment]
Hi @cotneit ,

If I understand correctly, you just want a `Open in New Window` command available for each one of the root-folders from a multi-root workspace, right? So, whenever you need to open one of the inner folders from you monorepo, on a separate window, you just hit the command and it’s done.

In this case, I suggest you to use this extension https://marketplace.visualstudio.com/items?itemName=chrisdias.vscode-opennewinstance. It works pretty well.

Hope this helps.

**Comment by cotneit** [comment]
Thank you, @alefragnani ! This is not exactly what I had in mind, but the recommended extension will definitely come in handy!

I actually found an extension that does exactly what I want (except for automatically extracting root-folders from a workspace, instead it relies solely on the config file, which works perfectly fine for me). 

Here's a screenshot from that extension of what I had in mind: 
![image](https://user-images.githubusercontent.com/36513243/129729268-75d8845c-0bea-4cde-b910-57cb96791dc6.png)
Basically, you can group related projects in one place, much like tags but more isolated. 
Here, `uni-y2-practice` is a group, which also happens to be the name of a monorepo.
* `_root` is a link to the root of that monorepo:
![image](https://user-images.githubusercontent.com/36513243/129730271-83f11a37-9214-497f-ab0e-333f0f8088ae.png)
* `client` and `server` are links to the respective folders (projects) inside the monorepo

The extension: https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-projects-plus

All in all, I'm very satisfied with how it works, and I thought you would be interested in implementing something like this in project-manager.

**Comment by alefragnani** [comment]
Hi @cotneit,

That's great to see the Project Plus extension works for you. I remember, when Fabio first released, that it lets you organize your projects using a multi-level approach. I never used, but I remember it has a good feedback.

Right now, I'm trying to avoid such complexity. I totally understand its value, but I see **Tags** as a good alternative for simpler scenarios. And keeping the current approach, would also be easier to replicate on auto-detected projects.

Thank you.
