### ISSUE TITLE
[FEATURE] - Disable projects tooltips in the sidebar

### ISSUE THREAD

**Issue by inwardmovement** [alefragnani/vscode-project-manager#547]
As far as I'm concerned the info displayed in the projects tooltips is not useful.
A disable switch would be great.

**Comment by Tim-Tech-Dev** [comment]
Do you want to disable only icon? If so, there is already a built-in function in VS Code which handles this (by right-clicking the icon).
![Screenshot](https://user-images.githubusercontent.com/64265106/133908167-3ed4877c-da97-451d-be14-9acb3f1df786.png)

**Comment by inwardmovement** [comment]
No I want the icon/sidebar. I just don't want the tooltip over each
project, inside the sidebar.

**Comment by inwardmovement** [comment]
Will there be a way to disable these tooltips?

**Comment by inwardmovement** [comment]
I'm closing as we can use `workbench.hover.delay` to control these tooltips in some way.
