### ISSUE TITLE
[FEATURE] - Cannot find git project automatically if it's a symlink

### ISSUE THREAD

**Issue by felipecrs** [alefragnani/vscode-project-manager#548]
I always have at least one symlink in my git base dir:

```
dotfiles -> ~/.dotfiles
```

Currently, the project manager won't find such project.

**Comment by alefragnani** [comment]
Hi @felipecrs ,

This is already being tracked in #274. 

I'm planning to take a look at this in upcoming releases, but as I _avoid_ using symlinks, I hope my test scenarios will be enough 😄 

Stay tuned

**Comment by felipecrs** [comment]
Thank you, and sorry for the duplicate.

**Comment by alefragnani** [comment]
No problem 👍
