### ISSUE TITLE
As a user It would be nice to support relative paths

### ISSUE THREAD

**Issue by wendellmva** [alefragnani/vscode-project-manager#55]
when setting the projects.json location you have the option to set that in the workspace settings in .vs instead of in the user settings. It would be nice to support relative paths from there so ./../ sets the projects.json in the root folder of the current project. If you have a flag projects.relative: true then you could store the project location relative to the projects.json file. The use case it would support: direct opening of git sub-modules inside and outside the current workspace environment. and the ability to save the current workspace project in the git repo so all collaborators can share the same projects setup. Let me know what you think. Great extension btw kudos.

**Comment by alefragnani** [comment]
Hi @wendellm ,

That's a great idea! I never thought about using as _workspace setting_. I will investigat some ideas and add some comments, so we could evolve this issue together. 

Thanks 👍

**Comment by alefragnani** [comment]
Last week I decided to "re-focus" on some of my extensions, and I'll start to plan milestones for each of them. This "re-focus" will be based on community feedback/support.

I'm closing this issue because no new comments/reaction has been added in two years, so it seems it is not something as useful as expected. It could be reopened if new requests appears.

Thanks

**Comment by jolo-dev** [comment]
Hi @alefragnani,

this is something which we would like to have. Reason: Monorepo
Is there a change to consider this again?

Best.

**Comment by alefragnani** [comment]
Hi @jolo-dev ,

There is always a chance 😄 

Which kind of project would be more useful? Favorites (saved) or auto-detected (like Git)?

**Comment by alefragnani** [comment]
Thanks for the update.

And yes, the `.vscode` folder would probably be the location for it.

BTW, if you need onboarding for new joiners, I suggest you to take a look at [CodeTour extension](https://marketplace.visualstudio.com/items?itemName=vsls-contrib.codetour). It may fit perfectly for you.

Hope this helps
