### ISSUE TITLE
[FEATURE]  activate certain extensions

### ISSUE THREAD

**Issue by GHOSTS15** [alefragnani/vscode-project-manager#552]
an extension that allows you to activate certain extensions when you execute a command, (ie if I need only certain extensions when I develop with a language) I make the command and activate only the extensions that I need.

**Comment by alefragnani** [comment]
Hi @GHOSTS15 ,

The extension’s idea is not activate/deactivate other extensions, but manage your projects to quickly access. 

The #281 asks to _associate_ extensions for each project, but unless VS Code itself allows you to activate/deactivate extension on a per-session scenario, it wouldn’t be possible to.

You could try [Profile Switcher](https://marketplace.visualstudio.com/items?itemName=aaronpowell.vscode-profile-switcher&wt.mc_id=profileswitcher-github-aapowell) extension, to see if it does works the way you need.

Hope this helps

**Comment by GHOSTS15** [comment]
ok allora devo chiederlo proprio a vs code se lo implementa , se no chi ha 20 o piu estensioni per diversi linguaggi diventa matto ad attivarle e disattivarle ogni volta

**Comment by alefragnani** [comment]
Just out of curiosity, what's the reason you would like to activate/deactivate extensions depending on the language you use? It should already work this way...

I mean, you may have 20 extensions installed, but only 5 being active when you open _a certain project_. It's up to the extension to choose the conditions to activate (and VS Code uses that).

Of course, some extensions chooses to be active for _any_ project you open (like this one), but others only if you open a certain file type, or a project that contains a certain file, etc. This is what extensions uses (https://code.visualstudio.com/api/references/activation-events). If you see some extension that is active but _shouldn't_, maybe you could ask the author to revisit its `activationEvents`.

BTW, I'm not saying I don't want this feature (because I do), but it's not just VS Code that needs attention.

**Comment by GHOSTS15** [comment]
> 
> 
> Solo per curiosità, qual è il motivo per cui vorresti attivare/disattivare le estensioni a seconda della lingua che usi? Dovrebbe già funzionare così...
> 
> Voglio dire, potresti avere 20 estensioni installate, ma solo 5 sono attive quando apri _un determinato progetto _. Sta all'estensione scegliere le condizioni da attivare (e VS Code lo usa).
> 
> Naturalmente, alcune estensioni scelgono di essere attive per _qualsiasi _progetto che apri (come questo), ma altre solo se apri un certo tipo di file, o un progetto che contiene un determinato file, ecc. Questo è ciò che usano le estensioni ( [https: //code.visualstudio.com/api/references/activation-events ](https://code.visualstudio.com/api/references/activation-events)). Se vedi qualche estensione che è attiva ma _non dovrebbe _, forse potresti chiedere all'autore di rivisitarla `activationEvents`.
> 
> A proposito, non sto dicendo che non voglio questa funzione (perché lo voglio), ma non è solo VS Code che ha bisogno di attenzione.


Because some might conflict and then because it's much more organized.

**Comment by GHOSTS15** [comment]
> 
> 
> > Solo per curiosità, qual è il motivo per cui vorresti attivare/disattivare le estensioni a seconda della lingua che usi? Dovrebbe già funzionare così...
> > Voglio dire, potresti avere 20 estensioni installate, ma solo 5 sono attive quando apri _un determinato progetto _. Sta all'estensione scegliere le condizioni da attivare (e VS Code lo usa).
> > Naturalmente, alcune estensioni scelgono di essere attive per _qualsiasi _progetto che apri (come questo), ma altre solo se apri un certo tipo di file, o un progetto che contiene un determinato file, ecc. Questo è ciò che usano le estensioni ( [https: //code.visualstudio.com/api/references/activation-events ](https://code.visualstudio.com/api/references/activation-events)). Se vedi qualche estensione che è attiva ma _non dovrebbe _, forse potresti chiedere all'autore di rivisitarla `activationEvents`.
> > A proposito, non sto dicendo che non voglio questa funzione (perché lo voglio), ma non è solo VS Code che ha bisogno di attenzione.
> 
> Because some might conflict and then because it's much more organized.

then i have 128 extensions (some because i still have to test them, others i was curious and others i have to remove) If I keep them all active, think how long it takes to load vs code and how many possibilities to have problems ..... instead if I can decide with a command to activate certain extensions (or as I wrote better here: https://github.com/microsoft/vscode/issues/40239#issuecomment-932686852 ) would be much more organized and have less problems.

**Comment by alefragnani** [comment]
Take a look at `Developer: Show Running Extensions` command, and you will be able to see which/how many extensions are actually active/running.

**Comment by GHOSTS15** [comment]
yes all those I have activated manually (I don't have 128 active extensions, many I have disabled) I have only 18 active extensions, (which also shows me from the command you gave me)
