### ISSUE TITLE
[FEATURE] - Open project in new window when holding `ctrl` key

### ISSUE THREAD

**Issue by Antyos** [alefragnani/vscode-project-manager#553]
Holding `ctrl` while clicking a project in the Project Explorer should open that project in a new window. This is the equivalent of right clicking on the project and selecting **Open in New Window**. 

Additionally, this change would match the behavior of VS Code when holding `ctrl` and selecting a folder from **File > Open Recent**.

P.S. Thanks for such a useful extension!

**Comment by alefragnani** [comment]
Hi @Antyos ,

First of all, thank you. I'm glad to know you like the extension.

About the request, this was the initial idea, but up until today, there is no API available. I opened https://github.com/microsoft/vscode/issues/18064 almost 5 years ago, and I'm still waiting 😞 

Once the API is available, the extension will be updated.

Hope this helps.

/duplicate #76
