### ISSUE TITLE
[BUG] - Favorites are not shown if it is filtered by tags and all projects are removed

### ISSUE THREAD

**Issue by mohas** [alefragnani/vscode-project-manager#557]
**Environment/version**

- Extension version: 12.4.0
- VSCode version: 1.62.0
- OS version: Win 10

**Steps to reproduce**

1. add projects to favorites
2. add a tag to any or all of them
3. filter favorites by that tag
4. remove all projects containing that tag from favorites
5. now you cannot remove tag filter saing `No tags available/defined` all untagged projects are hidden and you cannot access them
NOTE: this only happens if that tag was the only tag for your projects
I think that what happens is that the extension searches the projects in the favorites for tags and if it finds any it shows the tag selection prompt, but the error situation happens when there are no more projects with tags left in the favorites but the tag filter is active

**Comment by alefragnani** [comment]
Hi @mohas ,

I can reproduce the issue. 

Thanks for reporting.
