### ISSUE TITLE
Issue with search

### ISSUE THREAD

**Issue by wallverb** [alefragnani/vscode-project-manager#56]
Turns out that Project Manager causes this issue: https://github.com/Microsoft/vscode/issues/12709

If I uninstalled Project Manager - it is ok, as soon as I install - I get that issue.
Version: 0.10.0

**Comment by wallverb** [comment]
Sorry, turns out to be different extension. project-manager is awesome 👍

**Comment by alefragnani** [comment]
No problem. Good to know :+1:
