### ISSUE TITLE
[BUG] - vscode-project-manager-core git submodule points to invalid revision

### ISSUE THREAD

**Issue by akosyakov** [alefragnani/vscode-project-manager#560]
**Environment/version**

- Extension version:
- VSCode version: 
- OS version: 

**Steps to reproduce**

1. 
2.

**Comment by alefragnani** [comment]
Hi @akosyakov ,

The `vscode-project-manager-core` submodule is _private_ (because the extension is not fully open source anymore) so you won't be able to clone/build.

I was planning to reopen pieces of it, but I had to postpone.
