### ISSUE TITLE
[FEATURE] Remove watchFile interval (use the Node's default)

### ISSUE THREAD

**Issue by nidefawl** [alefragnani/vscode-project-manager#575]
I noticed that this extension checks json file for changes 10 times per second.
A user setting to make that interval higher or turn it off would be nice.

**Comment by alefragnani** [comment]
Hi @nidefawl ,

Wow, I didn't notice the polling, and I don't see why it would be that short.

Instead of a setting, I prefer simply remove that, and use the default value provided by Node (5s by docs). 

Thanks for pointing that out.
