### ISSUE TITLE
Conditionally open a new project in the current window, or a new window

### ISSUE THREAD

**Issue by sondrele** [alefragnani/vscode-project-manager#58]
I'm working on several projects during a day, and the possibility to switch between them is quite vital (thanks btw! :smile: ). I prefer to work on a single project at a time if I can, but a new feature might touch several of these projects so that I will need to have them all open in separate windows.

Thus, I would really like the ability to choose whether or not to open a new project in the current window, or in a new window, depending on whether the task I'm working on extends over several projects or not.
There's already the `projectManager.openInNewWindow` setting that partly solves the issue I'm having, but I would like to make this decision _when_ I'm opening a new project.
I guess #50 could also solve the problem I'm having, but that might take a while.

Out of the top of my head I can come up with two different approaches to configure this (might also be beneficial with some new settings to configure whether you want this behavior or not):

1. A new shortcut, e.g. `Ctrl+Shift+Alt+P` that opens a new project in the same window, and `Shift+Alt+P` to open a new project in a new window (I prefer this).
2. A pop-up that asks whether to open in a new window or not (Intellij, as an example, does this by default).

What do you think?

**Comment by alefragnani** [comment]
Hi @sondrele ,

I recently released a new command **Project Manager: List Projects to Open in New Window** which does exactly what you suggested first. It will always open the project in a new window, no matter what you define in `projectManager.openInNewWindow`. 

![Commands](https://github.com/alefragnani/vscode-project-manager/raw/master/images/project-manager-commands.png)

You only need to define a `keybinding` to that 😄 .

Hope this helps.

**Comment by sondrele** [comment]
Awesome, just what I was looking for. Thank you again! :)
