### ISSUE TITLE
[FEATURE] - Color of the VSCode workspace

### ISSUE THREAD

**Issue by majkinetor** [alefragnani/vscode-project-manager#582]
[Peacock](https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock)  allows for VS to have specific color when loading specific workspaces. 

That feature naturally belongs to this plugin and color option should be among json options.  Using both plugins decouples configurations.

**Comment by alefragnani** [comment]
Hi @majkinetor ,

This extension is not designed to manage workspace configurations (settings, extensions, colors, etc) but instead, to give you quick and easy access to your projects.

Sometime ago, someone asked a similar question (#303), but he didn’t know (at first) about Peacock, and raised the possibility of both extensions to interact. But in the end, nothing happened, neither from Peacock side. 

I’m not sure how Peacock works, neither if it does exposes an API. If the interaction is easy I could take a look.

Let’s see if we get enough users upvoting this idea.

Thank you

**Comment by majkinetor** [comment]
> I’m not sure how Peacock works, neither if it does exposes an API.

That is irrelevant. Its not point of two separate extensions handling projects. Since Peacock is open source you could copy main functionality.

>  to give you quick and easy access to your projects.

Yeah, its quick and easy, but on random moment identification on which project I am currently at is highly problematic. I quite often work in wrong project and then when I load correct one my existing tabs are gone which sux. So this becomes nor quick, nor easy.

Its not specific to this tool, many other tools have this. Its tremendously helpful and can even prevent major mistakes - for example, production environment in database could be set to have red color so its highly unlikely that you will by accident think that you work on non-production environment.

**Comment by alefragnani** [comment]
> That is irrelevant. Its not point of two separate extensions handling projects. Since Peacock is open source you could copy main functionality.

I’m sorry to say, but that’s totally relevant. This extension **only manages access** to projects, not how such projects are displayed/configured. No matter if Peacock is open source or not, I’ll not copy its source to my extension. Even worst, to do something that my extension doesn’t intend to. The only way such feature could be added to this extension is via _integration_.

> for example, production environment in database could be set to have red color so its highly unlikely that you will by accident think that you work on non-production environment. 

What you need is a quick way to **identify** your projects, **based on some rule**. This is not the scope of this extension. 

Your best chance will be customize Peacock itself, adding this **rules concept** to create/apply colors to your projects.

Hope this helps

**Comment by majkinetor** [comment]
Fair enough. 

Thanks for discussion.
