### ISSUE TITLE
[FEATURE] - Use double click instead of single click

### ISSUE THREAD

**Issue by gavin-c-tcg** [alefragnani/vscode-project-manager#592]
I hope to provide a switch function on setting to replace the single-click switching workspace function with a double-click. 

This prevents mistakes

**Comment by alefragnani** [comment]
Hi @gavin-c-tcg ,

VS Code does not provide APIs for extensions to define single/double clicks. 

On the other hand, VS Code itself has a setting for you to control how to open items in trees and lists. This is its description:  **_Controls how to open items in trees and lists using the mouse (if supported). Note that some trees and lists might choose to ignore this setting if it is not applicable._** 

You should add the setting below to your User Settings.

```json
    "workbench.list.openMode": "doubleClick"
```

I just tested and the extension works as expected

Hope this helps
