### ISSUE TITLE
"projectManager.projectsLocation" is not working on OSX

### ISSUE THREAD

**Issue by FuriouZz** [alefragnani/vscode-project-manager#60]
I am OSX El Capitan 10.11.4 and I use VSCode Insider 1.7.0-insider.

When I set `projectManager.projectsLocation` to the stable VSCode `projects.json`, no project found. It returns me the info : "No projects saved yet.".

My user settings :

```json
{
  "projectManager.projectsLocation": "/Users/username/Library/Application Support/Code/User/projects.json"
}
```

**Comment by FuriouZz** [comment]
OK. I fixed the issue... I must precise the directory and not the `projects.json` directly. Is it not better to precise a `json` file ?

**Comment by alefragnani** [comment]
Hi @FuriouZz , 
Good to know that you figured out the correct configuration. :+1: 

I decided to use _folder_ instead of _file_ for simplicity. Thinking in the future, if new files need to be created, no other config needs to be made.

Hope this helps.

**Comment by muuvmuuv** [comment]
Came to the same problem, would be nice if you could notice that in the README for others

**Comment by peacefulseeker** [comment]
Also spent quite a time to realize, that just directory needed without the `project.json` filename in it. 🤷
