### ISSUE TITLE
[FEATURE] - Azure Data Studio integration

### ISSUE THREAD

**Issue by VASKOTechDesign** [alefragnani/vscode-project-manager#600]
Hello,

first of all, thank you for your extension in VS Code, my question is whether you have a plan to implement this extension also in "Azure Data Studio"? Would be very helpful.

Thank you

Jan Vaško

**Comment by alefragnani** [comment]
Hi @VASKOTechDesign ,

I just discovered about ADS a few months ago, when #558 was opened. Searching for updated docs, I didn’t find any news about it, nor better documentation on how to enable/update/migrate the extension to be ADS. 

So, for now, I won't spend efforts to publish it there. If, in the future, the Azure Data Studio become an oficial channel for VS Code extensions, like Codespaces/GitHub.dev/vscode.dev, I would be glad to make the extension to work there.

Hope this helps
