### ISSUE TITLE
[BUG] - github keeps open google page cannot find 

### ISSUE THREAD

**Issue by eddies8200** [alefragnani/vscode-project-manager#603]
**Environment/version**

- Extension version:
- VSCode version: 
- OS version: 

**Steps to reproduce**

1. 
2.

**Comment by alefragnani** [comment]
Hi @eddies8200 ,

Please, could you provide more details?

Thank you

**Comment by eddies8200** [comment]
Thank you for following up on my request but I solved the problem
Thank you Mr. Fragnani
