### ISSUE TITLE
alx git project

### ISSUE THREAD

**Issue by DAVE2456** [alefragnani/vscode-project-manager#604]
**Environment/version**

- Extension version:
- VSCode version: 
- OS version: 

**Steps to reproduce**

1. 
2. 

>

**Comment by alefragnani** [comment]
Hi @DAVE2456,

Please, could you provide more details?

Thank you

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been added since my last question. 

Thanks for your understanding
