### ISSUE TITLE
[FEATURE] - Documentation on Docusaurus

### ISSUE THREAD

**Issue by KarlGusta** [alefragnani/vscode-project-manager#607]
A documentation site, hosted on GitHub. We can use Docusaurus to create the documentation. Docusaurus.io is really simple and easy to navigate to read docs.

This makes it easier for new users to understand the steps to add their projects. I would love to help out with the documentation if that is okay. 

If also, just having a Docs folder with each step separated for easy digestion sounds good then, let's do this @alefragnani

**Comment by alefragnani** [comment]
Hi @KarlGusta ,

Thanks for your suggestion, but a similar request to improve documentation already exists (#394), and personally, I prefer an _inside repository_ approach.

I’m also planning to use the new Walkthrough feature, which is displayed inside VS Code, which is being tracked in #517. This one in particular, I already started producing some content, but no ETA to be available, yet.

Feel free to open a PR with the documentation idea you have, so we can chat about it and improve.

**Comment by KarlGusta** [comment]
Great @alefragnani When the walkthrough documentation is released, `project manager` will be among the most installed. It has so much to offer that people don't get it yet. I'll work on the documentation with fresh eyes since I'm beginning to understand more here.
