### ISSUE TITLE
[FEATURE] - Categorization of projets

### ISSUE THREAD

**Issue by ilcontabile** [alefragnani/vscode-project-manager#611]
Could you please implement a system to create and move projects in sub-folders?
Many thanks

**Comment by alefragnani** [comment]
Hi @ilcontabile ,

To _organize_ the project, the extension provides a feature called [Tags](https://github.com/alefragnani/vscode-project-manager#project-tags---view-and-filter). 

Right now it is only supported for **Favorite** projects (those you save using the `Project Manager: Save Project`) command, but I'm planning to expand such feature for the auto-detected projects as well.

Hope this helps
