### ISSUE TITLE
[FEATURE] - Improve (Git) repository view 

### ISSUE THREAD

**Issue by lfvjimisola** [alefragnani/vscode-project-manager#615]
The Git repository view could be improved in two ways:

1. Make it possible to search/filter live using custom string (on git repo name and path)
2. Make it configurable to show more than just repository name. We have a lot of repositories with the same name (see screenshot), e.g. due to use of submodules.

![Screenshot from 2022-06-21 10-01-33](https://user-images.githubusercontent.com/85176191/174748266-c5d311d4-bddc-4197-b554-da9e698e14ea.png)

**Comment by alefragnani** [comment]
Hi @lfvjimisola ,

* About the search/field feature is already being tracked in #213 
* About more details in the side bar, specifically for those _same name repositories_, I suggest you to take a look at `projectManager.showParentFolderInfoOnDuplicates` and `projectManager.ignoreProjectsWithinProjects` settings. I think at least one of them should help you.

Hope this helps

**Comment by lfvjimisola** [comment]
@alefragnani Sorry for taking your time. I totally missed those two settings. The showParentFolderInfoOnDuplicates is what I wanted (still want to show submodules aka "projects within projects").

Following #213 now.

Thank you for a very useful extension :pray:
