### ISSUE TITLE
Linux users see "Reveal in Finder"

### ISSUE THREAD

**Issue by arcanistzed** [alefragnani/vscode-project-manager#618]
https://github.com/alefragnani/vscode-project-manager/blob/4e8b7ddf030ed005aaca9393c67f28d7ca9f4b19/src/commands/revealFileInOS.ts#L14

Since I have never used Mac, it took me a while to figure out what the context menu option does :rofl: 
I think it would be more appropriate to name it "Reveal in File Manager" which is a more neutral wording

**Comment by alefragnani** [comment]
Hi @arcanistzed ,

I remember using no more than 3 Linux distributions (Conectiva and RedHat back in the KDE/Gnome war era) and a few years ago a bit of Ubuntu, and couldn't figure out which file manager they used as well 😆 . The only name I remember is Nautilus.

If `File Manager` is a more neutral working, I see no reason why it should be used in the extension.

Thanks for reporting
