### ISSUE TITLE
Error loading projects: ${reason}

### ISSUE THREAD

**Issue by renatomestre** [alefragnani/vscode-project-manager#62]
![error_switching](https://cloud.githubusercontent.com/assets/3286138/19743369/cda56f88-9ba7-11e6-837c-8279a8da9619.png)

Occurs on switching any project.

Version 0.11.0
Win 10 x64

**Comment by renatomestre** [comment]
VS Code was deprecated (1.5.1).

On VS Code 1.6.1 it works. My bad.

**Comment by alefragnani** [comment]
Hi @renatomestre , good to know it's working 👍
