### ISSUE TITLE
[BUG] - No "Git" tab in Project Manager.

### ISSUE THREAD

**Issue by jeti20** [alefragnani/vscode-project-manager#620]
- Extension version: v12.6.0
- VSCode version: version 1.69
- OS version:  Windows 10

**Steps to reproduce**
1. Install project manager

Hi, I have been struggling with this problem entire day and decided to ask how can I fix it.  I feel like a I miss something stupid, but I cannot fix it :(

I downloaded and installed VS Code on two computers. Then I downloaded the Project Manager. And on one computer I don't see the Git tab in Project Manager, and on the other computer it showed up without any problems... Do any of you know how to solve this problem?
 

I'm connecting to the server via SSH if that matters. I also added
"remote.extensionKind": {
         "alefragnani.project-manager": [
             "workspace"
         ]
     },
![3](https://user-images.githubusercontent.com/61649661/179015740-fee52e76-3775-432a-bd80-558df3953835.png)
![2](https://user-images.githubusercontent.com/61649661/179027651-cee89f2d-8ff1-4f72-97e6-819dc481086f.png)
![1](https://user-images.githubusercontent.com/61649661/179016347-c2d722fa-0c74-4f12-bb67-b8410deafe13.jpg)

**Comment by jeti20** [comment]
It can be closed.  I was not aware these posts.
![image](https://user-images.githubusercontent.com/61649661/179198790-af2ed12d-9691-42f7-b025-f9752a574d51.png)

I found solution in this post: https://github.com/alefragnani/vscode-project-manager/issues/578

It works for me:
"Do you mean inside the Project Manager view, you only see Favorites view, but no Git or Help and Feedback? If that's the case, I suggest you to click in the ellipsis button, located at top-right of Project Manager view, and be sure the Git view is selected." 
![image](https://user-images.githubusercontent.com/61649661/179200022-d1d4b761-1100-4a67-9a86-0bd42d7bcee9.png)



Life is beautiful again. Thank you.

**Comment by alefragnani** [comment]
Hi @jeti20 ,

That's great to see you found the solution. Enjoy the extension 😄
