### ISSUE TITLE
Project Manager can't display directory of project

### ISSUE THREAD

**Issue by csbo98** [alefragnani/vscode-project-manager#627]
After a complete uninstall of vscode on MacOS, I install vscode again. After that, I install the Project Manager, however, the Project Manager doesn't display the project normally. 
I have saved some project using "Project Manager: save project" command, but when I click the Project Manager icon      in the activity bar, it displays as follows:  
<img width="307" alt="截屏2022-07-24 19 31 40" src="https://user-images.githubusercontent.com/67197317/180644935-ed594482-d4ec-4fb4-bd98-eaf89600adc8.png">

**Comment by alefragnani** [comment]
Hi @csbo98 ,

The view/panel position is managed by VS Code, and maybe something failed/was lost.

I see two alternatives to try to fix this:

- You could use `Project Manager: Focus on ... View` command, to focus/display the Favorites view (and identify where it is)

- You could use `View: Reset View Locations`, to reset all views, from all extensions. The downside of this alternative is that any customization you has made on view's location will be lost, and every extension will return the its default location,

Hope this helps

**Comment by csbo98** [comment]
Thanks for your quick reply!

**Comment by csbo98** [comment]
Thanks for your quick reply! Although the reason is unknown, the "View: Reset View Locations" command solves my problem.
