### ISSUE TITLE
showProjectInStatusBar does not work

### ISSUE THREAD

**Issue by leomikezee** [alefragnani/vscode-project-manager#63]
<img width="168" alt="screen shot 2016-10-28 at 2 57 32 pm" src="https://cloud.githubusercontent.com/assets/7655600/19818684/e2fd306e-9d1e-11e6-99c8-2ac44fc0747c.png">
When I re-saved the project, the project showed in the status bar. However, when I switched to another project and then switched back, the status disappeared.
Using VSCode 1.6.1 on macOS Sierra

**Comment by leomikezee** [comment]
Problem solved.
You have to re-save all the projects.

**Comment by alefragnani** [comment]
Hi @leomikezee ,

What do you mean about _re-saved the project_? Are you updating it's path/name using the `Save Project` command, or updating the `projects.json` file yourself?

**Comment by leomikezee** [comment]
@alefragnani 
I updated the project using `Save Project` command.

**Comment by alefragnani** [comment]
Ok, I will take a look tomorrow. Stay tunned 👍

**Comment by alefragnani** [comment]
I tried a few times, but instead of a _missing status bar_, I've got a _duplicate status bar_, with the _older_ and _newer_ project's name :) That's probably related, so while fine tuning the Status Bar feature, the error should appear.

Maybe you code write the steps to reproduce the error, or maybe record it? It would be really useful.

**Comment by leomikezee** [comment]
@alefragnani So when I open a project through `List Projects to Open`, the status bar shows nothing
<img width="330" alt="screen shot 2016-10-31 at 10 38 41 pm" src="https://cloud.githubusercontent.com/assets/7655600/19878045/cbe6153c-9fba-11e6-8186-9d5b4c097662.png">
Then I re-save the project through `Save Project`, the status bar shows the project name.
<img width="690" alt="screen shot 2016-10-31 at 10 39 59 pm" src="https://cloud.githubusercontent.com/assets/7655600/19878064/07f9cac8-9fbb-11e6-9507-575c9ca0cf57.png">
<img width="275" alt="screen shot 2016-10-31 at 10 40 24 pm" src="https://cloud.githubusercontent.com/assets/7655600/19878065/07ff8ca6-9fbb-11e6-9438-faaef25f11fb.png">
Then I switch to another project and switch back through `List Projects to Open`, the project name on status bar disappear.
<img width="266" alt="screen shot 2016-10-31 at 10 41 56 pm" src="https://cloud.githubusercontent.com/assets/7655600/19878096/3e0a6abe-9fbb-11e6-87c4-7040dd318611.png">

**Comment by DavidBabel** [comment]
+1 VSCode 1.7.1 on macOS Sierra

**Comment by alefragnani** [comment]
There will be a new release with this fix later today
