### ISSUE TITLE
[BUG] - Listing files from outside of current folder

### ISSUE THREAD

**Issue by sumonst21** [alefragnani/vscode-project-manager#630]
**Environment/version**

- Issue Type: `Bug`
- Extension Name: `project-manager`
- Extension Version: `12.6.1`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.70.0`

**Steps to reproduce**

1. open/init a repo in code then 
2. open a file from nowhere that does not belongs to current dir/repo but another repo.

this will show all files & folder from that repo as changes for current repo.

![Listing files from outside of current folder](https://user-images.githubusercontent.com/7096865/183779883-6a29e02c-6eaf-413f-adac-890fa9c50cc6.png)

**Comment by alefragnani** [comment]
Hi @sumonst21 ,

This issue is not related to this extension. Instead, it appears to be related to some **Git** extension, maybe GitLens, which if I remember correctly, it's the one that adds this `Commits` panel to the Source Control Side Bar.

Hope this helps
