### ISSUE TITLE
[FEATURE] - The set tag is automatically added

### ISSUE THREAD

**Issue by jipika** [alefragnani/vscode-project-manager#632]
You want to automatically add the set tag before or after the project name so that you can see in the status bar that it belongs to that tag group

**Comment by alefragnani** [comment]
Hi @jipika ,

I'm using #551 to track improvements on how Tags works, and there is already a comment suggesting the same idea, even tho I still didn't defined exactly what/how those improvements will happen. My first idea was to use a _wizard way_ to add tags, instead parse the input, but the idea is on the table.

Please, upvote and/or subscribe to that issue, so you will receive updates on that.

Thank you.
