### ISSUE TITLE
[FEATURE] - Remove Project from Workspace through Command Palette

### ISSUE THREAD

**Issue by ao10** [alefragnani/vscode-project-manager#633]
When I open the command palette, I'd also like to be able to remove projects in my workspace without having to manually remove each one from the GUI. It should have similar filtering and autocompletion as the "Add Project to Workspace" . 

Let me know if this makes sense. This feature would save a lot of time as I find myself constantly removing and adding projects during my workflow and would love to just stick with my keyboard/command palette.

I'd be more than happy to work on this as well to submit a PR. Thanks again for this awesome extension!

**Comment by alefragnani** [comment]
Hi @ao10 ,

Thanks for your kind words. I'm glad to know you like the extension.

About your request, are you aware VS Code already has a `Workspaces: Remove Folder from Workspace...` command? It will present you the list of folders contained in the Workspace, and you just have to select it and it will be removed.

I guess fit your needs.

Hope this helps

**Comment by ao10** [comment]
Ah didn't know this command existed under `Workspaces`. I usually open the command palette and start typing `Project Manager`. Thank you!

**Comment by alefragnani** [comment]
Yeah, this `Workspaces:` prefix means this command is _native_ in VS Code. The commands from the `Project Manager` extension will always start with `Project Manager: `. 

It's a _convention_ for extensions to create its own prefix 😬
