### ISSUE TITLE
[FEATURE] - highlight opened folder

### ISSUE THREAD

**Issue by kzhui125** [alefragnani/vscode-project-manager#636]
I saved many projects, for example: at a time I may be opening 5 of them.

I want to highlight opened folder, so I can quickly switch between the 5 folder.

**Comment by alefragnani** [comment]
Hi @kzhui125 ,

A similar request already exists (#299), but the idea is to highlight the _current_ project instead. It is on the Backlog for upcoming releases.

I'm not sure you are aware of, but VS Code itself provides a `Switch Window...` command, which allows you to switch between open windows. It was released a few releases after I asked for an API exactly for that purpose, but instead they gave us a native command. Way better 😄 

Hope this helps
