### ISSUE TITLE
[FEATURE] - Add localization support to the welcome view in the Sidebar

### ISSUE THREAD

**Issue by TheCodingDead** [alefragnani/vscode-project-manager#638]
**Environment/version**

- Extension version: v12.6.1
- VSCode version:  1.7
- OS version: macOS 12.5.1

**Steps to reproduce**

1. install project manager 
2. click project manager's icon on activity bar. 

<img width="574" alt="截屏2022-08-22 13 05 36" src="https://user-images.githubusercontent.com/110464411/185843607-67c424a4-3d71-4a98-9194-7c61309d59e1.png">

**Comment by alefragnani** [comment]
Hi @TheCodingDead ,

The localization depends on external contributions so, I'll leave it open for PRs. Feel free to contribute, if you feel comfortable.

Hope this helps.
