### ISSUE TITLE
How to hide a file or folder from sidebar (not exclude) for a project?

### ISSUE THREAD

**Issue by jitendravyas** [alefragnani/vscode-project-manager#64]

**Comment by alefragnani** [comment]
If you want to _hide_ files from _Explorer_ SideBar, you must take a look at `"files.exclude"` config ([more info](https://code.visualstudio.com/Docs/customization/userandworkspace)). It's a Visual Studio Code _core_ concept, not related to this extension 😄 

Hope this helps.
