### ISSUE TITLE
[FEATURE] - Search Bar in not found

### ISSUE THREAD

**Issue by iamgaddiel** [alefragnani/vscode-project-manager#648]
A search bar for project names would be really helpful

**Comment by alefragnani** [comment]
Hi @iamgaddiel ,

Unfortunately, VS Code does not provide an API for that. Instead, they automatically add a so called `Tree Find control` (https://code.visualstudio.com/updates/v1_70#_tree-find-control), for every Treeview.

Just recently I added a `Find` button on each panel of the Project Manager side bar, to list its projects.

Hope this helps
