### ISSUE TITLE
[FEATURE] - Option to locate in Explorer tab on Activity Bar

### ISSUE THREAD

**Issue by binaryben** [alefragnani/vscode-project-manager#649]
As title says, would it be possible to add an option to move the extension to the explorer tab. This would be similar to how popular git extensions like GitLens can extend the default git tab or use their own tab.

**Comment by alefragnani** [comment]
Hi @binaryben ,

VS Code already supports drag & drop of views / panels. With that, you can easily move any of the Project Manager panels to whatever location, either the Explorer tab, bottom panel or the Secondary Side Bar. And you are free to choose which panel (Favorites, Git, SVN) to move, individually.

Do you think an additional command/option, like the one provided by GitLens, is really necessary?

**Comment by binaryben** [comment]
Amazing, thank you for pointing out the feature for me. That will serve me well!
