### ISSUE TITLE
Support for --user-data-dir

### ISSUE THREAD

**Issue by tleepa** [alefragnani/vscode-project-manager#65]
When running VSCode.exe you can specify this flag to point to the user data directory.
However, the extension looks for the process.env.appdata to set up the base to build projectFile path (extension.js, var appdata = ... in the getProjectFilePath function).
It would be great, if it could support the --user-data-dir.
One way could be to start with process.env.VSCODE_HOME and leave out the channelPath.

Please, note that I am not a developer and I only did "find" the issue. The above "solution" is just a general idea and Windows specific. Linux supports this flag too (most likely so does Mac)...

**Comment by alefragnani** [comment]
Hi @tleepa ,

The idea behind `projectManager.projectsLocation` is to allow the user to define a _different location_ for its `projects.json` file, either for _sharing_, _ sync_ or _custom rules_. You could use that, if you always use the same `--user-data-dir`. (just a tip).

I don't know if there is an API to access `--user-data-dir` parameter. In fact there are some opened issues around VS Code internal folders (data, extensions, etc). But it makes sense, if it allows you to define _a different_ folder for its data, to _use_ this folder in the extension. Even better if `process.env.appData` should be _updated_ to reflect `--user-data-dir`.

Stay tuned.

**Comment by alefragnani** [comment]
Depends on https://github.com/Microsoft/vscode/issues/2741

**Comment by medikoo** [comment]
I approached very same problem, hopefully they provide requested API in VSCode

**Comment by alefragnani** [comment]
There is no ETA for the VS Code API to be available, and so, I'm closing the issue.
