### ISSUE TITLE
[BUG] - The status bar does not show the name of the currently loaded project when using a relative path.

### ISSUE THREAD

**Issue by jaronfort** [alefragnani/vscode-project-manager#650]
**Environment/version**

- Extension version: latest
- VSCode version: latest
- OS version: Windows 11 Pro 10.0.22621 Build 22621 (also experienced on macOS)

**Steps to reproduce**

1. Create a new workspace.
2. Save the workspace as a project.
3. Open up the `projects.json` file and change the workspace path of the new project to use `~/Documents/MyProjects/my-project.vscode-workspace` (instead of `c://Users/Me/Documents/MyProjects/my-project.vscode-workspace`.
4. Open the project using the project manager.
5. Notice the project is not showing in the status bar with no "Hide/Show 'Project Manager'" open in the right-click menu.

**Comment by alefragnani** [comment]
Hi @jaronfort ,

I'm not sure this is a Windows related issue, but I couldn't reproduce the error on my MacOS. 

The `~` shortcut is supported on project paths and it seems to be properly _expanded_ on project detection of the Status Bar, so it is really weird it is not working in your case.

Btw, does the project path is properly displayed (expanded) when you hover the project in the Project Manager - Favorites view? It should display

```
Project Name
c:/Users/Me.... (expanded path)
Icon Workspace
```

Hope this helps

**Comment by jaronfort** [comment]
Sorry, I made a mistake. It is actually working fine for me on macOS. I
tried replacing the paths to use the "/" delimiter instead of "\" (which is
escaped in the string literal as "\\") and still no luck.

[image: screenshot.1.jpg]
I also confirmed that I can see the project path, workspace icon, and
project name when I hover over it in the favorites view.

Btw. Thanks for creating this extension. This has definitely improved my
workflow.

**Comment by alefragnani** [comment]
Just to let you know, I could reproduce the error on a Windows machine, and neither `$home` keyword is working.

So, it is definitely something OS specific.

Thanks for reporting

**Comment by jaronfort** [comment]
No problem.

**Comment by sdak75** [comment]
Hi,
I had the same problem on Windows and was able to resolve it by removing the \\ at the end of the path.
Best regards
