### ISSUE TITLE
[BUG] - Project manager fails to activate when projectManager.supportSymlinksOnBaseFolders is true and baseFolders contains invalid path.

### ISSUE THREAD

**Issue by ParaSpl01t** [alefragnani/vscode-project-manager#657]
**Environment/version**

- Extension version: v12.7.0
- VSCode version: 1.74.0
- OS version: 6.0.11.arch1-1

**Steps to reproduce**

1. Install Project manager
2. Add your real project directory to Any:Base Folders
3. Add some non-existent directory to Any:Base Folders
4. set "projectManager.supportSymlinksOnBaseFolders": true
5. close and reopen VSCode

After these steps project manager sidebar will not show anything at all not even refresh button.
In Console, there's this error message : 
```
Activating extension 'alefragnani.project-manager' failed: ENOENT: no such file or directory, lstat '/home/otherpcusername/dev/projects'.
$onExtensionActivationError	@	workbench.desktop.main.js:2155
``` 
![image](https://user-images.githubusercontent.com/18276917/206636499-34fc98f1-e9c7-478a-a41c-1783b67bcb8f.png)

**Scenario**
I'm currently using vscode in two seperate systems and syncing the extensions and settings between both. that's why my Any: Base Folder contains one correct path and one incorrect path.
I'm don't use windows so can't tell if it's OS specific or not. but this might have something to do with #655 
If there's more info I can provide please let me know.

**Comment by alefragnani** [comment]
Hi @ParaSpl01t ,

I could repro the issue, and I suppose it is not OS specific. 

Thanks for reporting
