### ISSUE TITLE
[FEATURE] - Show the project name as as the Explorer bar's title

### ISSUE THREAD

**Issue by gee-forr** [alefragnani/vscode-project-manager#658]
Firstly - thank you for this extension, it makes managing multiple projects much simpler. It's extremely appreciated.

It would be great if it was possible to show the current project name as the heading of the Explorer panel, instead of having "EXPLORER" just sitting there being frankly quite useless.

It's probably easier if I describe what I'm talking about by showing you a picture instead...

![image](https://user-images.githubusercontent.com/345730/206726380-525bda4a-7324-4a7c-b90d-5e4ceef99493.png)

**Comment by alefragnani** [comment]
Hi @gee-forr ,

First of all, thank you for your kind words. I'm glad to know the extension is being helpful! 

About your request, unfortunately not. That `Explorer` heading is the built in Explorer View, and is not touched by the extension. And, AFAIK, there is no API to customize that info, yet.

So, I suggest you to request that to the VS Code team itself (https://github.com/microsoft/vscode/issues/new/choose), maybe they could look at it in the future.

Hope this helps.
