### ISSUE TITLE
[BUG] - sync

### ISSUE THREAD

**Issue by stan-ac** [alefragnani/vscode-project-manager#662]
**Environment/version**

- Extension version:
- VSCode version: 
- OS version: 

**Steps to reproduce**

- I have worked successfully with project manager for quite a while.
- I then started using a new computer, on which I added project manager to vs code.
- I then tried to sync the two machines to pull the changes over. 
- I have not used (or even powered up) the new machine since. However I discovered that on the previous computer I am no longer able to use project manager. It seems to have tried to pull sync data in from the new computer, and shows the startup "no projects saved yet" intro panel. 
-  I turned off sync and tried to move on:
- The previous data still exists and when I looked at the json file I saw the previous projects and tags
- When I try to save a project or get a list of projects, nothing moves past the intro screen. 
- If I save a new project it seems to save it but the intro screen persists
- If I try save an existing project it will say this project already exists, but I cannot get a list of them.
- I tried various things like changing the json, removing and re-adding the extension but to no avail, so I'm out of options and cannot use it.

**Comment by alefragnani** [comment]
Hi,

Please, could you provide more details?

Thank you

**Comment by stan-ac** [comment]
Added above ..

**Comment by alefragnani** [comment]
The extension doesn’t support Settings Sync, that’s the reason why you don’t see your projects on the other computer.

The support was being planned in #431, which depended on the VS Code team to provide an API. But just recently, the VS Code team decided to not release that API anymore, so in order to sync projects, an alternate solution will ve to use Gist, which is being tracked in #525.

I suggest you to upvote #525, so I’ll be able to know how many users desire it, and you will be notified when the feature is released.

Hope this helps

**Comment by stan-ac** [comment]
To be honest It's not that  important to me at this stage. 
HOWEVER right now I cannot use the project manager at all as I described above, and uninstalling does not help. 
so if you can explain what to do to revert to a clean state I'd appreciate it. 
Thanks

**Comment by alefragnani** [comment]
If that’s not important (sync), why did you commented _ I then tried to sync the two machines to pull the changes over._? Also, you didn’t mention if you are using the _old_ Settings Sync extension (https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync), or the native solution (https://code.visualstudio.com/docs/editor/settings-sync).

If you are using the _old_ extension, maybe that extension is responsible for the _missing_ projects, as it supports my extension.

Technically speaking, the projects you save are stored in a single `projects.json` file. The auto detected projects are stored in the same folder, in a separate files. If you have projects in `projects.json` but they don’t appear in project list/side bar, maybe you have tags defined and are facing #561 , #557 or #594, and I would suggest you to remove tags. Or you disabled the project. There is no _clean up_ feature for extensions, so any _state_ the extension stored is maintained even if you reinstall the extension.

Hope this helps

**Comment by stan-ac** [comment]
It's not that important to me - the reason I mentioned it is because that was the cause of the problem and I included it to help you understand what happened. 
Thanks for the input I appreciate it.
