### ISSUE TITLE
[FEATURE] - A feature to sync projects across all devices

### ISSUE THREAD

**Issue by CanePlayz** [alefragnani/vscode-project-manager#670]
Title says it all. Despite projects being tied to local paths on your device, this would be really useful for me as I use the cloud to store my projects hence all of my projects are under the same path, no matter which device I'm on. Could be added as an optional setting.

**Comment by alefragnani** [comment]
Hi @CanePlayz ,

There is already #525 requesting this. The idea is to use GitHub Gist to host the project list. 

Feel free to upvote.

Hope this helps

**Comment by CanePlayz** [comment]
> Hi @CanePlayz ,
> 
> There is already #525 requesting this. The idea is to use GitHub Gist to host the project list. 
> 
> Feel free to upvote.
> 
> Hope this helps

Thanks for making me aware, another thing that I've missed yesterday...
