### ISSUE TITLE
[FEATURE] - Let us enter a new path when a project has been moved

### ISSUE THREAD

**Issue by CanePlayz** [alefragnani/vscode-project-manager#671]
Currently, when a project has been moved, you need to delete it and create a new one. A feature where you can enter the new project path when the message that the project couldn't be found pops up would be really helpful.

**Comment by alefragnani** [comment]
Hi @CanePlayz ,

It already does that. When you select a project with an invalid path, the extension warns you and gives you the option `Update Project`, which will open `projects.json` file. There, you can freely edit it's path. 

![edit project](https://user-images.githubusercontent.com/3781424/218087450-2a04deae-0320-49e1-9bd9-d4e5a309510a.png)

Hope this helps

**Comment by CanePlayz** [comment]
> Hi @CanePlayz ,
> 
> It already does that. When you select a project with an invalid path, the extension warns you and gives you the option `Update Project`, which will open `projects.json` file. There, you can freely edit it's path. 
> 
> ![edit project](https://user-images.githubusercontent.com/3781424/218087450-2a04deae-0320-49e1-9bd9-d4e5a309510a.png)
> 
> Hope this helps

Thanks. I must have missed that yesterday, sorry. 😬

**Comment by CanePlayz** [comment]
> Hi @CanePlayz ,
> 
> It already does that. When you select a project with an invalid path, the extension warns you and gives you the option `Update Project`, which will open `projects.json` file. There, you can freely edit it's path. 
> 
> ![edit project](https://user-images.githubusercontent.com/3781424/218087450-2a04deae-0320-49e1-9bd9-d4e5a309510a.png)
> 
> Hope this helps

Thanks. I must have missed that yesterday, sorry. 😬
