### ISSUE TITLE
[FEATURE] - List git projects by used times

### ISSUE THREAD

**Issue by chouzz** [alefragnani/vscode-project-manager#674]
It would be really great if the extension can support list all git projects according to used times, for example, if I open one git project, this project should at the first in the list, but project should under this project.

Further more:
  It can support list git project according to "Last Opened", "Recently Updated", it would be really cool.

![image](https://user-images.githubusercontent.com/18023066/218628532-db8b449e-2709-4c34-95f5-9a36b875f9f4.png)

**Comment by alefragnani** [comment]
Hi @chouzz ,

There is already a `projectManager.sortList` setting, which supports `Recent` option. But it is limited to the `Project Manager: List Project to Open`, `Project Manager: List Project to Open in New Window` commands and the **Favorites** panel, but not for others, like Git. 

For the `List` commands, the result is _merged_, which means no matter which project you selected (Favorite, Git, etc).

Hope this helps

**Comment by chouzz** [comment]
OK. Thanks. Should be enough for me.
