### ISSUE TITLE
[BUG] - Project Manager not showing on sideBar

### ISSUE THREAD

**Issue by OmarOdaini** [alefragnani/vscode-project-manager#675]
A while ago the extension disappeared from the side bar. I uninstalled Vscode and reinstalled it again but it didn't help.

- Extension version:
Project Manager v12.7.0
- VSCode version: 
  Version: 1.75.1 (Universal)
  Date: 2023-02-08T21:34:59.000Z (5 days ago)
  OS: Darwin x64 22.2.0

- OS version: 
   Mac Ventura 13.1

Is there a setting that I might've accidentally set to hide or something.

<img width="708" alt="image" src="https://user-images.githubusercontent.com/26101260/218782166-51a674da-c1d9-4835-82f7-ede3ce0fc2a5.png">

**Comment by adamnator92** [comment]
I manage to resolved this issue by follow the option 2

https://github.com/alefragnani/vscode-project-manager/issues/641

**Comment by OmarOdaini** [comment]
Works thanks
