### ISSUE TITLE
[FEATURE] - Option to view full path of git projects

### ISSUE THREAD

**Issue by therosbif** [alefragnani/vscode-project-manager#678]
i have multiple projects in directories of the same name so differentiating between them is difficult in the `GIT` section.
It would be nice to have the option to display the path from the base folder to the git projet in grey similar to how it's done in Source Contol.

<img width="225" alt="Screenshot 2023-03-09 at 19 31 02" src="https://user-images.githubusercontent.com/55743301/224192580-de7abd86-44dc-4c50-8b7b-bba5d88d7a17.png">

**Comment by alefragnani** [comment]
Hi @therosbif ,

You have the same behavior if you turn on the `"projectManager.showParentFolderInfoOnDuplicates"` setting. 

```json
    "projectManager.showParentFolderInfoOnDuplicates": true,
```

Hope this helps
