### ISSUE TITLE
[FEATURE] - open the same project in differrent window 

### ISSUE THREAD

**Issue by lfire** [alefragnani/vscode-project-manager#682]
sometimes, I need to open the same project in two windows, which helps me to diff some codes. But when I open a new window, and click the project list, which is the same project, the new window will be closed, and open the pre window.

I holp it will support opening the same project in different windows, thx.

**Comment by alefragnani** [comment]
Hi @lfire ,

This is _by design_ not supported by VS Code. But, they provided a workaround, which is to use the `Workspace: Duplicate Workspace in New Window` command instead. 

It works perfectly, and I suggest you to try out.

Hope this helps

**Comment by lfire** [comment]
nice, thx.
