### ISSUE TITLE
[FEATURE] - Make the panels in the side bar equally height

### ISSUE THREAD

**Issue by nacengineer** [alefragnani/vscode-project-manager#691]
When I click on a project, in the the project left panel the Git pane always resizes to a fairly small size from what I had had it before clicking. Ideally persist the sizing when I drag it or make the git portion larger than the favorites. right now the default settings seems like 2/3 favs and 1/3 git... maybe just make it half.

**Comment by alefragnani** [comment]
Hi @nacengineer ,

The only piece that extensions has some _limited_ control is the initial size of their panels. Once you open a folder/workspace, the persistence/restore of its size/state is totally controlled by VS Code itself, just like any other _session state_ you see (editors, terminals, etc).

TBH, I never worried about panels _height_, as most of the times I'm looking for **Favorite** projects, but I totally understand your point. Maybe the panels could be _equally distributed_. It may be a bit tricky, as the extension may show up to 6 panels, but only the **Favorites** is always there.

I'll take a look on what can be done about it.

Thank you for your suggestion

**Comment by nacengineer** [comment]
bummer. Ah yes favorites would handle that probably for most use cases. We create a lot of projects (college library) so I usually use the pick list. I'll close this then as I'm probably more a niche case and the CMD+SHIFT+P list projects to open is an option too
