### ISSUE TITLE
[BUG] - Remote SSH "Not an Authority"

### ISSUE THREAD

**Issue by TheTaylorLee** [alefragnani/vscode-project-manager#693]
**Environment/version**

- Extension version: 12.7.0
- VSCode version: 1.80.0
- OS version: Windows 11

**Error Shown**
![image](https://github.com/alefragnani/vscode-project-manager/assets/53202926/353d34fe-237f-42c2-993e-9a620e668319)

**Steps to reproduce**

1. Use project manager to open a remote SSH workspace

- Workspace Config
```conf
{
    "folders": [
        {
            "name": "docker",
            "uri": "vscode-remote://ssh-remote+root@192.168.2.20/home/taylor/docker/appdata"
        },
        {
            "name": "dockerssd",
            "uri": "vscode-remote://ssh-remote+root@192.168.2.20/media/ssd/docker/appdata"
        },
        {
            "name": "github",
            "uri": "vscode-remote://ssh-remote+root@192.168.2.20/home/taylor/github"
        }
    ],
    "remoteAuthority": "ssh-remote+root@192.168.2.20",
    "settings": {
    },
}
```

**Comment by alefragnani** [comment]
Hi @TheTaylorLee ,

Could you detail how the workspace is stored in Project Manager extension? I mean, is it something like:

```json
        {
		"name": "My SSH Workspace",
		"rootPath": "~/Documents/Projects/MySSHConnection.code-workspace",
		"paths": [],
		"tags": [],
		"enabled": true,
		"profile": ""
	},
```

The extension doesn't do any _connection_ to the remote machine, but only asks VS Code to open to path/workspace/folder you did configure in `rootPath` property. So, if it says something about _authority_ when you open that workspace, I suppose it would do the same if you open the workspace via VS Code itself, using the native `File / Open...` command.

Hope this helps

**Comment by TheTaylorLee** [comment]
Thanks for the help. I tested opening the workspace directly and had the same issue. Seems like a bug with the new release of vscode.

```json	
{
		"name": "TALDocker",
		"rootPath": "g:\\github\\scripts\\VSCode\\Workspaces\\TALDocker.code-workspace",
		"paths": [],
		"tags": [],
		"enabled": true
	}
```

**Comment by TheTaylorLee** [comment]
For anyone running into this I found some error logs in the Terminal > Window output. It indicated that vscode is not treating the vscode app as a trusted path and causing remote ssh connections to fail. I added the following into vscode settings to bypass this issue.

It's related to these changes by Microsoft. 

https://github.com/microsoft/vscode/issues/182055

**Comment by alefragnani** [comment]
Thanks for pointing out the original VS Code issue. It can help other users for sure 👍

**Comment by TheTaylorLee** [comment]
Previous provided issue was incorrect and based of other issues referencing similar logs.

https://github.com/microsoft/vscode/issues/187202 

SSH was not considered during a change to remote authorities code base in VS Code. Fix supposedly has been pushed to insiders and hopefully will be in the next stable vs code release.
