### ISSUE TITLE
[FEATURE] - Show current active folder

### ISSUE THREAD

**Issue by jackiotyu** [alefragnani/vscode-project-manager#699]
utils code:
https://github.com/jackiotyu/git-worktree-manager/blob/99df4236323ee87385c809856caaf42a2e65e383/src/folderRoot.ts#L1-L33
https://github.com/jackiotyu/git-worktree-manager/blob/99df4236323ee87385c809856caaf42a2e65e383/src/utils.ts#L1-L13

example:
![image](https://github.com/alefragnani/vscode-project-manager/assets/31788042/8b68c4d4-328f-4f03-a587-9fa248f4bcc6)

Through the vscode workspace api, it can find the current folder uri easily. Maybe help to clearly show current working directory.
😀

**Comment by alefragnani** [comment]
Hi @jackiotyu ,

Could you provide more details about what is your request? What do you mean about _current active folder / current working directory_ in Project Manager extension?

Thank you

**Comment by jackiotyu** [comment]
![image](https://github.com/alefragnani/vscode-project-manager/assets/31788042/317cb3c4-f5b4-45a1-a880-3bd7f470881f)

Good day!, I mean that you can let the extension find the folder or workspace used by the current window, and if you can highlight it, you can clearly see the current working directory, which is convenient for switching and prevents misoperation at some times.

Just a suggestion😀

**Comment by alefragnani** [comment]
Hi @jackiotyu ,

Identifying the current folder and comparing with the project path is not an issue, as it is already made for the Status Bar item. The real issue in highlighting the project in the Side Bar, is the _highlighting_ itself 😀 .

I have played with in the past, but it wasn't that stable, so I leave it in the backlog to try again later. BTW, it's already being tracked in #299. 

It's been a long time, so maybe it is working better now. I'll try to revisit this for upcoming releases.

Thank you
