### ISSUE TITLE
Open Project in same window

### ISSUE THREAD

**Issue by Chandan-Nayak** [alefragnani/vscode-project-manager#70]
I can see two options in Commands to open projects

1. List Projects to Open
2. List Projects to Open in 

I believe the second one should open the selected project in the new window and the first one in the current window. For me both are doing the same - Opening the project in the new window.

Please guide me if i am doing anything wrong. My purpose is to find a way to open the new project at start in the same window.

Thanks!!

**Comment by alefragnani** [comment]
Hi @Chandan-Nayak ,

You are right, each one has it's own behavior, but the first one also respects the `"projectManager.openInNewWindow"` configuration. 

In the beginning, there was only the config and the first command. The second command was created more recently, for those users that have the config as `false` but _sometimes_ wants to open a project in a new window.

You can get more info in the `readme`

Hope this helps

**Comment by Chandan-Nayak** [comment]
Thanks!!
