### ISSUE TITLE
[BUG] - how can i debug or package vscode-project-manager-core

### ISSUE THREAD

**Issue by codegzx** [alefragnani/vscode-project-manager#703]
1. run yarn at root folder of the profect;
2. but then i found there is nothing in `../vscode-project-manager-core` and `../vscode-whats-new`.
3. then how to debug or package the project ;
![image](https://github.com/alefragnani/vscode-project-manager/assets/62829855/e32d0f15-41c4-45c3-a042-7fb7d9db49e1)

**Comment by alefragnani** [comment]
Hi @codegzx  ,

You can't debug it right now, because the core repo is not open source. 

I've plans to reopen it, as tracked in #498 . Probably in the upcoming releases, but no ETA.

Hope this helps
