### ISSUE TITLE
Set tag(s) while saving project

### ISSUE THREAD

**Issue by james-berkheimer** [alefragnani/vscode-project-manager#704]
I tried searching to see if this feature exists, but didn't find anything.  So forgive me if it does exist.  But it would be really nice if I could take a project while I'm saving it.  That would save a lot of clicks.

**Comment by alefragnani** [comment]
Hi @james-berkheimer ,

A similar (and a bit more generic) request has already been made in #551, and the idea was to use a _multi-step approach_. If you have any other suggestions, feel free to comment on that issue, so all the information would be together in a single place.

Hope this helps

ps: no need to be sorry for not finding the issue. it's ok 👍
