### ISSUE TITLE
[FEATURE] - Keyboard Shortcut - Open In New Window

### ISSUE THREAD

**Issue by josephcrawfordSRH** [alefragnani/vscode-project-manager#710]
I have my project list opened by cmd+; and I can quickly search and jump to a new project without leaving my keyboard.  I have checked the keyboard shortcut settings but I have not found the ability to add a keyboard shortcut for the list so that if I were to say hold `cmd+enter` or `shift+enter` it would tell the extension to open in a new window.  I know I can have it set to always open in new windows or I can click the icon to do so.  However, I try to grab my mouse as little as possible and would appreciate the ability to set a keyboard shortcut for this.

**Comment by alefragnani** [comment]
Hi @josephcrawfordSRH ,

This has already been requested in #76, but it depends on VS Code exposing/supporting modifiers for the keybindings. Unfortunately, this is still not available yet.

So, in this case, the best approach is to use a separate keyboard shortcut for the `List Projects to Open in New Window` command. The downside is that you need to decide _upfront_ if you want open in the current or new window.

Hope this helps

**Comment by josephcrawfordSRH** [comment]
@alefragnani that suits my needs perfectly, I was not aware there were different windows I can manage using that because I will know when I want it in a new window.  Thanks for bringing this option to my attention.
