### ISSUE TITLE
[FEATURE] Automatic encoding change

### ISSUE THREAD

**Issue by sdak75** [alefragnani/vscode-project-manager#711]
Hi,
I would like the project manager to be able to change the default encoding when opening a project. Indeed, we have projects in UTF-8 and others in Western (ISO 8859-15).
Thank you for this add-on which makes our lives much easier.

Best regards

**Comment by alefragnani** [comment]
Hi @sdak75 ,

The extension's objective is manage your project list and and easy way to switch between them, and I'm trying to avoid touching the user's settings while doing this. In the next release you will be able to assign a [Profile](https://code.visualstudio.com/docs/editor/profiles) to each project, and doing so, you could have different profiles for different encodings, and the change would be automatic.

For now, I won't add this encoding feature on the extension but, based on other similar user requests, I'll take a inner look if there are alternatives that could fit in a broader way.

Hope this helps

**Comment by sdak75** [comment]
Hi,
Thank you for this feedback and congratulations again for your add-on!
Best regards
