### ISSUE TITLE
[FEATURE] - Bind shortcut with specified project

### ISSUE THREAD

**Issue by ahuigo** [alefragnani/vscode-project-manager#714]
I think using keyboard shortcuts to switch to frequently used projects is more convenient than using a dropdown list projects with `command+alt+p`

Is it possible to bind shortcut with specified project like this?

	{
		"name": "docs",
		"shortcut":["ctrl", 1], // bind shortcut here
		"rootPath": "/Users/.../docs",
		"enabled": true
	},

**Comment by alefragnani** [comment]
Hi @ahuigo ,

Unfortunately not. Keyboard shortcuts must be defined upfront by extensions, and there is no API to _register_ keyboard shortcuts. So there would be no way to load a user defined shortcut to register in VS Code.

On the other hand, VS Code supports user defined Keyboard Shortcut, invoking command with arguments https://code.visualstudio.com/docs/getstarted/keybindings#_command-arguments. In this case, the extension could add support to arguments in the `projectManager.listProjects` command, to _filter/find_ projects with a provided name (using the arguments). 

Hope this helps
