### ISSUE TITLE
[FEATURE] - "Projects Location" setting respecting environment variables?

### ISSUE THREAD

**Issue by eddieparker** [alefragnani/vscode-project-manager#721]
I'm trying to set the projects location to use an environment variable (as it differs on different machines).  It doesn't seem to take:

![image](https://github.com/alefragnani/vscode-project-manager/assets/1141487/920361a7-718c-4765-b7c1-1c5c73d2cd41)

I don't see any obvious errors in any of the output windows, so forgive me if there's a log I should read or something.  Happy to provide more details if needed.

**Comment by alefragnani** [comment]
Hi @eddieparker ,

Right now, there is no support for environment variables, but a similar request has been already been made in #550. Feel free to upvote that issue and add comments, if you miss something.

Hope this helps
