### ISSUE TITLE
[FEATURE] - 

### ISSUE THREAD

**Issue by inmativ** [alefragnani/vscode-project-manager#722]
It would be great to display the project name in the title bar of the VSCode window so that when you switch via Alt-Tab you can see the project names.

This problem can be solved through Workspace. VSCode can display the Workspace name in the window title. But this is not always convenient, because in some projects file-indexing does not work correctly for Workspace.

I understand that this is a very narrow feature and I don’t have much hope for its implementation. But suddenly.

**Comment by alefragnani** [comment]
Hi @inmativ ,

The same requested has already been made a while ago (#98 ), but it depends on VS Code providing an API to extensions, and the VS Code team has closed previous requests on such matter. So, unfortunately, this can’t be added to the extension.

Thanks for your understanding.
