### ISSUE TITLE
[BUG] - Error while saving project when no folder is opened

### ISSUE THREAD

**Issue by monster898** [alefragnani/vscode-project-manager#725]
Saving a project in a window without an open folder results in a confusing error message for users.

We can improve the error message to let users know they are saving a project in an empty window.

<img width="1512" alt="image" src="https://github.com/alefragnani/vscode-project-manager/assets/77763617/a4ff74d9-beaa-4705-9148-baab171d6a21">

**Comment by alefragnani** [comment]
Hi @monster898 ,

This has already been reported in #683, and will be fixed in the next release, which should be available next week.

Stay tuned.
