### ISSUE TITLE
[BUG] -保存为项目不显示标签

### ISSUE THREAD

**Issue by Hql1123** [alefragnani/vscode-project-manager#730]
**Environment/version**

- Extension version:
- VSCode version: 
- OS version: 

**Steps to reproduce**

1. 
2.

**Comment by alefragnani** [comment]
Hi @Hql1123 ,

Please, could you provide more details?

Thank you

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been added since my last question. 

Thanks for your understanding
