### ISSUE TITLE
[BUG] - Why the source code for the repo: vscode-project-manager-core is missing from your github ?

### ISSUE THREAD

**Issue by peterlevel1** [alefragnani/vscode-project-manager#742]
**Environment/version**

- Extension version: any
- VSCode version: any
- OS version: any

**Steps to reproduce**

1. clone the repo of this git repo 
2. check the .gitmodules
3. no repo for https://github.com/alefragnani/vscode-project-manager-core.git

**Comment by alefragnani** [comment]
Hi @peterlevel1 ,

The core is not missing. it is just not open source anymore. 

I've plans to reopen it, as tracked in #498 . Probably in the upcoming releases, but no ETA.

Hope this helps
