### ISSUE TITLE
[FEATURE] - When using `List Projects to Open` add a shortcut to open in a new window

### ISSUE THREAD

**Issue by WeslleyNasRocha** [alefragnani/vscode-project-manager#744]
When using the `Project Manager: List Projects to Open` command, you can select an item and press `enter` to open the project, there is already a button to open it in another window, but it would be nice to add a shortcut (like `ctrl+enter` or `shift+enter`) to open in another window.

![image](https://github.com/alefragnani/vscode-project-manager/assets/19312651/5020c248-b08b-4cff-b75e-cef954a1e582)

**Comment by alefragnani** [comment]
Hi @WeslleyNasRocha ,

I would love that too, but unfortunately, VS Code does not provide a way to create such behavior, as you can notice in #76. It depends on https://github.com/microsoft/vscode/issues/18064.

Whenever an API is available, I'll update the extension to support it.

Hope this helps
