### ISSUE TITLE
[FEATURE] - Modify the tag by users ourselves

### ISSUE THREAD

**Issue by Bpc-CPU** [alefragnani/vscode-project-manager#758]
It's noticed that there is only two tags including _Personal_ and _Work_. It seems that I can't add more tags. Can you please add a feature to allow us to add the tag?

We users can add the tags and modify the tags by ourselves.
PS: I've found that I can modify the tags in the file "projects.json", but it wasn't convenient.

**Comment by alefragnani** [comment]
Hi @Bpc-CPU ,

You can improve the list of built in tags using the `projectManager.tags` setting. Just like:

```json
    "projectManager.tags": [
        "Personal", 
        "Work",
        "VS Code",
        "Learning"
    ]
```

Doing so, you will be able to select any of the ones you added.

Also, an improvement on how to use custom tags is already being tracked in #551.

Hope this helps
