### ISSUE TITLE
Make `Ctrl + Return` to open the selected project in `new window`

### ISSUE THREAD

**Issue by djhojd** [alefragnani/vscode-project-manager#76]
Hi guys,

I'm aware of the new feature (and thank you!) that will open the select project into a new window by using **Project Manager: List Projects to Open in New Window** or the setting `projectManager.openInNewWindow`. 

What I think would be nice (don't know if VS Code API even let's you) is to have only one **Project Manager: List Projects to Open** and after you select the project you want to be able to use `Enter` to open in current window and (let's say) `Shift+Enter` to open in a new window. Of course this would mean that you will need a `projectManager.openInNewWindow` which if set to `false` will do the above but if set to `true` will switch the above behavior.

What do you think?

**Comment by alefragnani** [comment]
Hi @djhojd ,

When I created the new command, I did take a look on how to accomplish the `Ctrl + `/`Shift + ` option, but didn't find any API to handle that. 

You have this in some core commands, like in `Open Recent` or when using `Ctrl + P` for opening files (which will open in new tab), but It appeared to be something handled _in low level_, not publicly available.

I really like the idea and maybe the API has been made public. I will take a look :+1:

**Comment by alefragnani** [comment]
Depends on https://github.com/Microsoft/vscode/issues/18064

**Comment by alefragnani** [comment]
Hi @djhojd @rockingskier  ,

Last week I decided to "re-focus" on some of my extensions, and I'll start to plan milestones for each of them. But this "re-focus" will be based on community feedback/support.

I'm closing this issue because the VS Code issue that it depends on, has no update from VS Code team members for more than an year. It is not planned on any Milestone, so it appears it will not be released soon. I'm subscribed to that issue, so if/when it is closed, I'll be notified.

Thank you

**Comment by jabacchetta** [comment]
For anyone coming to this issue, please remember to "thumbs up" the open VSCode issue linked above so that it is more likely to get on their radar.

**Comment by alexrussell** [comment]
Looks like you might be able to go part way towards this with the [new `alternativeAcceptSelectedQuickOpenItem` command](https://code.visualstudio.com/updates/v1_44#_quick-open-rewrite) (see bottom of linked section, just above [this section](https://code.visualstudio.com/updates/v1_44#_improved-extension-pack-display))?


But as I said [in microsoft/vscode#18064](https://github.com/microsoft/vscode/issues/18064#issuecomment-612523738) it's not clear whether you as an extension author can use this functionality or not.

**Comment by alefragnani** [comment]
Hi @alexrussell ,

I’ll take a look at the latest API in the weekend, but my initial feeling is that’s only available for the open Symbol picker, as you commented.

Stay tuned

**Comment by alexrussell** [comment]
Yup, looking very briefly into the QuickPick API I couldn't see how VS Code can tell the extension whether the alternative accept was used. The release notes also didn't seem to mention anything in extension development as far as I could see.

But it'd be interesting to see how the files/symbols picker does it, being as it presumably uses the same public APIs as extensions...?

**Comment by alefragnani** [comment]
No, it does not uses the same public API, unfortunately. 

BTW, there are other limitations in the public API. For instance, it does not allow _groups/sections_ like you see when you open the `Go to Symbol`command. I've opened an issue about this in 2016, but it is still open https://github.com/microsoft/vscode/issues/11468 😞
