### ISSUE TITLE
Feature request: clarify that projectManager.projectsLocation expects a folder, not a full path

### ISSUE THREAD

**Issue by appel** [alefragnani/vscode-project-manager#764]
First of, thank you so much for this extension, it has been indispensable for me and pretty much the first extension I install anywhere I install VS Code.

This is super minor, in fact, I hesitated to open an issue for it. But I struggled with this for a bit this morning and perhaps I'm not the only one, so I figured I'd just provide a bit of a feedback here in case it's useful.

I run VS Code on a couple of different machines and as such wanted to have a custom location for my projects.json in order to be able to sync it. I found the `projectManager.projectsLocation` setting, which has the following description:

> Indicates an alternative location where the `projects.json` file is stored

So I happily provided the full path to the projects.json file:

`C:\Users\appel\Localhost\projects.json`

And then it took both my brain cells a bit to figure out why my projects disappeared, which of course is because the extension expects a folder location, not a full path. Re-reading the description it's easier to see that I misinterpreted it, but perhaps it can be rewritten a bit to make it more obvious for non-native speakers like me. Perhaps something like this?

> Define an alternative folder path where the `projects.json` file is stored.

Come to think of it, it might not be a bad idea to allow people to provide the full path. This way you could optionally have more than one projects.json file live side-by-side (e.g `projects-windows.json` and `projects-ubuntu.json`) in the same folder. And if a folder path is provided, simply fallback to the default projects.json.

Again, super minor, but I figured I'd mention it. Feel free to close this of course and thank you again for an amazing extension!

**Comment by appel** [comment]
Apologies for the 'bug' label, I meant this to be a request but I can't seem to find where to change this now.

**Comment by alefragnani** [comment]
Hi @appel ,

Yeah, that’s a minor detail indeed, but doesn’t hurt to clarify the understanding.

Thanks for reporting

**Comment by appel** [comment]
Much obliged, @alefragnani!
