### ISSUE TITLE
[FEATURE] - Search function change

### ISSUE THREAD

**Issue by CodeGetters** [alefragnani/vscode-project-manager#772]
I want to select an item when searching and open it in a new window instead of this window, just like in a list, I can right-click and choose whether to open it in this window or a new window.
I think this can greatly improve the user experience

**Comment by alefragnani** [comment]
Hi @CodeGetters ,

Unfortunately, there is no way to use a keyboard modifier like (<kbd>Ctrl</kbd> or <kbd>Cmd</kbd>) or a right click in the project list, as VS Code does not support this yet, but the project list displayed while searching for projects contains a button in the right of each project, which allows you to open the project in a new windows.

Hope this helps
