### ISSUE TITLE
[BUG] - Version v12.8.0 is not compatible with DevContainers > v0.380.0

### ISSUE THREAD

**Issue by samraul** [alefragnani/vscode-project-manager#776]
**Environment/version**

- Extension version: v12.8.0
- VSCode version: 1.95.3
- OS version: OSX Sequoia 15.1 

**Steps to reproduce**

1. Update DevContainers to versions above `v0.380.0`
2. Launch a project using Project Manager

```
[26 ms] TypeError: Cannot read properties of undefined (reading 'hostPath')
        at un (/home/.vscode/extensions/ms-vscode-remote.remote-containers-0.388.0/dist/extension/extension.js:296:2764)
        at iU (/home/.vscode/extensions/ms-vscode-remote.remote-containers-0.388.0/dist/extension/extension.js:331:4793)
        at cd (/home/.vscode/extensions/ms-vscode-remote.remote-containers-0.388.0/dist/extension/extension.js:331:4660)
        at ZJ (/home/.vscode/extensions/ms-vscode-remote.remote-containers-0.388.0/dist/extension/extension.js:331:6310)
        at Tg (/home/.vscode/extensions/ms-vscode-remote.remote-containers-0.388.0/dist/extension/extension.js:331:16744)
        at async /home/.vscode/extensions/ms-vscode-remote.remote-containers-0.388.0/dist/extension/extension.js:406:4265
```

Does this extension need to send the host path differently now, or is this an issue with the dev-container extension itself?

Thanks!

**Comment by alefragnani** [comment]
Hi @samraul ,

No, the Project Manager extension doesn't need a `hostPath` property. If you look at the saved project in `projects.json` file, you will notice it will save the project something like:  `"rootPath": "vscode-remote://dev-container%2Bxxxxxx/workspaces/the-project-folder"`.

I don't use Docker that much on my day to day projects, but I just noticed that while _saving_ a new remote project, the path changed quite a bit. It is _larger_ than before, but the structure is almost the same. (`"rootPath": "vscode-remote://dev-container+7bxxxxxxxxxxxxxxxxxxxxxx/workspaces/the-project-folder"`.) I'm not sure when this changed (on dev-container extension side), but either way, the Project Manager extension still recognizes the path.

Did you try to _rebuild_ the dev container? Have you looked for issues in the dev-container extension's repo?

Hope this helps.

**Comment by samraul** [comment]
Hey @alefragnani,

Thanks for the reply.

> Did you try to rebuild the dev container? Have you looked for issues in the dev-container extension's repo?

I had looked into `dev-container` extension and found nothing, but your comment about rebuilding made me look into a promising direction. There is a [hostPath ](https://kubernetes.io/docs/concepts/storage/volumes/#hostpath) specified in deployments, so perhaps something has changed related to that. I will keep investigating.

Thanks!
