### ISSUE TITLE
[FEATURE] - Multiple folders for a project

### ISSUE THREAD

**Issue by jandroav** [alefragnani/vscode-project-manager#777]
I have a Terraform project made of several modules in a monorepo. I would like to create a project with the needed folders to easily work on it instead of folding and unfolding stuff. I thought the `paths` should do the trick:

```json
[
	{
		"name": "myproject",
		"rootPath": "/Users/jandroav/workspace/infrastructure/aws-control-tower/root-ou/engineering-io-ou",
		"paths": ["/Users/jandroav/workspace/infrastructure/modules/shared", "/Users/jandroav/workspace/infrastructure/modules/tenant"],
		"tags": [],
		"enabled": true
	}
]
```

Is it possible?

**Comment by alefragnani** [comment]
Hi @jandroav ,

I think the [native Multi-root workspace](https://code.visualstudio.com/docs/editor/multi-root-workspaces) would work great for your scenario. You could even save the `.code-workspace` file (which stores the multi-root configuration) inside the monorepo.

That `paths` attribute was created a bit before the multi-root workspace feature landed on VS Code, with the same purpose. But, once multi-root appeared, it became outdated and in fact, will be removed.

In the extension's side, the #677 would be an alternative. You define a new tag, apply it to each desired repo, and open all of them at once.

Hope this helps.

**Comment by jandroav** [comment]
> Hi @jandroav ,
> 
> I think the [native Multi-root workspace](https://code.visualstudio.com/docs/editor/multi-root-workspaces) would work great for your scenario. You could even save the `.code-workspace` file (which stores the multi-root configuration) inside the monorepo.
> 
> That `paths` attribute was created a bit before the multi-root workspace feature landed on VS Code, with the same purpose. But, once multi-root appeared, it became outdated and in fact, will be removed.
> 
> In the extension's side, the #677 would be an alternative. You define a new tag, apply it to each desired repo, and open all of them at once.
> 
> Hope this helps.

Thanks a lot. Really helpful!
