### ISSUE TITLE
Sort list by Git/SVN/Registered

### ISSUE THREAD

**Issue by FuriouZz** [alefragnani/vscode-project-manager#79]
Add a new option in `projectManager.sortList` to sort the list by `git`, `svn` or project registered in the `projects.json`.

**Comment by alefragnani** [comment]
Hi @FuriouZz 

Do you think a _simple sorting_ would be enough or a _grouping_ would be better? I mean, _group by type_ and _sort by name/path_?

**Comment by FuriouZz** [comment]
@alefragnani Mhm...good question. Maybe create a boolean option `group_by_type` and each group will be sorted by the `projectManager.sortList` value ?

**Comment by alefragnani** [comment]
@FuriouZz something like that 👍
