### ISSUE TITLE
showProjectNameInStatusBar does not work in 0.13.0

### ISSUE THREAD

**Issue by hotwheelsBo** [alefragnani/vscode-project-manager#84]
showProjectInStatusBar does not work #63 happened again.

macOS Sierra

<img width="532" alt="1" src="https://cloud.githubusercontent.com/assets/1224488/22273662/d75d60ea-e2dc-11e6-82b7-fa2b898da9f3.png">

after reload window

<img width="515" alt="2" src="https://cloud.githubusercontent.com/assets/1224488/22273670/e1fb9da0-e2dc-11e6-8a86-bd08115b568b.png">

the project name disappeared

**Comment by alefragnani** [comment]
Hi @hotwheelsBo ,

What _kind_ of project is it? I mean, is it saved with `Project Manager: Save Project` or is it a auto-detected `VSCode`, `Git`, `SVN`?

**Comment by hotwheelsBo** [comment]
both

**Comment by hotwheelsBo** [comment]
The problem is same with #63 

When I saved the project, the name of the project will appear in the status bar. But after I reload the window, it's disappeared.

**Comment by nfour** [comment]
Can confirm on Arch Linux.

I did try various combinations of behavior and deleted the projects.json file more than once.
Any saved project will not be reflected in the statusbar after the editor is restarted.

**Comment by nfour** [comment]
Can confirm fixed, yay!
