### ISSUE TITLE
vscode-icon-rotation support

### ISSUE THREAD

**Issue by Gama11** [alefragnani/vscode-project-manager#86]
I've been wondering if you'd consider supporting the vscode-icon-rotation extension (https://github.com/krizzdewizz/vscode-icon-rotation). It allows using custom icons for different .vscode workspaces, which in turn helps tell different vscode windows apart in the task bar. However, it's neither very popular and it only works on Windows.

The reason why it doesn't work with project-manager out of the box is that it requires VSCode to be started via a special wrapper called `codee`, so project-manager would have to run `codee <path>` as a command, rather than just calling the appropriate vscode command.

If this is too much of a niche use-case, that's fine, I could probably make a branch where I get this working just for myself. :)

**Comment by alefragnani** [comment]
Hi @Gama11 ,

Yes, that's a _niche use-case_, but why not? :smile: 

For me, the best solution would be something like [Atom does](http://flight-manual.atom.io/behind-atom/sections/interacting-with-other-packages-via-services/), but it doesn't exists in VSCode (I will post an issue there by the way).

But as a workaround, I ask you first. Does the `codee` wrapper is a `command line application` like `code.exe`? If yes, does it supports the same parameters as `code.exe` and `code-insiders.exe`? If yes, then simply ressurecting the `codePath` setting would be enough.

What do you think?

**Comment by Gama11** [comment]
Awesome! 👍 

So, yes, running `codee <path>` on the command line works. I don't think it supports any of the other parameters though (`codee --help` gives me nothing).

**Comment by alefragnani** [comment]
It should support, at least, `-r` or `--reuse-window`, which means **Force opening a file or folder in the last active window**. Otherwise the `projectManager.openInNewWindow` setting would have no effect.

Talk to the other extension's developer and see if he can (or already does) support this. Then I could add it here as well 👍

**Comment by Gama11** [comment]
Looks like `-r` is not currently supported. @krizzdewizz is that something that could be added? :)

**Comment by krizzdewizz** [comment]
Hi, yes. That should be possible. I'll take a look into it.

**Comment by Gama11** [comment]
@krizzdewizz Any update on this?

I might be able to take a look at it myself if you point me in the right direction.

**Comment by krizzdewizz** [comment]
Sorry for the long delay. What should work is: in the file "ahk/codee.ahk", you could pass more parameters along: Run, "code" "%1%" "%2%" "%3%" "%4%",, Hide
up until 9 or so. The build/test procedure is described in README.md.

**Comment by Gama11** [comment]
@krizzdewizz Thanks for pointing me in the right direction. I was able to make it take additional arguments that way. Unfortunately, it looks like the `--reuse-window` option has no effect, perhaps VSCode's logic for reusing windows isn't compatible with it being run through a wrapper application like this... :/

I still made a pull request, since it could still be useful to pass on parameters, and others like `--disable-extensions` seem to work fine: https://github.com/krizzdewizz/vscode-icon-rotation/pull/2

**Comment by krizzdewizz** [comment]
@Gama11 Thanks for the pull request. I've merged it and will release a new version later today.

**Comment by Gama11** [comment]
I remember that I had some issues with this, but I don't remember what specifically. I'm no longer interested in looking into this though, and it doesn't really look like anybody else is either, so I'll just go ahead and close this. :)
