### ISSUE TITLE
On a mac, dots in project's rootPath are not valid

### ISSUE THREAD

**Issue by louissalin** [alefragnani/vscode-project-manager#90]
The following project fails to be displayed when I list my projects. Renaming the directory and removing the dot in the rootPath made it show up in the list.

This happened in version 0.13.1 on Mac OS.

```
[
	{
		"name": "some-project",
		"rootPath": "$home/projects/some.project",
		"paths": [],
		"group": ""
	}
]
```

**Comment by alefragnani** [comment]
Hi @louissalin ,

Unfortunatelly I don't have a macOS/Linux machine to test, and in Windows it seems to be working fine. 

I will try to find someone with an available OS to test, but until there, I can't fix it. Maybe someone make a PR to help.

**Comment by BonDoQ** [comment]
Hi @louissalin,

I am using a mac machine, I will check it  on the weekend and give you more details.
Stay tuned ..

**Comment by alefragnani** [comment]
@BonDoQ,  thanks for your help :+1:

**Comment by BonDoQ** [comment]
Hi @louissalin 

The problem didn't happen to me on my mac  on version 0.13.2

`projects.json` : 

<img width="375" alt="screen shot 2017-02-04 at 12 28 21 pm" src="https://cloud.githubusercontent.com/assets/6190844/22618140/8cd2714a-ead5-11e6-8322-d339a0afed89.png">

`Screenshot`
<img width="602" alt="screen_shot_2017-02-04_at_12_28_13_pm" src="https://cloud.githubusercontent.com/assets/6190844/22618182/8e353c6a-ead6-11e6-8bbe-8880abaf9bc6.png">

can you give try out again on the new version ?

**Comment by alexus85** [comment]
same here (but on Windows 10) .. it couldn't read the following path ` "rootPath": "c:\\Projects\\test.web.client",`

**Comment by louissalin** [comment]
Hi @BonDoQ, I tried to reproduce the issue on version 0.13.2 with an empty directory containing a dot and everything worked fine. However, when I copied one of my existing git projects to a directory containing a dot, things started breaking again.

In the attached screenshot, you can see the projects.json file and the list of projects I can open. The project list used to have my simple test directory, but after copying my existing project it looks like the project list can't refresh based on the json file.

<img width="851" alt="screen shot 2017-02-04 at 11 01 16 am" src="https://cloud.githubusercontent.com/assets/278391/22620109/d110f400-eac9-11e6-9035-0e27c428138a.png">

Thank you so much for the help so far! This is definitely not a show stopper as we have workarounds. I just thought I'd bring it to your attention because we did spend some time figuring out the cause of this issue.

**Comment by louissalin** [comment]
Actually, I lied... Restarting VS code after editing the projects.json file cleared everything up and everything worked fine.

Thanks for the help!

**Comment by alefragnani** [comment]
Good to know the problem is solved. It was really strange to have that behavior. Maybe the PR #87 has fixed it too 😄 

By the way, the _caching_ issue will be handled in #85 . 

Thanks again @BonDoQ for your help, and @louissalin for your patience 👍
