### ISSUE TITLE
List project to open feature always open new window

### ISSUE THREAD

**Issue by kevinrambaud** [alefragnani/vscode-project-manager#91]
Running vscode on macOS Serria 10.12.3 with Project Manager 0.13.2, when I use the feature "Project Manager: List project to open" and select a project, a new window is opened. I thought that this feature would open a project in the same window that the current one.

Is this a bug ?

**Comment by alefragnani** [comment]
Hi @kevinrambaud ,

This is the default behavior (the same as the new command `List Project to Open in New Window`). But for this command, you can change it to open in the _current window_, you just have to set `projectManager.openInNewWindow`  to `false`.

Hope this helps

**Comment by EmmittPu** [comment]
@alefragnani  To set projectManager.openInNewWindow to false in where or which files? pleas!

**Comment by alefragnani** [comment]
Do it in *User Settings*, just like you customize any other VSCode setting :+1: 

Ps. I'll change that in the near future, removing this setting and using `false` as the default behavior, since now there are two commands to Open Project...
