### ISSUE TITLE
Project sorting when filtering

### ISSUE THREAD

**Issue by lypscan** [alefragnani/vscode-project-manager#92]
If I set a custom sort order, for example:
**"projectManager.sortList": "Saved",**
when I search (filter from the project listing) for a specific project, this setting is ignored, and filtered projects are sorted alphabetically. 
I think this used to work properly in a previous version of this extension... I'm not sure, though...

**Comment by alefragnani** [comment]
Hi @lypscan ,

The setting is intended to work only for _listing_, because the _filtering_ is not possible to customize. It's a VSCode limitation.

On the other hand, there is an open issue to improve the ranking https://github.com/Microsoft/vscode/issues/14879.

Hope this helps

**Comment by lypscan** [comment]
Hi @alefragnani ,

Thanks for clarifying the situation.
