### ISSUE TITLE
Add keyboard shortcut to switch between open projects

### ISSUE THREAD

**Issue by peterloron** [alefragnani/vscode-project-manager#95]
It would be very handy to have a keyboard shortcut to quickly switch between open projects.

**Comment by alefragnani** [comment]
Hi @peterloron ,

This is already possible, using the _native_ command **Switch Window**. You just have to define a `keybinding` for it. 

As already discussed in #48, there is no API for that _(to be aware of other VSCode instances)_ so the only way is to use the **Switch Window** command.

Hope this helps

**Comment by peterloron** [comment]
Ah! Thanks. I missed that when I was looking through the key bindings.
