### ISSUE TITLE
Support window.title via variable for project?

### ISSUE THREAD

**Issue by Idealien** [alefragnani/vscode-project-manager#98]
"projectManager.showProjectNameInStatusBar": true shows at the bottom of window. Status Bar is great! window title bar would be even better. Especially b/c Feb 2017 Release of VSCode - https://code.visualstudio.com/updates/v1_10#_february-release-summary - enabled a config item - window.title - that gives much more flexibility to the title bar of window.

Is it possible to get a ${projectManager.Name} variable or similar that could be put into the window.title config?

**Comment by alefragnani** [comment]
Hi @Idealien ,

The _release notes_ doesn't say anything about _custom variables_, so at first sight, it doesn't seems to be possible. Unless the extension itself did _override_ the `window.title` attribute in `workspace settings` (the `.vscode\settings.json` file that VSCode creates).

I will ask the VSCode team, to see if they intend to support external variables, so I could _publish_ the _Project Name_ to be used in `user/workspace settings`

Hope this helps

**Comment by alefragnani** [comment]
Closing as VS Code team has closed the referenced issue.

**Comment by Idealien** [comment]
It's coming up on the end of their "will not consider for 6 - 12 months" period.
Has anything changed in VS Code code landscape that this might be re-considered re-opened you think?

**Comment by alefragnani** [comment]
I believe they will re-consider it 👍

**Comment by aaron13223** [comment]
I made a quick extension based on [this](https://github.com/microsoft/vscode/issues/202991#issuecomment-2310582766)

It works!
