### ISSUE TITLE
Auto detection always uses directory as project name

### ISSUE THREAD

**Issue by Gama11** [alefragnani/vscode-project-manager#99]
With project auto-detection, project manager always uses the directory name as the project name. However, there are situations where this is not helpful as the direct name itself is not very meaningful.

One such example is when using the `haxelib git` command of Haxelib (the package manager for [Haxe](http://haxe.org/)). It's used to install a package from a git repo, and when doing so, it places the project in `lib/<library-name>/git` (because the parent directory `<library-name>` could also contain other versions of the package).

![](http://i.imgur.com/thCPZ7T.png)

Of course, this means that every package installed this way shows up as "git" in the project picker. Perhaps it could be a bit smarter about this, and disambiguate when there are duplicate project names? I think vscode does a good job with this in tab names (it's easily noticable that the second Readme is in a `server` subdir):

![](http://i.imgur.com/YtNwUG6.png)

Of course, technically the "open project" entries  already include their respective directories, but not in the project name, so they are not searchable. I remember when they were included in searches, that caused other issues: #67

If anyone else has similar issues: for now I've successfully been using this workaround of manually regex-replacing "git" names with the names of the immediate parent directories in the generated `projects_cache_git.json`:

- find: `([\w-]+)\\\\git",\n\t\t"name": ("git")`
- replace: `$1\\\\git",\n\t\t"name": "$1"`

**Comment by alefragnani** [comment]
Hi @Gama11 ,

Sorry for the delay, it's been a busy week in other side projects 🏃 .

I see two different alternatives for this:

1. Display the `base-folder` in the area below the `name`/`path`, just like it displays when the path does not exists. I could add this area to the search criteria, so it would be searchable as well. The only _collateral effect_ is that the sentence `Path does not exist` would also be searchable 😄 

2. Add the `base-name` to the `Project Name`, literally (only the disambiguation piece, like **yaml\git**, **flixel-tools\git**, or between parentesis, like **git (yaml)**, **git (flixel-tools)**. It's similar to the Tab approach, but in this case, the name and the disambiguation piece would be both, displayed together, before the `path`.

Of course, in any case, only when you have duplicated project names. 

What do you think?

**Comment by Gama11** [comment]
I think I'd prefer the second option, simply because it's a bit more compact (the "Path does not exist" message doubles the height of an entry). Also, "git" alone as a name is not very useful to begin with, so there's not much value in keeping the name to just that. And `yaml/git` seems slightly nicer than `git (yaml)` because it puts the important part first.

I assume `base-name` would be detected automatically based on duplicated project names?

**Comment by alefragnani** [comment]
That's my preferred too, and yes, the `base-name` would be automatically detected :+1:

**Comment by Gama11** [comment]
I've changed my setup, so this is no longer an issue for me.
